// Shared internal helpers for the tool registry and domain files.
// This file is auto-generated by scripts/extract_helpers.py — do not edit
// manually except to add new exports. Domain files in ./domains/ import
// from here. registry.ts re-exports the public API.

import { execFile, spawn } from "node:child_process"
import { randomUUID } from "node:crypto"
import { promisify } from "node:util"
import { createWriteStream, existsSync, mkdirSync, openSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs"
import { dirname, join, relative, resolve, sep } from "node:path"
import { pathToFileURL } from "node:url"
import { z, type ZodType } from "zod"
import { ensureDirs, getPaths } from "../ipc/protocol.ts"
import { MONOLITO_ROOT } from "../system/root.ts"
import { type McpClient, createMcpClient, getDefaultMcpServers } from "../mcp/client.ts"
import { getSharedLspClient } from "../lsp/client.ts"
import { normalizeChannelsConfigForWrite, readChannelsConfig, writeChannelsConfig } from "../channels/config.ts"
import {
  appendActionLog,
  addGraphTriple,
  fileMemory,
  invalidateGraphTriple,
  queryGraphEntity,
  recallMemory,
  listWings,
  listRooms,
  listProfiles,
  createProfile,
  readBootWing,
  writeBootWing,
  listBootWings,
  createBootWing,
  bootWingExists,
  ensureBootWings,
  readConfigWing,
  writeConfigWing,
  getSession,
  listSessions,
  tailEvents,
  writeSessionSource,
  writeSessionTask,
  listSessionTasks,
  deleteSessionTask,
  getDb,
  type SessionTask,
  upsertSemanticTool,
  querySemanticTools,
  upsertRalphRule,
  listDynamicSkills,
  saveDynamicSkill,
  getDynamicSkill,
  deleteDynamicSkill,
  incrementSkillTelemetry,
  archiveDynamicSkill,
  restoreArchivedSkill,
} from "../session/store.ts"
import { isEmbeddingsUnavailableError } from "../session/embeddings.ts"
import { type AgentOrchestrator } from "../runtime/orchestrator.ts"
import { redactSensitiveValue } from "../security/redact.ts"
import { type Logger } from "../logging/logger.ts"
import { CONFIG_WING_ORDER, type ConfigWingName } from "../config/configWings.ts"
import { coerceConfigRecord } from "../config/wingValue.ts"
import { loadAndApplyModelSettings, readModelSettings } from "../runtime/modelConfig.ts"
import { getActiveProfile, activateProfile } from "../runtime/modelRegistry.ts"
import {
  deployManagedTtsContainer,
  getManagedTtsBaseUrl,
  getManagedTtsStatus,
  listManagedTtsContainers,
  normalizeTtsConfig,
  removeManagedTtsContainer,
  stopManagedTtsContainer,
} from "../tts/managed.ts"
import {
  deployManagedSttContainer,
  getManagedSttBaseUrl,
  getManagedSttStatus,
  listManagedSttContainers,
  normalizeSttConfig,
  removeManagedSttContainer,
  stopManagedSttContainer,
  transcribeManagedAudioFile,
} from "../stt/managed.ts"
import { deploySearxng, SEARXNG_URL } from "../websearch/managed.ts"
import { readWebSearchConfig } from "../websearch/config.ts"
import { isBootWingName, BOOT_WING_ORDER } from "../bootstrap/bootWings.ts"

export const execFileAsync = promisify(execFile)
export const DEFAULT_GREP_LIMIT = 250
export const DEFAULT_BASH_TIMEOUT_MS = 120_000
export const MAX_EXEC_BUFFER = 4 * 1024 * 1024
export const TELEGRAM_AUDIO_FORMATS = new Set(["mp3", "m4a", "aac"])
export const TELEGRAM_VOICE_FORMATS = new Set(["ogg", "opus"])
export const TTS_RESPONSE_FORMATS = new Set(["mp3", "opus", "aac", "flac", "wav", "pcm"])

export function formatToolError(error: unknown): string {
  return JSON.stringify({
    success: false,
    error: error instanceof Error ? error.message : String(error),
  })
}

export const configWingZod = z.enum([...CONFIG_WING_ORDER] as [ConfigWingName, ...ConfigWingName[]])
export const strictRecordZod = z.record(z.string(), z.unknown())
export const modelProfileZod = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  provider: z.enum(["minimax", "ollama", "openai_compatible", "anthropic_compatible"]),
  baseUrl: z.string(),
  apiKey: z.string(),
  model: z.string().min(1),
  active: z.boolean(),
}).strict()
export const modelRegistryZod = z.object({
  version: z.literal(1),
  profiles: z.array(modelProfileZod),
}).strict()
export const systemConfigZod = z.object({
  modelConfig: z.object({
    protocol: z.string().min(1),
  }).strict(),
  env: z.object({
    ANTHROPIC_BASE_URL: z.string(),
    ANTHROPIC_AUTH_TOKEN: z.string(),
    ANTHROPIC_MODEL: z.string(),
    API_TIMEOUT_MS: z.string(),
    MAX_BUDGET_USD: z.string(),
  }).strict(),
}).strict()
export const webSearchConfigZod = z.object({
  provider: z.enum(["default", "searxng", "brave", "serper", "tavily"]),
  apiKey: z.string().optional(),
}).strict()
export const hookMatcherZod = z.object({
  tool: z.string().optional(),
  input: z.string().optional(),
  session: z.string().optional(),
  profile: z.string().optional(),
}).strict()
export const hookDefinitionZod = z.object({
  matcher: hookMatcherZod.optional(),
  commands: z.array(z.object({ cmd: z.string().min(1) }).strict()),
}).strict()
export const policyConfigZod = z.object({
  permissions: z.object({
    mode: z.enum(["default", "acceptEdits", "bypassPermissions"]),
    rules: z.array(z.object({
      tool: z.string().optional(),
      action: z.enum(["allow", "deny", "ask"]),
      input: z.string().optional(),
    }).strict()),
  }).strict(),
  hooks: z.object({
    PreToolUse: z.array(hookDefinitionZod),
    PostToolUse: z.array(hookDefinitionZod),
    SessionStart: z.array(hookDefinitionZod),
    SessionEnd: z.array(hookDefinitionZod),
  }).strict(),
}).strict()
export const bootWriteInputZod = z.object({
  wing: z.string().min(1),
  content: z.string(),
  action: z.enum(["overwrite", "append"]).optional().default("overwrite"),
}).strict()
export const bootCreateWingInputZod = z.object({
  wing: z.string().min(1).regex(/^[A-Za-z][A-Za-z0-9_]*$/, "wing must be alphanumeric/snake_case and start with a letter"),
}).strict()
export const manageConfigInputZod = z.object({
  action: z.enum(["read", "write", "get", "set", "activate_model"]),
  wing: configWingZod.optional(),
  path: z.string().optional(),
  value: z.unknown().optional(),
}).strict().superRefine((input, ctx) => {
  if (input.action !== "activate_model" && !input.wing) {
    ctx.addIssue({
      code: "custom",
      path: ["wing"],
      message: "wing is required for actions other than activate_model",
    })
  }
  if (input.action === "write" && input.value === undefined) {
    ctx.addIssue({
      code: "custom",
      path: ["value"],
      message: "value is required when action='write'",
    })
  }
  if (input.action === "set" && input.path === undefined) {
    ctx.addIssue({
      code: "custom",
      path: ["path"],
      message: "path is required when action='set'",
    })
  }
  if (input.action === "set" && input.value === undefined) {
    ctx.addIssue({
      code: "custom",
      path: ["value"],
      message: "value is required when action='set'",
    })
  }
  if (input.action === "get" && input.path === undefined) {
    ctx.addIssue({
      code: "custom",
      path: ["path"],
      message: "path is required when action='get'",
    })
  }
  if (input.action === "activate_model" && input.value === undefined) {
    ctx.addIssue({
      code: "custom",
      path: ["value"],
      message: "value (profileId) is required when action='activate_model'",
    })
  }
})

export function normalizeIntentText(value: string) {
  return value
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase()
}

export function isImageIntentText(value: string) {
  return /\b(imagen(?:es)?|foto(?:s)?|picture(?:s)?|photo(?:s)?|image(?:s)?|vision|visual)\b/.test(normalizeIntentText(value))
}

export function isTelegramPhotoDeliveryRequest(value: string) {
  const normalized = normalizeIntentText(value)
  return isImageIntentText(value) && /\b(pasame|pasa(?:me)?|mandame|manda(?:me)?|enviame|envia(?:me)?|send|send me|pasar|mandar|enviar)\b/.test(normalized)
}

// Soft detector for "the user wants visual verification of an image".
//
// The previous regex also matched the bare words `vision` and `visual`,
// which produced false positives on medical ("tengo problemas de
// visión") and aesthetic ("dame una imagen con buena visual") uses.
// The LLM was forced to call VisionAnalyze on every "visión" mention.
//
// This new version:
//   - drops the bare `vision|visual` branches
//   - keeps all the explicit verification verbs
//   - adds the "que sea la/el <person>" and "correcta/as/o/os" patterns
//   - the soft "real" branch is kept (used in "es la imagen real?")
//
// The function is still binary (true/false) but the caller should treat
// the result as a soft default, not a hard requirement: the user can
// always say "no analices, solo mandá" (see imageVerificationSkipped)
// to override.
export function requiresImageVerificationText(value: string) {
  const normalized = normalizeIntentText(value)
  return /\b(verifica(?:r|me|las|los)?|valid(?:a|ar|ame|alas|alos)|analiza(?:r|me|las|los)?|describe(?:me|las|los)?|confirm(?:a|ar|ame)|coincid(?:e|an)|que sea (la|el) (persona|actor|actriz|mismo|misma)|correct(a|as|o|os)|real(es)?)\b/.test(normalized)
}

// Soft opt-out detector: when the user says "no analices", "skip verify",
// "solo mandá", etc., the flow MUST skip VisionAnalyze regardless of
// what requiresImageVerificationText says. This makes the policy
// overridable in plain Spanish/English without the LLM having to
// discover a special keyword.
export function imageVerificationSkipped(value: string) {
  const normalized = normalizeIntentText(value)
  // Pattern A: explicit negation of the verify action
  //   "no analices", "no analices las fotos", "no verifiques",
  //   "sin verificar", "skip verify", "skip verification",
  //   "no quiero verificación", "evitá el análisis"
  // Match: <negation-word> <up to 3 intervening words> <verify-verb>
  // The intervening words are bounded to avoid swallowing the whole
  // sentence (e.g. "no quiero que analices" still matches).
  const negationPattern =
    /\b(no|sin|skip|evit(a|ar|ame))\b(?:\s+\S+){0,3}\s+(analices|analizar|verifiques?|verific(ar|aciones?|acion)|verificar|verify|verification|analisis|vision(es)?|visual|valid(ar|aci[oó]n))\b/
  // Pattern B: "solo mandá/enviá" — user explicitly wants delivery only
  //   "solo mandá", "solo enviá", "just send"
  const soloDeliveryPattern = /\b(solo|just|simplemente)\b\s+(mand(a|ame|ar|emos)|envi(a|ame|ar|emos)|send)\b/
  return negationPattern.test(normalized) || soloDeliveryPattern.test(normalized)
}

export function latestActionableUserText(rootDir: string, sessionId: string) {
  const session = getSession(rootDir, sessionId)
  const message = session?.messages
    .filter(entry => entry.role === "user")
    .slice()
    .reverse()
    .find(entry => {
      const text = entry.text.trim()
      return text && !text.startsWith("<task-notification>") && !text.startsWith("/")
    })
  return message?.text ?? ""
}

export function buildTelegramPhotoWorkerTask(task: string, parentSessionId: string, latestUserText: string) {
  const chatId = parentSessionId.startsWith("telegram-") ? parentSessionId.slice("telegram-".length) : ""
  if (!chatId) return task
  // Decision logic (soft policy):
  //   1. If the user explicitly opts out ("no analices", "solo mandá"),
  //      skip VisionAnalyze even if the verification regex would match.
  //   2. Otherwise, if the user asked for verification explicitly,
  //      recommend VisionAnalyze but do not force it.
  //   3. Otherwise, default to no verification (fast delivery).
  const combinedText = `${latestUserText}\n${task}`
  const skipped = imageVerificationSkipped(combinedText)
  const shouldVerify = !skipped && requiresImageVerificationText(combinedText)
  const imageHandlingSteps = shouldVerify
    ? [
        "2. Como el pedido parece pedir verificación visual, se sugiere validar cada candidato con VisionAnalyze. Si el modelo activo no soporta visión, la herramienta devuelve un error claro: reportalo y sugerí al usuario cambiar de modelo. Descartá cualquier resultado sin descripción útil o que no coincida con el pedido.",
        "3. NO envíes mensajes ni archivos al usuario. Tu salida es solo para el coordinador.",
        "4. Devolvé los local_path validados por la herramienta y una descripción breve de cada imagen.",
        "5. Si la verificación es informativa, podés devolver URLs directas junto con la descripción de VisionAnalyze; el coordinador decidirá.",
        "6. Si no lográs validar ninguna foto, respondé claramente que no hay local_path validado y por qué.",
      ]
    : skipped
      ? [
          "2. El usuario pidió explícitamente saltarse la verificación visual. NO uses VisionAnalyze en este turno.",
          "3. NO uses WebFetch ni scraping de paginas fuente. Usá directamente los `image_url` que devuelve ImageSearch.",
          "4. NO envíes mensajes ni archivos al usuario. Tu salida es solo para el coordinador.",
          "5. Devolvé las mejores `image_url` directas, con título/fuente si están disponibles.",
        ]
      : [
          "2. NO uses VisionAnalyze salvo que el pedido original solicite verificacion/analisis visual (o que el query sea ambiguo y vos mismo decidas que ayuda validar).",
          "3. NO uses WebFetch ni scraping de paginas fuente. Usá directamente los `image_url` que devuelve ImageSearch.",
          "4. NO envíes mensajes ni archivos al usuario. Tu salida es solo para el coordinador.",
          "5. Devolvé las mejores `image_url` directas, con título/fuente si están disponibles.",
          "6. Si no lográs obtener URLs directas, respondé claramente que no hubo resultados usables y por qué.",
        ]
  return [
    "Tarea interna de obtención y verificación de fotos para entrega por Telegram.",
    "",
    "Pedido original del usuario:",
    latestUserText.trim() || task.trim(),
    "",
    "Recomendaciones operativas (no contractuales):",
    "1. Usá ImageSearch para buscar candidatos directos de imagen (`image_url`).",
    ...imageHandlingSteps,
    "",
    "Instrucción generada originalmente por el coordinador:",
    task.trim(),
  ].join("\n")
}

export type ToolContext = {
  rootDir: string
  cwd: string
  abortSignal?: AbortSignal
  traceId?: string
  profileId?: string
  getMcpClient?: (serverName: string) => Promise<McpClient>
  orchestrator?: AgentOrchestrator
  logger?: Logger
  sessionId?: string
  // Optional whitelist of tool names the LLM is allowed to call in this turn.
  // Used by SkillsAgent to restrict synthetic turns to lifecycle tools only.
  allowedToolNames?: string[]
  // Set to true for synthetic SkillsAgent turns so tools (e.g. CreateSkill)
  // can mark provenance as "agent" instead of "user".
  isSkillsSynthetic?: boolean
  runtime?: {
    acquireJobGroupForBatch: (sessionId: string) => string
    getSystemStatus?: () => Promise<unknown>
    gracefulRestart?: (reason?: string) => void
    registerPendingPermission?: (permissionId: string, resolve: (decision: "allow" | "deny" | "ask") => void) => void
    emit?: (event: any) => void
    hasAdultMode?: (sessionId: string) => boolean
  }
  querySessionStatus?: (sessionId: string) => string
  queryCost?: () => string
  queryStats?: (sessionId: string) => string
  compactSession?: (sessionId: string, maxMessages?: number) => string
}

export type ToolInputSchema = {
  type: "object"
  properties: Record<string, unknown>
  required?: string[]
  additionalProperties?: boolean
}

export type ToolDefinition = {
  name: string
  aliases?: string[]
  permissionTier: "read" | "edit"
  description: string
  inputSchema: ToolInputSchema
  concurrencySafe?: boolean | ((input: Record<string, unknown>) => boolean)
  sideEffect?: boolean
  validate?: (input: Record<string, unknown>) => string | null
  run: (input: Record<string, unknown>, context: ToolContext) => Promise<unknown>
  // ── Fase 0 extension (additive, all optional, no breaking) ────────────────
  /** upstream parity: marker for read-only tools. Lets permission gate fast-path
   *  allow decisions without invoking the AST parser. */
  isReadOnly?: boolean
  /** upstream parity: marker for tools whose results can be safely collapsed in UI
   *  (Grep, Glob, Read, WebSearch). */
  isSearchOrReadCommand?: boolean
  /** upstream parity: optional per-tool permission gate. Returns the gate result
   *  before the tool runs. If undefined, the runtime default applies
   *  (permissionTier-based + global policyConfigZod rules). */
  checkPermissions?: (input: Record<string, unknown>, context: ToolContext) => Promise<"allow" | "ask" | "deny"> | "allow" | "ask" | "deny"
  /** upstream parity: marker for MCP-sourced tools. Affects UI rendering and
   *  isOpenWorld defaults. */
  isMcp?: boolean
  /** upstream parity: MCP open-world flag. Defaults to true for MCP tools. */
  isOpenWorld?: boolean
  /** upstream parity: result size cap in characters. Triggers truncation marker
   *  when exceeded. */
  maxResultSizeChars?: number
  /** upstream parity: optional function to truncate results. If undefined and
   *  maxResultSizeChars is set, the runtime applies a default truncate. */
  isResultTruncated?: (output: unknown) => boolean
  /** upstream parity: optional async prompt extension. Lets tools contribute extra
   *  prompt text to the model call. */
  prompt?: string | (() => string | Promise<string>)
  /** upstream parity: small string passed to the auto-classifier for fast
   *  permission routing. */
  toAutoClassifierInput?: (input: Record<string, unknown>) => string
}

export function withSafeToolFailure(tool: ToolDefinition): ToolDefinition {
  return {
    ...tool,
    async run(input, context) {
      try {
        return await tool.run(input, context)
      } catch (error) {
        return formatToolError(error)
      }
    },
  }
}

export const emptyInputSchema: ToolInputSchema = {
  type: "object",
  properties: {},
  additionalProperties: false,
}

export const optionalPathInputSchema: ToolInputSchema = {
  type: "object",
  properties: {
    path: { type: "string" },
  },
  additionalProperties: false,
}

export async function resolveWorkspacePath(
  rootDir: string,
  cwd: string,
  target = ".",
  context?: ToolContext,
  toolName?: string,
) {
  return resolve(cwd, target)
}

export function toWorkspaceRelative(rootDir: string, absolute: string) {
  const relativePath = relative(rootDir, absolute)
  return relativePath.length === 0 ? "." : relativePath
}

export function normalizePathInput(input: Record<string, unknown>, key = "path") {
  const value = input[key]
  return typeof value === "string" && value.length > 0 ? value : "."
}

export function buildTraceEnv(traceId?: string) {
  const env = { ...process.env }
  delete env.ANTHROPIC_API_KEY
  delete env.ANTHROPIC_AUTH_TOKEN
  delete env.OPENAI_API_KEY
  if (traceId) env.TRACEPARENT = traceId
  return env
}

export function requireString(input: Record<string, unknown>, key: string) {
  const value = input[key]
  if (typeof value !== "string" || value.length === 0) {
    throw new Error(`${key} must be a non-empty string`)
  }
  return value
}

export function optionalString(input: Record<string, unknown>, key: string) {
  const value = input[key]
  return typeof value === "string" && value.length > 0 ? value : undefined
}

export function optionalNumber(input: Record<string, unknown>, key: string) {
  const value = input[key]
  return typeof value === "number" && Number.isFinite(value) ? value : undefined
}

export function compactWhitespace(value: string) {
  return value.replace(/\s+/g, " ").trim()
}

export function isVisionConnectionFailure(error: unknown) {
  const message = error instanceof Error ? error.message : String(error)
  return /\b(fetch failed|econnrefused|local vision service unavailable|connect|timed? out|timeout)\b/i.test(message)
}

export function truncateText(value: string, max = 220) {
  const compact = compactWhitespace(value)
  return compact.length > max ? `${compact.slice(0, Math.max(0, max - 3))}...` : compact
}

export function stringifyValue(value: unknown, max = 220) {
  if (typeof value === "string") return truncateText(value, max)
  try {
    return truncateText(JSON.stringify(value), max)
  } catch {
    return truncateText(String(value), max)
  }
}

export function decodeBasicHtmlEntities(value: string) {
  return value
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&quot;/gi, "\"")
    .replace(/&#39;|&apos;/gi, "'")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&#(\d+);/g, (match, code: string) => {
      const parsed = Number(code)
      return Number.isFinite(parsed) ? String.fromCodePoint(parsed) : match
    })
    .replace(/&#x([0-9a-f]+);/gi, (match, code: string) => {
      const parsed = Number.parseInt(code, 16)
      return Number.isFinite(parsed) ? String.fromCodePoint(parsed) : match
    })
}

export function htmlToReadableText(html: string) {
  return decodeBasicHtmlEntities(html
    .replace(/<!--[\s\S]*?-->/g, " ")
    .replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, " ")
    .replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, " ")
    .replace(/<noscript\b[^>]*>[\s\S]*?<\/noscript>/gi, " ")
    .replace(/<svg\b[^>]*>[\s\S]*?<\/svg>/gi, " ")
    .replace(/<(br|hr)\b[^>]*>/gi, "\n")
    .replace(/<\/(p|div|section|article|header|footer|li|tr|h[1-6])>/gi, "\n")
    .replace(/<[^>]*>/g, " "))
    .replace(/[ \t\f\v]+/g, " ")
    .replace(/\s*\n\s*/g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim()
}

export function promptTerms(prompt: string) {
  const stopwords = new Set([
    "para", "por", "con", "una", "uno", "unos", "unas", "del", "las", "los", "the",
    "and", "for", "from", "that", "this", "especially", "sobre", "como", "cual", "cuál",
  ])
  return Array.from(new Set(prompt
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .match(/[a-z0-9]{4,}/g) ?? []))
    .filter(term => !stopwords.has(term))
}

export function selectRelevantText(content: string, prompt: string, maxChars: number) {
  if (content.length <= maxChars) return content

  const normalizedContent = content
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
  const terms = promptTerms(prompt)
  const anchors = terms
    .flatMap(term => {
      const positions: number[] = []
      let from = 0
      while (positions.length < 20) {
        const index = normalizedContent.indexOf(term, from)
        if (index === -1) break
        positions.push(index)
        from = index + term.length
      }
      return positions
    })
    .sort((a, b) => a - b)

  if (anchors.length === 0) return `${content.slice(0, maxChars).trimEnd()}\n...[truncated]`

  const windowSize = Math.min(1800, Math.max(700, Math.floor(maxChars / 3)))
  const scored = anchors.map(anchor => {
    const start = Math.max(0, anchor - Math.floor(windowSize / 3))
    const end = Math.min(content.length, start + windowSize)
    const windowText = normalizedContent.slice(start, end)
    const score = terms.reduce((sum, term) => sum + (windowText.includes(term) ? 1 : 0), 0)
    return { start, end, score }
  })
    .sort((a, b) => b.score - a.score || a.start - b.start)

  const selected: Array<{ start: number; end: number }> = []
  for (const candidate of scored) {
    if (selected.some(range => candidate.start < range.end && candidate.end > range.start)) continue
    selected.push({ start: candidate.start, end: candidate.end })
    const used = selected.reduce((sum, range) => sum + range.end - range.start, 0)
    if (used >= maxChars) break
  }

  return selected
    .sort((a, b) => a.start - b.start)
    .map(range => {
      const prefix = range.start > 0 ? "... " : ""
      const suffix = range.end < content.length ? " ..." : ""
      return `${prefix}${content.slice(range.start, range.end).trim()}${suffix}`
    })
    .join("\n\n---\n\n")
    .slice(0, maxChars)
    .trimEnd()
}

type ForensicsIntent = "auto" | "history" | "actions" | "delegation" | "origin"

export function resolveForensicsIntent(raw: string | undefined): ForensicsIntent {
  switch (raw) {
    case undefined:
    case "auto":
    case "history":
    case "actions":
    case "delegation":
    case "origin":
      return raw ?? "auto"
    default:
      throw new Error(`Unsupported intent: ${raw}`)
  }
}

export function inferForensicsIntent(question: string | undefined): ForensicsIntent {
  const normalized = compactWhitespace(question ?? "").toLowerCase()
  if (!normalized) return "actions"
  if (/\b(worker|workers|agent|agente|sub.?agente|delegat|deleg|parallel|paralelo|spawn)\b/.test(normalized)) return "delegation"
  if (/\b(de donde|de dónde|origen|source|fuente|salio|salió|conclusion|conclusión)\b/.test(normalized)) return "origin"
  if (/\b(que dije|qué dije|que dijo|qué dijo|mensaje|conversation|conversaci|chat|historial)\b/.test(normalized)) return "history"
  return "actions"
}

export function pickForensicsSession(rootDir: string, profileId: string | undefined, preferredSessionId: string | undefined) {
  if (preferredSessionId) {
    const exact = getSession(rootDir, preferredSessionId)
    if (!exact) throw new Error(`Session ${preferredSessionId} not found`)
    return exact
  }
  const sessions = listSessions(rootDir, profileId)
  if (sessions.length === 0) throw new Error("No sessions available for forensics")
  const latest = getSession(rootDir, sessions[0]!.id)
  if (!latest) throw new Error(`Session ${sessions[0]!.id} not found`)
  return latest
}

export function buildEventLine(event: Record<string, unknown>) {
  const type = typeof event.type === "string" ? event.type : "unknown"
  switch (type) {
    case "tool.start":
      return `${type}: ${(event.tool as string) ?? "unknown"} started`
    case "tool.finish":
      return `${type}: ${(event.tool as string) ?? "unknown"} ${event.ok === true ? "ok" : "failed"}${event.output !== undefined ? ` -> ${stringifyValue(event.output, 160)}` : ""}`
    case "agent.background.completed":
      return `${type}: ${(event.agentId as string) ?? "unknown"} ${(event.status as string) ?? "unknown"}${event.result ? ` -> ${stringifyValue(event.result, 160)}` : ""}${event.error ? ` error=${stringifyValue(event.error, 120)}` : ""}`
    case "message.received":
      return `${type}: ${(event.role as string) ?? "unknown"} -> ${truncateText(String(event.text ?? ""), 160)}`
    case "error":
      return `${type}: ${truncateText(String(event.error ?? ""), 160)}`
    default:
      return `${type}: ${stringifyValue(event, 180)}`
  }
}

export function uniqueLines(lines: string[]) {
  const seen = new Set<string>()
  const result: string[] = []
  for (const line of lines) {
    const normalized = compactWhitespace(line)
    if (!normalized || seen.has(normalized)) continue
    seen.add(normalized)
    result.push(normalized)
  }
  return result
}

export function optionalBoolean(input: Record<string, unknown>, key: string) {
  const value = input[key]
  return typeof value === "boolean" ? value : undefined
}

export function findStringOccurrences(content: string, needle: string) {
  const matches: Array<{ index: number; line: number }> = []
  let fromIndex = 0
  while (true) {
    const index = content.indexOf(needle, fromIndex)
    if (index === -1) break
    const line = content.slice(0, index).split("\n").length
    matches.push({ index, line })
    fromIndex = index + needle.length
  }
  return matches
}

export function zodErrorMessage(error: unknown) {
  if (error instanceof z.ZodError) {
    return error.issues.map(issue => `${issue.path.join(".") || "input"}: ${issue.message}`).join("; ")
  }
  return error instanceof Error ? error.message : String(error)
}

export function parseZod<T>(schema: ZodType<T>, value: unknown, label: string): T {
  try {
    return schema.parse(value)
  } catch (error) {
    throw new Error(`${label} failed validation: ${zodErrorMessage(error)}`)
  }
}

export function validateZod<T>(schema: ZodType<T>, value: unknown) {
  const result = schema.safeParse(value)
  return result.success ? null : zodErrorMessage(result.error)
}

export function normalizeConfigWingValue(wing: ConfigWingName, value: unknown) {
  if (wing === "CONF_CHANNELS") {
    parseZod(strictRecordZod, value, "CONF_CHANNELS")
    return normalizeChannelsConfigForWrite(value)
  }
  if (wing === "CONF_MODELS") {
    return parseZod(modelRegistryZod, coerceConfigRecord(value) ?? value, "CONF_MODELS")
  }
  if (wing === "CONF_SYSTEM") {
    return parseZod(systemConfigZod, coerceConfigRecord(value) ?? value, "CONF_SYSTEM")
  }
  if (wing === "CONF_WEBSEARCH") {
    return parseZod(webSearchConfigZod, coerceConfigRecord(value) ?? value, "CONF_WEBSEARCH")
  }
  if (wing === "CONF_MCP") {
    return parseZod(strictRecordZod, coerceConfigRecord(value) ?? value, "CONF_MCP")
  }
  if (wing === "CONF_POLICY") {
    return parseZod(policyConfigZod, coerceConfigRecord(value) ?? value, "CONF_POLICY")
  }
  return value
}

export function parseJsonStringValue(value: unknown) {
  if (typeof value !== "string") return value
  const trimmed = value.trim()
  if (!trimmed) return value
  try {
    return JSON.parse(trimmed)
  } catch {
    return value
  }
}

export function objectArrayField(value: unknown, key: string): Record<string, unknown>[] {
  if (!value || typeof value !== "object" || Array.isArray(value)) return []
  const candidate = (value as Record<string, unknown>)[key]
  if (!Array.isArray(candidate)) return []
  return candidate.filter((item): item is Record<string, unknown> =>
    Boolean(item) && typeof item === "object" && !Array.isArray(item),
  )
}

export function inferExtensionFromFormat(format: string) {
  if (format === "opus") return "ogg"
  return format
}

export function sanitizeFilenameSegment(value: string) {
  const normalized = value.trim().replace(/[^a-zA-Z0-9._-]+/g, "-").replace(/-+/g, "-")
  return normalized.replace(/^-+|-+$/g, "") || "speech"
}

export async function telegramApiCall(token: string, method: string, params: Record<string, unknown>) {
  const response = await fetch(`https://api.telegram.org/bot${token}/${method}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(params),
    signal: AbortSignal.timeout(15_000),
  })
  return await response.json() as { ok: boolean; result?: unknown; description?: string }
}

export const TELEGRAM_SENT_PHOTOS_KEY = "telegram_sent_photos"

export function getAlreadySentPhotos(rootDir: string): Set<string> {
  try {
    const stateFile = join(rootDir, "run", `${TELEGRAM_SENT_PHOTOS_KEY}.json`)
    if (existsSync(stateFile)) {
      const data = JSON.parse(readFileSync(stateFile, "utf8")) as string[]
      return new Set(data)
    }
  } catch {}
  return new Set()
}

export function markPhotoAsSent(rootDir: string, photoPath: string) {
  try {
    const stateFile = join(rootDir, "run", `${TELEGRAM_SENT_PHOTOS_KEY}.json`)
    const sent = getAlreadySentPhotos(rootDir)
    sent.add(photoPath)
    mkdirSync(dirname(stateFile), { recursive: true })
    writeFileSync(stateFile, JSON.stringify([...sent]), "utf8")
  } catch {}
}

export function isPhotoAlreadySent(rootDir: string, photoPath: string): boolean {
  return getAlreadySentPhotos(rootDir).has(photoPath)
}

export function isLocalPath(value: string) {
  return value.startsWith("/") || value.startsWith("./") || value.startsWith("../") || value.startsWith("~/")
}

export function resolveMonolitoPath(pathStr: string): string {
  const index = pathStr.indexOf(".monolito-v2")
  if (index !== -1) {
    const relativePart = pathStr.slice(index + ".monolito-v2".length)
    return join(MONOLITO_ROOT, relativePart)
  }
  return pathStr
}

export async function telegramApiCallWithFile(
  token: string,
  method: string,
  fileField: string,
  filePath: string,
  params: Record<string, unknown>,
) {
  let resolvedPath = filePath.startsWith("~/")
    ? filePath.replace("~/", `${process.env.HOME ?? ""}/`)
    : filePath

  resolvedPath = resolveMonolitoPath(resolvedPath)

  if (!existsSync(resolvedPath)) {
    return { ok: false, description: `File not found: ${resolvedPath}` }
  }

  const fileData = readFileSync(resolvedPath)
  const fileName = resolvedPath.split("/").at(-1) ?? "upload.bin"
  const formData = new FormData()
  formData.append(fileField, new Blob([fileData]), fileName)

  for (const [key, value] of Object.entries(params)) {
    if (key === fileField) continue
    if (value !== undefined && value !== null) {
      formData.append(key, typeof value === "object" ? JSON.stringify(value) : String(value))
    }
  }

  const response = await fetch(`https://api.telegram.org/bot${token}/${method}`, {
    method: "POST",
    body: formData,
    signal: AbortSignal.timeout(30_000),
  })
  return await response.json() as { ok: boolean; result?: unknown; description?: string }
}

export async function resolveTelegramDownload(
  token: string,
  fileId: string,
  rootDir: string,
  filename?: string,
) {
  const paths = ensureDirs(rootDir)
  const downloadsDir = join(paths.scratchpadDir, "telegram-downloads")
  if (existsSync(downloadsDir)) {
    const existingFiles = readdirSync(downloadsDir)
    const match = existingFiles.find(name => name.includes(fileId.slice(0, 8)))
    if (match) {
      const localPath = join(downloadsDir, match)
      try {
        const stats = statSync(localPath)
        return {
          ok: true,
          file_id: fileId,
          local_path: localPath,
          bytes: stats.size,
          cached: true,
        }
      } catch {
        // Fall back to downloading if stat fails.
      }
    }
  }

  const fileInfo = await telegramApiCall(token, "getFile", { file_id: fileId })
  if (!fileInfo.ok || !fileInfo.result || typeof fileInfo.result !== "object") {
    throw new Error(`Failed to get Telegram file info: ${fileInfo.description ?? "unknown error"}`)
  }

  const result = fileInfo.result as { file_path?: string }
  if (!result.file_path) {
    throw new Error("Telegram did not return file_path for this file_id.")
  }

  const response = await fetch(`https://api.telegram.org/file/bot${token}/${result.file_path}`, {
    signal: AbortSignal.timeout(30_000),
  })
  if (!response.ok) {
    throw new Error(`Failed to download Telegram file: HTTP ${response.status}`)
  }

  mkdirSync(downloadsDir, { recursive: true })
  const originalName = result.file_path.split("/").at(-1) ?? fileId
  const extension = originalName.includes(".") ? `.${originalName.split(".").at(-1)}` : ""
  const saveName = filename
    ? (filename.includes(".") ? filename : `${filename}${extension}`)
    : originalName
  const localPath = join(downloadsDir, saveName)
  const buffer = Buffer.from(await response.arrayBuffer())
  writeFileSync(localPath, buffer)

  return {
    ok: true,
    file_id: fileId,
    file_path: result.file_path,
    local_path: localPath,
    bytes: buffer.length,
  }
}

export async function runRg(args: string[], cwd: string) {
  try {
    return await execFileAsync("rg", args, {
      cwd,
      maxBuffer: MAX_EXEC_BUFFER,
      env: { ...process.env, LC_ALL: "C", LANG: "C" },
    })
  } catch (error) {
    const typed = error as NodeJS.ErrnoException & { code?: number; stdout?: string; stderr?: string }
    if (typed.code === 1) {
      return { stdout: typed.stdout ?? "", stderr: typed.stderr ?? "" }
    }
    if (typed.code === "ENOENT") {
      throw new Error("rg is required but not installed")
    }
    throw error
  }
}

export async function getMcpClient(context: ToolContext, serverName: string) {
  if (context.getMcpClient) return context.getMcpClient(serverName)
  const server = getDefaultMcpServers(context.rootDir)[serverName]
  if (!server) throw new Error(`Unknown MCP server: ${serverName}`)
  const client = createMcpClient(server)
  await client.initialize()
  return client
}

export async function fetchWithCurl(url: string) {
  const result = await execFileAsync("curl", ["-fsSL", "--max-time", "15", url], {
    maxBuffer: MAX_EXEC_BUFFER,
    env: process.env,
  })
  return {
    code: 200,
    codeText: "OK",
    bytes: Buffer.byteLength(result.stdout),
    content: result.stdout,
  }
}

/**
 * Helper to convert local time components in a specific IANA timezone to a UTC Date.
 * 
 * Works by:
 * 1. Treating the local time components as a UTC time first.
 * 2. Formatting this UTC candidate in the target timezone to find the local components of that instant.
 * 3. Computing the difference (offset) between the target local time and the candidate's local time.
 * 4. Applying this difference to the candidate to get the exact UTC Date.
 */
export function localTimeToUtc(
  year: number,
  month: number, // 1-12
  day: number,
  hour: number,
  minute: number,
  second: number,
  timezone: string
): Date {
  const utcCandidateMs = Date.UTC(year, month - 1, day, hour, minute, second)
  
  const formatter = new Intl.DateTimeFormat("en-US", {
    timeZone: timezone,
    year: "numeric",
    month: "numeric",
    day: "numeric",
    hour: "numeric",
    minute: "numeric",
    second: "numeric",
    hour12: false,
  })
  
  const parts = formatter.formatToParts(new Date(utcCandidateMs))
  const partVal = (type: string) => parseInt(parts.find(p => p.type === type)!.value, 10)
  
  const localYear = partVal("year")
  const localMonth = partVal("month")
  const localDay = partVal("day")
  const localHour = partVal("hour") % 24
  const localMinute = partVal("minute")
  const localSecond = partVal("second")
  
  const localCandidateMs = Date.UTC(localYear, localMonth - 1, localDay, localHour, localMinute, localSecond)
  const offsetMs = utcCandidateMs - localCandidateMs
  
  return new Date(utcCandidateMs + offsetMs)
}

/**
 * Parses an absolute time string (e.g. "15:30", "2026-05-18 10:00") in the context of the
 * user's timezone and returns a UTC Date.
 */
export function parseAbsoluteTimeToUtc(timeStr: string, timezone: string): Date {
  const trimmed = timeStr.trim()
  const now = new Date()

  // 1. Try Full Date-Time (e.g., "2026-05-17 15:30:00" or "2026-05-17T15:30")
  const fullDateTimeRegex = /^(\d{4})-(\d{1,2})-(\d{1,2})[ T](\d{1,2}):(\d{2})(?::(\d{2}))?$/
  const matchFull = trimmed.match(fullDateTimeRegex)
  if (matchFull) {
    const year = parseInt(matchFull[1]!, 10)
    const month = parseInt(matchFull[2]!, 10)
    const day = parseInt(matchFull[3]!, 10)
    const hour = parseInt(matchFull[4]!, 10)
    const minute = parseInt(matchFull[5]!, 10)
    const second = matchFull[6] ? parseInt(matchFull[6]!, 10) : 0
    return localTimeToUtc(year, month, day, hour, minute, second, timezone)
  }

  // 2. Try Time Only (e.g., "15:30" or "15:30:00")
  const timeOnlyRegex = /^(\d{1,2}):(\d{2})(?::(\d{2}))?$/
  const matchTime = trimmed.match(timeOnlyRegex)
  if (matchTime) {
    const hour = parseInt(matchTime[1]!, 10)
    const minute = parseInt(matchTime[2]!, 10)
    const second = matchTime[3] ? parseInt(matchTime[3]!, 10) : 0

    // Retrieve the current date components inside the target timezone
    const formatter = new Intl.DateTimeFormat("en-US", {
      timeZone: timezone,
      year: "numeric",
      month: "numeric",
      day: "numeric",
    })
    const parts = formatter.formatToParts(now)
    const partVal = (type: string) => parseInt(parts.find(p => p.type === type)!.value, 10)
    const currentYear = partVal("year")
    const currentMonth = partVal("month")
    const currentDay = partVal("day")

    let targetDate = localTimeToUtc(currentYear, currentMonth, currentDay, hour, minute, second, timezone)
    // If the target time today has already passed, schedule it for tomorrow
    if (targetDate.getTime() <= now.getTime()) {
      targetDate = localTimeToUtc(currentYear, currentMonth, currentDay + 1, hour, minute, second, timezone)
    }
    return targetDate
  }

  throw new Error(`Invalid absolute time format: "${timeStr}". Expected "HH:MM", "HH:MM:SS", "YYYY-MM-DD HH:MM" or "YYYY-MM-DD HH:MM:SS".`)
}

export const scheduleTaskInputZod = z.discriminatedUnion("action", [
  z.object({
    action: z.literal("list"),
  }).strict(),
  z.object({
    action: z.literal("remove"),
    job_index: z.number().int().min(1, "job_index must be >= 1"),
  }).strict(),
  z.object({
    action: z.literal("add"),
    message: z.string().min(1, "message is required and cannot be empty"),
    chat_id: z.number(),
    timezone: z.string().min(1, "timezone is required when adding a task"),
    delay_seconds: z.number().min(0, "delay_seconds must be >= 0").optional(),
    at: z.string().min(1).optional(),
    time: z.string().min(1).optional(),
    cron_expression: z.string().min(1).optional(),
  }).strict().superRefine((data, ctx) => {
    const providedTriggers = [
      data.delay_seconds !== undefined,
      data.at !== undefined,
      data.time !== undefined,
      data.cron_expression !== undefined,
    ].filter(Boolean).length

    if (providedTriggers === 0) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "Either delay_seconds, at/time, or cron_expression must be provided",
        path: ["delay_seconds"],
      })
    } else if (providedTriggers > 1) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "delay_seconds, at, time, and cron_expression are mutually exclusive",
        path: ["delay_seconds"],
      })
    }
  }),
])

// ----- Skills: configuration and security helpers ----------------------------

/**
 * Read the CONF_SKILLS config wing for skill lifecycle settings.
 * Returns sensible defaults if the wing is missing or malformed.
 */
export function readSkillGuardConfig(rootDir: string): boolean {
  try {
    const wing = readConfigWing(rootDir, "CONF_SKILLS") as {
      guard_agent_created?: boolean
    } | null
    return wing?.guard_agent_created === true
  } catch {
    return false
  }
}

/**
 * Lightweight threat-pattern scanner for agent-created skill guides.
 * Returns the first matched pattern (or null if clean).
 * This is defensive only — not a sandbox. The agent can still execute
 * anything via Bash; the scan just adds friction against self-inflicted
 * bad SOPs that would otherwise look innocuous.
 */
export const SKILL_THREAT_PATTERNS: { name: string; regex: RegExp }[] = [
  { name: "rm -rf root", regex: /\brm\s+(-\w*r\w*f\w*\s+)*\/\s*$/m },
  { name: "rm -rf home", regex: /\brm\s+-\w*r\w*f\w*\s+~(?:\s|$)/m },
  { name: "rm -rf ssh", regex: /\brm\s+-\w*r\w*f\w*\s+\.?\.?\/?\.ssh/m },
  { name: "curl pipe bash", regex: /curl[^|]*\|\s*(sudo\s+)?(ba)?sh/m },
  { name: "exfiltrate env", regex: /\b(cat|printenv|env)\b[^.\n]*\b(AWS_|GITHUB_|OPENAI_|ANTHROPIC_|API_KEY|SECRET|TOKEN)/m },
  { name: "chmod 777", regex: /\bchmod\s+777\b/ },
  { name: "dd overwrite disk", regex: /\bdd\s+if=[^\n]*\s+of=\/dev\/(sd|nvme|hd)/m },
]

export function scanSkillGuideForThreats(guide: string): { threat: boolean; pattern: string | null } {
  for (const { name, regex } of SKILL_THREAT_PATTERNS) {
    if (regex.test(guide)) {
      return { threat: true, pattern: name }
    }
  }
  return { threat: false, pattern: null }
}

/**
 * Debounce window for skill telemetry. If a skill was used less than this many
 * milliseconds ago, skip the increment. Prevents SQLite writes from a tight
 * loop of skill_view calls in the same turn.
 */
export const SKILL_TELEMETRY_DEBOUNCE_MS = 60_000

export function shouldRecordSkillUse(skill: { telemetry?: { last_used_at?: string; use_count?: number } }): boolean {
  // First use (use_count === 0) always counts. After that, debounce.
  if (!skill.telemetry || (skill.telemetry.use_count ?? 0) === 0) return true
  const last = skill.telemetry.last_used_at
  if (!last) return true
  const lastMs = Date.parse(last)
  if (Number.isNaN(lastMs)) return true
  return Date.now() - lastMs >= SKILL_TELEMETRY_DEBOUNCE_MS
}


export function isValidJson(value: string) {
  try {
    JSON.parse(value)
    return true
  } catch {
    return false
  }
}
