#!/usr/bin/env python3
"""
Extracts the helper section (lines 1-1080) of registry.ts to internal.ts,
adding `export` to every function, const, etc. Also generates the
import statements for each domain file.

This is a one-time refactor script.
"""

import re
from pathlib import Path

REGISTRY = Path("src/core/tools/registry.ts")
INTERNAL = Path("src/core/tools/internal.ts")
DOMAINS_DIR = Path("src/core/tools/domains")

# Lines 1-1080 are the helpers (per analysis). The const rawTools starts at 1081.
# We extract everything UP TO the line before "const rawTools".
HELPERS_END_LINE = 1080  # 0-based exclusive: read up to line 1080 (1-based 1080)

# All helpers we know about (functions, consts, etc.) that need to be exported.
# We add `export` to anything that doesn't already have it.
EXPORT_TARGETS = {
    "function", "const", "async function", "let",
}

def add_export_to_declarations(text: str) -> str:
    """Add `export` keyword to function/const declarations that don't have it."""
    out_lines = []
    for line in text.split("\n"):
        stripped = line.lstrip()
        # If line already starts with `export`, skip
        if stripped.startswith("export "):
            out_lines.append(line)
            continue
        # Match function declarations
        m = re.match(r'^(\s*)(async\s+function\s+\w+|function\s+\w+)', line)
        if m:
            indent = m.group(1)
            rest = line[len(indent):]
            out_lines.append(f"{indent}export {rest}")
            continue
        # Match const/let declarations (with or without type annotation)
        m = re.match(r'^(\s*)(const|let)\s+(\w+)', line)
        if m:
            indent = m.group(1)
            kind = m.group(2)
            name = m.group(3)
            # Skip if it's a destructured import (would have been `import`)
            rest = line[len(indent):]
            out_lines.append(f"{indent}export {rest}")
            continue
        out_lines.append(line)
    return "\n".join(out_lines)


def extract_helpers():
    text = REGISTRY.read_text()
    lines = text.split("\n")
    # Lines are 0-based. Line 1080 (0-based) is the line BEFORE `const rawTools: ...` at line 1081 (0-based 1080).
    # The line before "const rawTools:" is what we want.
    # Find exact line
    for i, line in enumerate(lines):
        if re.match(r'^const rawTools: ToolDefinition\[\] = \[$', line):
            helpers_end = i  # exclusive
            break
    else:
        raise SystemExit("Could not find rawTools array start")
    print(f"Helpers span lines 1 to {helpers_end} (0-based)")

    helpers_text = "\n".join(lines[:helpers_end])
    helpers_text = add_export_to_declarations(helpers_text)

    # Wrap the internal.ts in a clear header
    header = """// Shared internal helpers for the tool registry and domain files.
// This file is auto-generated by scripts/extract_helpers.py — do not edit
// manually except to add new exports. Domain files in ./domains/ import
// from here. registry.ts re-exports the public API.

"""
    INTERNAL.write_text(header + helpers_text)
    print(f"Wrote {INTERNAL} ({len(helpers_text.split(chr(10)))} lines)")

def find_used_identifiers_in_domain(domain_file: Path) -> set:
    """Find all identifiers used in the tool code (excluding local scope).

    Heuristic: strip string literals and template literals, then look for
    word identifiers. We rely on a known set of 'helpers' vs 'imports' to
    classify.
    """
    KNOWN_HELPERS = {
        # Functions
        "formatToolError", "withSafeToolFailure", "resolveWorkspacePath",
        "toWorkspaceRelative", "normalizePathInput", "buildTraceEnv",
        "requireString", "optionalString", "optionalNumber", "optionalBoolean",
        "compactWhitespace", "isVisionConnectionFailure", "truncateText",
        "stringifyValue", "decodeBasicHtmlEntities", "htmlToReadableText",
        "promptTerms", "selectRelevantText", "resolveForensicsIntent",
        "inferForensicsIntent", "pickForensicsSession", "buildEventLine",
        "uniqueLines", "findStringOccurrences", "zodErrorMessage", "parseZod",
        "validateZod", "normalizeConfigWingValue", "parseJsonStringValue",
        "objectArrayField", "inferExtensionFromFormat", "sanitizeFilenameSegment",
        "telegramApiCall", "telegramApiCallWithFile", "resolveTelegramDownload",
        "getAlreadySentPhotos", "markPhotoAsSent", "isPhotoAlreadySent",
        "isLocalPath", "resolveMonolitoPath", "runRg", "getMcpClient",
        "fetchWithCurl", "localTimeToUtc", "parseAbsoluteTimeToUtc",
        "readSkillGuardConfig", "scanSkillGuideForThreats", "shouldRecordSkillUse",
        "normalizeIntentText", "isImageIntentText", "isTelegramPhotoDeliveryRequest",
        "requiresImageVerificationText", "latestActionableUserText",
        "buildTelegramPhotoWorkerTask",
        # Constants and Zod schemas
        "emptyInputSchema", "optionalPathInputSchema",
        "configWingZod", "strictRecordZod", "modelProfileZod", "modelRegistryZod",
        "systemConfigZod", "webSearchConfigZod", "hookMatcherZod", "hookDefinitionZod",
        "policyConfigZod", "bootWriteInputZod", "bootCreateWingInputZod",
        "manageConfigInputZod", "scheduleTaskInputZod",
        "DEFAULT_GREP_LIMIT", "DEFAULT_BASH_TIMEOUT_MS", "MAX_EXEC_BUFFER",
        "TELEGRAM_AUDIO_FORMATS", "TELEGRAM_VOICE_FORMATS", "TTS_RESPONSE_FORMATS",
        "TELEGRAM_SENT_PHOTOS_KEY", "SKILL_TELEMETRY_DEBOUNCE_MS",
        "SKILL_THREAT_PATTERNS",
        # Type-only re-exports
        "ToolDefinition", "ToolContext", "ToolInputSchema",
        # Common external imports used by tools
        "randomUUID", "mkdirSync", "readFileSync", "writeFileSync", "existsSync",
        "statSync", "readdirSync", "openSync", "unlinkSync", "createWriteStream",
        "join", "dirname", "relative", "resolve", "sep", "pathToFileURL",
        "execFile", "spawn", "promisify",
        "MONOLITO_ROOT", "getPaths", "ensureDirs",
        # MCP
        "McpClient", "createMcpClient", "getDefaultMcpServers",
        "getSharedLspClient",
        # Channels
        "normalizeChannelsConfigForWrite", "readChannelsConfig", "writeChannelsConfig",
        # Session store
        "appendActionLog", "addGraphTriple", "fileMemory", "invalidateGraphTriple",
        "queryGraphEntity", "recallMemory", "listWings", "listRooms", "listProfiles",
        "createProfile", "readBootWing", "writeBootWing", "listBootWings",
        "createBootWing", "bootWingExists", "ensureBootWings", "readConfigWing",
        "writeConfigWing", "getSession", "listSessions", "tailEvents",
        "writeSessionSource", "writeSessionTask", "listSessionTasks",
        "deleteSessionTask", "getDb", "upsertSemanticTool", "querySemanticTools",
        "upsertRalphRule", "listDynamicSkills", "saveDynamicSkill",
        "getDynamicSkill", "deleteDynamicSkill", "incrementSkillTelemetry",
        "archiveDynamicSkill", "restoreArchivedSkill",
        # Embeddings
        "isEmbeddingsUnavailableError",
        # Orchestrator
        "AgentOrchestrator",
        # Redact
        "redactSensitiveValue",
        # Logger
        "Logger",
        # Config
        "CONFIG_WING_ORDER", "ConfigWingName", "coerceConfigRecord",
        "loadAndApplyModelSettings", "readModelSettings",
        "getActiveProfile", "activateProfile",
        # TTS/STT
        "deployManagedTtsContainer", "getManagedTtsBaseUrl", "getManagedTtsStatus",
        "listManagedTtsContainers", "normalizeTtsConfig", "removeManagedTtsContainer",
        "stopManagedTtsContainer",
        "deployManagedSttContainer", "getManagedSttBaseUrl", "getManagedSttStatus",
        "listManagedSttContainers", "normalizeSttConfig", "removeManagedSttContainer",
        "stopManagedSttContainer", "transcribeManagedAudioFile",
        # Websearch (SearXNG backend removed — only readWebSearchConfig remains)
        "readWebSearchConfig",
        # Boot
        "isBootWingName", "BOOT_WING_ORDER",
        # Master dashboard
        "renderMasterDashboard",
    }
    text = domain_file.read_text()
    # Strip string literals (simple regex)
    text = re.sub(r'"(?:[^"\\]|\\.)*"', '""', text)
    text = re.sub(r"'(?:[^'\\]|\\.)*'", "''", text)
    text = re.sub(r"`(?:[^`\\]|\\.)*`", "``", text)
    # Find identifiers
    found = set(re.findall(r'\b([A-Za-z_$][A-Za-z0-9_$]*)\b', text))
    used = found & KNOWN_HELPERS
    return used

def update_domain_imports():
    """For each domain file, add the appropriate imports from internal.ts."""
    for domain_file in sorted(DOMAINS_DIR.glob("*.ts")):
        text = domain_file.read_text()
        # Find existing import lines
        lines = text.split("\n")
        # Replace the simple import with the new one
        new_lines = []
        skip_old_import = False
        for line in lines:
            if line.strip() == 'import type { ToolDefinition } from "../registry.ts"':
                skip_old_import = True
                continue
            new_lines.append(line)
        # Find used identifiers
        used = find_used_identifiers_in_domain(domain_file)
        # Build the new import statements
        if not used:
            print(f"  {domain_file.name}: no helpers used?")
            domain_file.write_text("\n".join(new_lines))
            continue
        # Split into helpers from internal.ts vs imports from registry.ts
        # For now, all of them are expected to be in internal.ts.
        # Sort and format
        helpers = sorted(used - {"ToolDefinition"})
        # Check if ToolDefinition is also in there
        imports_block = ['import type { ToolDefinition } from "../registry.ts"']
        if helpers:
            imports_block.append('import {')
            for h in helpers:
                imports_block.append(f"  {h},")
            imports_block.append("} from \"./internal.ts\"")
        # Find the spot to insert (after the first comment lines)
        # Original file starts with:
        #   // Auto-generated comment
        #   // Domain: ...
        #   (blank)
        #   import type { ToolDefinition } from "../registry.ts"
        #   (blank)
        #   export const ...
        # We want to replace the import line with our new imports.
        result = []
        for line in new_lines:
            if line.startswith("export const "):
                # Insert our imports before this line
                result.extend(imports_block)
                result.append("")
                result.append(line)
            else:
                result.append(line)
        # Make sure imports are at the top (after the first comments)
        # Re-do: filter out the now-redundant imports
        final = []
        in_imports = False
        imports_done = False
        for line in result:
            if not imports_done and line.startswith("import "):
                # Skip existing import lines (we'll add them back together)
                in_imports = True
                continue
            if in_imports and line.strip() == "":
                in_imports = False
                # Add the imports here
                final.extend(imports_block)
                final.append("")
                imports_done = True
                continue
            if in_imports:
                continue  # skip
            final.append(line)
        domain_file.write_text("\n".join(final))
        print(f"  {domain_file.name}: added {len(helpers)} helper imports")

if __name__ == "__main__":
    extract_helpers()
    print("\n=== Updating domain imports ===")
    update_domain_imports()
