// Auto-generated by scripts/split_registry.py — do not edit manually.
// Domain: admin (8 tools)

import {
  join,
} from "node:path"

import {
  existsSync,
} from "node:fs"

import {
  userInfo,
} from "node:os"

import {
  emptyInputSchema,
  execFileAsync,
  formatToolError,
  optionalNumber,
  optionalString,
  requireString,
} from "../internal.ts"

import {
  querySemanticTools,
} from "../../session/store.ts"

import type { ToolDefinition } from "../registry.ts"

export const adminTools: ToolDefinition[] = [
{
  name: "GetSystemStatus",
  aliases: ["QueryRuntime", "system_status", "SystemStatus", "QuerySessionStatus", "QueryCost", "QuerySessionStats"],
  permissionTier: "read",
  description: "Query Monolito daemon health diagnostics, token consumption cost metrics, or session status history. Optional info_type='all'|'health'|'cost'|'session'. Defaults to 'all'.",
  inputSchema: {
    type: "object",
    properties: {
      info_type: { 
        type: "string", 
        enum: ["all", "health", "cost", "session"],
        description: "The type of information to retrieve."
      },
      metric: { type: "string", enum: ["status", "cost", "stats"], description: "Legacy parameter (same as info_type)." },
      sessionId: { type: "string", description: "Optional session ID (defaults to current session)." },
    },
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    const invoked = context.invokedAs ?? "GetSystemStatus"
    const sessionId = optionalString(input, "sessionId") ?? context.sessionId

    // Handle legacy specific actions by invoked name
    if (invoked === "QueryCost") {
      if (!context.queryCost) return formatToolError("Cost query is not available in this context")
      return context.queryCost()
    }
    if (invoked === "QuerySessionStats") {
      if (!sessionId) return formatToolError("sessionId is required")
      if (!context.queryStats) return formatToolError("Session stats query is not available in this context")
      return context.queryStats(sessionId)
    }
    if (invoked === "QuerySessionStatus") {
      if (!sessionId) return formatToolError("sessionId is required")
      if (!context.querySessionStatus) return formatToolError("Session status query is not available in this context")
      return context.querySessionStatus(sessionId)
    }
    if (invoked === "system_status" || invoked === "SystemStatus") {
      if (!context.runtime?.getSystemStatus) {
        return formatToolError("system_status is unavailable outside the Monolito runtime.")
      }
      return JSON.stringify(await context.runtime.getSystemStatus())
    }

    // Normal routing
    const infoType = optionalString(input, "info_type") ?? "all"
    const metric = optionalString(input, "metric")

    // Map legacy metric parameter to infoType if specified
    let targetType = infoType
    if (metric === "cost") targetType = "cost"
    else if (metric === "stats" || metric === "status") targetType = "session"

    // If QueryRuntime invoked without metric, default to session status or cost depending on legacy behavior
    if (invoked === "QueryRuntime" && !metric && infoType === "all") {
      targetType = "session"
    }

    if (targetType === "health") {
      if (!context.runtime?.getSystemStatus) {
        return formatToolError("System health is unavailable outside the Monolito runtime.")
      }
      return JSON.stringify(await context.runtime.getSystemStatus())
    }

    if (targetType === "cost") {
      if (!context.queryCost) return formatToolError("Cost query is not available in this context")
      return context.queryCost()
    }

    if (targetType === "session") {
      if (!sessionId) return formatToolError("sessionId is required")
      // Under legacy QueryRuntime status / stats:
      if (metric === "stats" || invoked === "QuerySessionStats") {
        if (!context.queryStats) return formatToolError("Session stats query is not available in this context")
        return context.queryStats(sessionId)
      }
      if (!context.querySessionStatus) return formatToolError("Session status query is not available in this context")
      return context.querySessionStatus(sessionId)
    }

    // Default: 'all'
    const result: Record<string, any> = {}
    if (context.runtime?.getSystemStatus) {
      try {
        result.health = await context.runtime.getSystemStatus()
      } catch (err: any) {
        result.health_error = err.message || err
      }
    }
    if (context.queryCost) {
      try {
        result.cost = await context.queryCost()
      } catch (err: any) {
        result.cost_error = err.message || err
      }
    }
    if (sessionId) {
      if (context.querySessionStatus) {
        try {
          result.session = await context.querySessionStatus(sessionId)
        } catch (err: any) {
          result.session_error = err.message || err
        }
      }
      if (context.queryStats) {
        try {
          result.stats = await context.queryStats(sessionId)
        } catch (err: any) {
          result.stats_error = err.message || err
        }
      }
    }
    return JSON.stringify(result)
  },
},

{
  name: "ExecuteSystemMaintenance",
  aliases: ["CompactSession", "system_reboot", "SystemReboot"],
  permissionTier: "edit",
  description: "Execute system maintenance tasks like rebooting the daemon or compacting historical context to prevent token overflows.",
  inputSchema: {
    type: "object",
    properties: {
      maintenance_task: {
        type: "string",
        enum: ["reboot_daemon", "compact_context"],
        description: "The maintenance task to execute."
      },
      reason: { type: "string", description: "Reason for rebooting (required for reboot_daemon)." },
      sessionId: { type: "string", description: "Optional session ID for context compaction (defaults to current)." },
      maxMessages: { type: "number", description: "Optional max messages to keep un-compacted." },
    },
    additionalProperties: false,
  },
  concurrencySafe: false,
  validate: input => {
    const invoked = input.maintenance_task
    const task = invoked ? String(invoked) : undefined

    if (task === "reboot_daemon") {
      const reason = input.reason
      if (typeof reason !== "string" || reason.trim().length === 0) {
        return "reason must be a non-empty string for reboot_daemon"
      }
    }
    if (task === "compact_context") {
      const maxMessages = input.maxMessages
      if (maxMessages !== undefined && (typeof maxMessages !== "number" || !Number.isInteger(maxMessages) || maxMessages < 1)) {
        return "maxMessages must be a positive integer"
      }
    }
    return null
  },
  async run(input, context) {
    const invoked = context.invokedAs ?? "ExecuteSystemMaintenance"
    const task = optionalString(input, "maintenance_task")

    if (invoked === "system_reboot" || invoked === "SystemReboot" || task === "reboot_daemon") {
      if (!context.runtime?.gracefulRestart) {
        return formatToolError("system_reboot is unavailable outside the Monolito runtime.")
      }
      const reason = optionalString(input, "reason")?.trim() || "Manual maintenance reboot request"
      context.runtime.gracefulRestart(reason)
      return `Reinicio iniciado. El sistema volverá a estar online en unos segundos por el motivo: ${reason}`
    }

    // Default to compaction for CompactSession or explicit compact_context
    if (invoked === "CompactSession" || task === "compact_context" || (!task && invoked === "ExecuteSystemMaintenance")) {
      const sessionId = optionalString(input, "sessionId") ?? context.sessionId
      const maxMessages = optionalNumber(input, "maxMessages")
      if (!sessionId) return formatToolError("sessionId is required")
      if (!context.compactSession) return formatToolError("Session compaction is not available in this context")
      return context.compactSession(sessionId, maxMessages)
    }

    return formatToolError(`Unknown maintenance task or invoked alias: ${invoked}`)
  },
},

{
  name: "search_tools",
  permissionTier: "read",
  description: "Busca herramientas disponibles en el registro que coincidan con la descripción o necesidad indicada. Úsala para descubrir nuevas herramientas dinámicamente si no encontrás una específica en tu contexto actual.",
  inputSchema: {
    type: "object",
    properties: {
      query: {
        type: "string",
        description: "La descripción de la necesidad o funcionalidad que buscás (ej: 'enviar archivos a Telegram', 'buscar en la web')."
      }
    },
    required: ["query"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    try {
      const query = typeof input.query === "string" ? input.query : ""
      const results = await querySemanticTools(context.rootDir, query, 10)
      if (results.length === 0) {
        return "No se encontraron herramientas que coincidan con la búsqueda."
      }
      const { listTools } = await import("../registry.ts")
      const matchedTools = listTools().filter(t => results.includes(t.name))
      // Sort: native (direct invocation) tools first, MCP tools last.
      // This nudges the model to call VoiceClone/GenerateSpeech/TranscribeAudio
      // directly instead of wrapping them in McpInvokeTool, which only works
      // for tools exposed by an actual MCP server (these are not).
      const sortedTools = [...matchedTools].sort((a, b) => {
        const aMcp = a.isMcp === true ? 1 : 0
        const bMcp = b.isMcp === true ? 1 : 0
        return aMcp - bMcp
      })
      return `Herramientas encontradas (native tools listed first — invoke them by name directly, do NOT wrap in McpInvokeTool):\n${sortedTools.map(t => {
        const kind = t.isMcp === true ? "mcp" : "native"
        const invocation = t.isMcp === true ? "McpInvokeTool(server, tool)" : `direct call: ${t.name}(...)`
        return `- [${kind}] ${t.name} (${invocation}): ${t.description}`
      }).join("\n")}`
    } catch (err) {
      return `Error buscando herramientas: ${err}`
    }
  }
},

{
  name: "manage_sudo_mode",
  permissionTier: "edit",
  description: "Administra el modo sudo dinámico temporal sin contraseña. Permite activar (requiere entorno gráfico y CLI local para mostrar el diálogo de autenticación nativo pkexec), desactivar (elimina la regla de sudoers) o consultar el estado actual. Al activar, podés opcionalmente restringir la regla a comandos específicos.",
  inputSchema: {
    type: "object",
    properties: {
      action: { type: "string", enum: ["activate", "deactivate", "status"], description: "Acción a realizar." },
      commands: { 
        type: "array", 
        items: { type: "string" }, 
        description: "Lista de comandos específicos permitidos sin contraseña (ej: ['/usr/bin/systemctl', '/usr/bin/apt-get']). Si se omite o está vacío, se permite ALL (todos los comandos)." 
      }
    },
    required: ["action"],
    additionalProperties: false,
  },
  validate: input => {
    if (input.action !== "activate" && input.action !== "deactivate" && input.action !== "status") {
      return "invalid or missing action"
    }
    if (input.action === "activate" && input.commands !== undefined) {
      if (!Array.isArray(input.commands)) return "commands must be an array of strings"
      for (const cmd of input.commands) {
        if (typeof cmd !== "string" || cmd.trim().length === 0) return "each command must be a non-empty string"
      }
    }
    return null
  },
  async run(input, context) {
    const action = input.action as "activate" | "deactivate" | "status"
    const commands = input.commands as string[] | undefined

    const sudoersDir = "/etc/sudoers.d"
    const sudoersFile = `${sudoersDir}/monolito-temp`

    if (action === "status") {
      const active = _testExistsSync(sudoersFile)
      if (!active) {
        return JSON.stringify({ active: false, message: "Modo sudo dinámico desactivado." })
      }
      try {
        const { stdout } = await _testExecFile("sudo", ["-n", "cat", sudoersFile], { timeout: 5000 })
        const content = stdout.trim()
        const match = content.match(/NOPASSWD:\s*(.+)$/)
        const allowedCommands = match ? match[1]!.trim().split(/,\s*/) : []
        return JSON.stringify({
          active: true,
          commands: allowedCommands,
          content,
          message: `Modo sudo dinámico activo. Comandos permitidos: ${allowedCommands.join(", ")}`
        })
      } catch (err: any) {
        return JSON.stringify({
          active: true,
          unreadable: true,
          message: "Modo sudo dinámico activo, pero la regla no se puede leer (requiere contraseña o es inválida)."
        })
      }
    }

    if (action === "deactivate") {
      if (!_testExistsSync(sudoersFile)) {
        return "El modo sudo dinámico ya estaba desactivado."
      }
      try {
        await _testExecFile("sudo", ["-n", "rm", "-f", sudoersFile], { timeout: 5000 })
        return "Modo sudo dinámico desactivado con éxito."
      } catch (err) {
        try {
          await _testExecFile("pkexec", ["rm", "-f", sudoersFile], { timeout: 15000 })
          return "Modo sudo dinámico desactivado con éxito (vía pkexec)."
        } catch (pkErr: any) {
          throw new Error(`No se pudo desactivar el modo sudo: ${pkErr.stderr || pkErr.message}`)
        }
      }
    }

    if (action === "activate") {
      const username = _testUserInfo().username
      if (!/^[a-zA-Z0-9_-]+$/.test(username)) {
        throw new Error(`Nombre de usuario inválido: ${username}`)
      }

      let ruleLine = ""
      if (commands && commands.length > 0) {
        for (const cmd of commands) {
          if (!cmd.startsWith("/")) {
            throw new Error(`El comando debe ser una ruta absoluta: ${cmd}`)
          }
          if (cmd.includes(",") || cmd.includes("\n") || cmd.includes("'") || cmd.includes('"')) {
            throw new Error(`Caracteres inválidos en el comando: ${cmd}`)
          }
        }
        ruleLine = `${username} ALL=(ALL) NOPASSWD: ${commands.join(", ")}`
      } else {
        ruleLine = `${username} ALL=(ALL) NOPASSWD: ALL`
      }

      const bashCmd = `echo '${ruleLine}' > ${sudoersFile} && chmod 0440 ${sudoersFile} && chown root:root ${sudoersFile} && (visudo -c -f ${sudoersFile} || (rm -f ${sudoersFile} && exit 1))`
      try {
        await _testExecFile("pkexec", ["bash", "-c", bashCmd], { timeout: 30000 })
        const allowedMsg = commands && commands.length > 0 ? commands.join(", ") : "ALL"
        return `Modo sudo dinámico activado con éxito. Permisos concedidos para: ${allowedMsg}`
      } catch (err: any) {
        throw new Error(`Error al activar el modo sudo (¿se canceló el diálogo o falló visudo?): ${err.stderr || err.message}`)
      }
    }

    throw new Error(`Acción desconocida: ${action}`)
  }
},

]

// Test hooks for module stubbing
export let _testExecFile = execFileAsync
export function _setTestExecFile(fn: typeof execFileAsync) {
  _testExecFile = fn
}

export let _testExistsSync = existsSync
export function _setTestExistsSync(fn: typeof existsSync) {
  _testExistsSync = fn
}

export let _testUserInfo: () => { username: string } = _defaultUserInfo
function _defaultUserInfo(): { username: string } {
  return userInfo()
}
export function _setTestUserInfo(fn: () => { username: string }) {
  _testUserInfo = fn
}
