// Auto-generated by scripts/split_registry.py — do not edit manually.
// Domain: admin (8 tools)

import {
  join,
} from "node:path"

import {
  existsSync,
} from "node:fs"

import {
  userInfo,
} from "node:os"

import {
  emptyInputSchema,
  execFileAsync,
  formatToolError,
  optionalNumber,
  optionalString,
  requireString,
} from "../internal.ts"

import {
  querySemanticTools,
} from "../../session/store.ts"

import type { ToolDefinition } from "../registry.ts"

export const adminTools: ToolDefinition[] = [
{
  name: "QuerySessionStatus",
  permissionTier: "read",
  description: "Return metadata for the current Monolito session, model configuration, and available tool count.",
  inputSchema: {
    type: "object",
    properties: {
      sessionId: { type: "string", description: "Optional session ID. Defaults to the current session." },
    },
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    const sessionId = optionalString(input, "sessionId") ?? context.sessionId
    if (!sessionId) return formatToolError("sessionId is required")
    if (!context.querySessionStatus) return formatToolError("Session status query is not available in this context")
    return context.querySessionStatus(sessionId)
  },
},

{
  name: "QueryCost",
  permissionTier: "read",
  description: "Return the current Monolito session token and cost summary.",
  inputSchema: emptyInputSchema,
  concurrencySafe: true,
  async run(_input, context) {
    if (!context.queryCost) return formatToolError("Cost query is not available in this context")
    return context.queryCost()
  },
},

{
  name: "QuerySessionStats",
  permissionTier: "read",
  description: "Return usage statistics for a Monolito session.",
  inputSchema: {
    type: "object",
    properties: {
      sessionId: { type: "string", description: "Optional session ID. Defaults to the current session." },
    },
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    const sessionId = optionalString(input, "sessionId") ?? context.sessionId
    if (!sessionId) return formatToolError("sessionId is required")
    if (!context.queryStats) return formatToolError("Session stats query is not available in this context")
    return context.queryStats(sessionId)
  },
},

{
  name: "CompactSession",
  permissionTier: "edit",
  description: "Compact older messages in the current Monolito session.",
  inputSchema: {
    type: "object",
    properties: {
      sessionId: { type: "string", description: "Optional session ID. Defaults to the current session." },
      maxMessages: { type: "number", description: "Optional number of recent messages to keep un-compacted." },
    },
    additionalProperties: false,
  },
  validate: input => {
    const maxMessages = input.maxMessages
    if (maxMessages !== undefined && (typeof maxMessages !== "number" || !Number.isInteger(maxMessages) || maxMessages < 1)) {
      return "maxMessages must be a positive integer"
    }
    return null
  },
  async run(input, context) {
    const sessionId = optionalString(input, "sessionId") ?? context.sessionId
    const maxMessages = optionalNumber(input, "maxMessages")
    if (!sessionId) return formatToolError("sessionId is required")
    if (!context.compactSession) return formatToolError("Session compaction is not available in this context")
    return context.compactSession(sessionId, maxMessages)
  },
},

{
  name: "system_status",
  aliases: ["SystemStatus"],
  permissionTier: "read",
  description: "Return a concurrent JSON audit of Monolito system health, including JIT-managed services, routing, file-backed sessions, workspace state, and daemon memory agent consolidation timing (lastExecutedAt, lastSkippedAt, isRunning). Use this tool when asked about the current state or recent activity of any daemon component.",
  inputSchema: emptyInputSchema,
  concurrencySafe: true,
  async run(_input, context) {
    if (!context.runtime?.getSystemStatus) {
      return formatToolError("system_status is unavailable outside the Monolito runtime.")
    }
    return JSON.stringify(await context.runtime.getSystemStatus())
  },
},

{
  name: "system_reboot",
  aliases: ["SystemReboot"],
  permissionTier: "edit",
  description: "Reinicia completamente el daemon de Monolito. ÚSALA ÚNICAMENTE después de haber modificado el código fuente y haber verificado que compila (npm run build), para que el sistema cargue tu nueva lógica en memoria.",
  inputSchema: {
    type: "object",
    properties: {
      reason: { type: "string", description: "Motivo del reinicio" },
    },
    required: ["reason"],
    additionalProperties: false,
  },
  concurrencySafe: false,
  validate: input => typeof input.reason === "string" && input.reason.trim().length > 0 ? null : "reason must be a non-empty string",
  async run(input, context) {
    if (!context.runtime?.gracefulRestart) {
      return formatToolError("system_reboot is unavailable outside the Monolito runtime.")
    }
    const reason = requireString(input, "reason").trim()
    context.runtime.gracefulRestart(reason)
    return `Reinicio iniciado. El sistema volverá a estar online en unos segundos por el motivo: ${reason}`
  },
},

{
  name: "show_master_dashboard",
  aliases: ["master_config", "config_hub"],
  permissionTier: "read",
  description:
    "Opens the Master Configuration Hub — an interactive menu for managing all system settings: models, channels, web search, audio/voice, and system configuration. ALWAYS use this tool (instead of reading config files manually) when the user wants to view or change settings, configure the system, or asks about current configuration. The tool returns a visual interactive menu to the CLI.",
  inputSchema: emptyInputSchema,
  concurrencySafe: true,
  async run() {
    const { buildMasterDashboard } = await import("../../menu/masterDashboard.ts")
    return buildMasterDashboard()
  },
},

{
  name: "search_tools",
  permissionTier: "read",
  description: "Busca herramientas disponibles en el registro que coincidan con la descripción o necesidad indicada. Úsala para descubrir nuevas herramientas dinámicamente si no encontrás una específica en tu contexto actual.",
  inputSchema: {
    type: "object",
    properties: {
      query: {
        type: "string",
        description: "La descripción de la necesidad o funcionalidad que buscás (ej: 'enviar archivos a Telegram', 'buscar en la web')."
      }
    },
    required: ["query"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    try {
      const query = typeof input.query === "string" ? input.query : ""
      const results = await querySemanticTools(context.rootDir, query, 10)
      if (results.length === 0) {
        return "No se encontraron herramientas que coincidan con la búsqueda."
      }
      const { listTools } = await import("../registry.ts")
      const matchedTools = listTools().filter(t => results.includes(t.name))
      // Sort: native (direct invocation) tools first, MCP tools last.
      // This nudges the model to call VoiceClone/GenerateSpeech/TranscribeAudio
      // directly instead of wrapping them in McpInvokeTool, which only works
      // for tools exposed by an actual MCP server (these are not).
      const sortedTools = [...matchedTools].sort((a, b) => {
        const aMcp = a.isMcp === true ? 1 : 0
        const bMcp = b.isMcp === true ? 1 : 0
        return aMcp - bMcp
      })
      return `Herramientas encontradas (native tools listed first — invoke them by name directly, do NOT wrap in McpInvokeTool):\n${sortedTools.map(t => {
        const kind = t.isMcp === true ? "mcp" : "native"
        const invocation = t.isMcp === true ? "McpInvokeTool(server, tool)" : `direct call: ${t.name}(...)`
        return `- [${kind}] ${t.name} (${invocation}): ${t.description}`
      }).join("\n")}`
    } catch (err) {
      return `Error buscando herramientas: ${err}`
    }
  }
},

{
  name: "manage_sudo_mode",
  permissionTier: "edit",
  description: "Administra el modo sudo dinámico temporal sin contraseña. Permite activar (requiere entorno gráfico y CLI local para mostrar el diálogo de autenticación nativo pkexec), desactivar (elimina la regla de sudoers) o consultar el estado actual. Al activar, podés opcionalmente restringir la regla a comandos específicos.",
  inputSchema: {
    type: "object",
    properties: {
      action: { type: "string", enum: ["activate", "deactivate", "status"], description: "Acción a realizar." },
      commands: { 
        type: "array", 
        items: { type: "string" }, 
        description: "Lista de comandos específicos permitidos sin contraseña (ej: ['/usr/bin/systemctl', '/usr/bin/apt-get']). Si se omite o está vacío, se permite ALL (todos los comandos)." 
      }
    },
    required: ["action"],
    additionalProperties: false,
  },
  validate: input => {
    if (input.action !== "activate" && input.action !== "deactivate" && input.action !== "status") {
      return "invalid or missing action"
    }
    if (input.action === "activate" && input.commands !== undefined) {
      if (!Array.isArray(input.commands)) return "commands must be an array of strings"
      for (const cmd of input.commands) {
        if (typeof cmd !== "string" || cmd.trim().length === 0) return "each command must be a non-empty string"
      }
    }
    return null
  },
  async run(input, context) {
    const action = input.action as "activate" | "deactivate" | "status"
    const commands = input.commands as string[] | undefined

    const sudoersDir = "/etc/sudoers.d"
    const sudoersFile = `${sudoersDir}/monolito-temp`

    if (action === "status") {
      const active = _testExistsSync(sudoersFile)
      if (!active) {
        return JSON.stringify({ active: false, message: "Modo sudo dinámico desactivado." })
      }
      try {
        const { stdout } = await _testExecFile("sudo", ["-n", "cat", sudoersFile], { timeout: 5000 })
        const content = stdout.trim()
        const match = content.match(/NOPASSWD:\s*(.+)$/)
        const allowedCommands = match ? match[1]!.trim().split(/,\s*/) : []
        return JSON.stringify({
          active: true,
          commands: allowedCommands,
          content,
          message: `Modo sudo dinámico activo. Comandos permitidos: ${allowedCommands.join(", ")}`
        })
      } catch (err: any) {
        return JSON.stringify({
          active: true,
          unreadable: true,
          message: "Modo sudo dinámico activo, pero la regla no se puede leer (requiere contraseña o es inválida)."
        })
      }
    }

    if (action === "deactivate") {
      if (!_testExistsSync(sudoersFile)) {
        return "El modo sudo dinámico ya estaba desactivado."
      }
      try {
        await _testExecFile("sudo", ["-n", "rm", "-f", sudoersFile], { timeout: 5000 })
        return "Modo sudo dinámico desactivado con éxito."
      } catch (err) {
        try {
          await _testExecFile("pkexec", ["rm", "-f", sudoersFile], { timeout: 15000 })
          return "Modo sudo dinámico desactivado con éxito (vía pkexec)."
        } catch (pkErr: any) {
          throw new Error(`No se pudo desactivar el modo sudo: ${pkErr.stderr || pkErr.message}`)
        }
      }
    }

    if (action === "activate") {
      const username = _testUserInfo().username
      if (!/^[a-zA-Z0-9_-]+$/.test(username)) {
        throw new Error(`Nombre de usuario inválido: ${username}`)
      }

      let ruleLine = ""
      if (commands && commands.length > 0) {
        for (const cmd of commands) {
          if (!cmd.startsWith("/")) {
            throw new Error(`El comando debe ser una ruta absoluta: ${cmd}`)
          }
          if (cmd.includes(",") || cmd.includes("\n") || cmd.includes("'") || cmd.includes('"')) {
            throw new Error(`Caracteres inválidos en el comando: ${cmd}`)
          }
        }
        ruleLine = `${username} ALL=(ALL) NOPASSWD: ${commands.join(", ")}`
      } else {
        ruleLine = `${username} ALL=(ALL) NOPASSWD: ALL`
      }

      const bashCmd = `echo '${ruleLine}' > ${sudoersFile} && chmod 0440 ${sudoersFile} && chown root:root ${sudoersFile} && (visudo -c -f ${sudoersFile} || (rm -f ${sudoersFile} && exit 1))`
      try {
        await _testExecFile("pkexec", ["bash", "-c", bashCmd], { timeout: 30000 })
        const allowedMsg = commands && commands.length > 0 ? commands.join(", ") : "ALL"
        return `Modo sudo dinámico activado con éxito. Permisos concedidos para: ${allowedMsg}`
      } catch (err: any) {
        throw new Error(`Error al activar el modo sudo (¿se canceló el diálogo o falló visudo?): ${err.stderr || err.message}`)
      }
    }

    throw new Error(`Acción desconocida: ${action}`)
  }
},

]

// Test hooks for module stubbing
export let _testExecFile = execFileAsync
export function _setTestExecFile(fn: typeof execFileAsync) {
  _testExecFile = fn
}

export let _testExistsSync = existsSync
export function _setTestExistsSync(fn: typeof existsSync) {
  _testExistsSync = fn
}

export let _testUserInfo: () => { username: string } = _defaultUserInfo
function _defaultUserInfo(): { username: string } {
  return userInfo()
}
export function _setTestUserInfo(fn: () => { username: string }) {
  _testUserInfo = fn
}
