// Auto-generated by scripts/split_registry.py — do not edit manually.
// Domain: config (1 tools)

import {
  formatToolError,
  manageConfigInputZod,
  normalizeConfigWingValue,
  parseJsonStringValue,
  parseZod,
  validateZod,
} from "../internal.ts"

import {
  loadAndApplyModelSettings,
} from "../../runtime/modelConfig.ts"

import {
  redactSensitiveValue,
} from "../../security/redact.ts"

import {
  appendActionLog,
  readConfigWing,
  writeConfigWing,
} from "../../session/store.ts"

import {
  activateProfile,
} from "../../runtime/modelRegistry.ts"

import {
  CONFIG_WING_ORDER,
} from "../../config/configWings.ts"

import type { ToolDefinition } from "../registry.ts"

export const configTools: ToolDefinition[] = [
{
  name: "tool_manage_config",
  permissionTier: "edit",
  description: "Read or update technical configuration stored in SQLite CONF_* wings. Use this instead of reading or writing JSON config files manually. ALWAYS wrap channel settings inside their provider key (e.g., { 'telegram': { 'enabled': true } }).\n\nSchemas for wings:\n- CONF_WEBSEARCH: { provider: 'default' | 'brave' | 'serper' | 'tavily', apiKey?: string } (Brave, Serper and Tavily are cloud search provider APIs)\n- CONF_CHANNELS: { telegram: { enabled: boolean, token?: string, ... }, ... }\n- CONF_SYSTEM: System environment variables\n- CONF_MODELS: Models and provider configuration",
  inputSchema: {
    type: "object",
    properties: {
      action: {
        type: "string",
        enum: ["read", "write", "get", "set", "activate_model"],
        description: "La acción a realizar:\n- 'read': Lee el bloque completo de la sección (wing).\n- 'write': Escribe/reemplaza el bloque completo de la sección.\n- 'get': Lee una propiedad específica usando notación de puntos (ej: 'telegram.enabled').\n- 'set': Modifica una propiedad específica usando notación de puntos (ej: 'telegram.enabled').\n- 'activate_model': Cambia el modelo activo del sistema usando el ID del perfil."
      },
      wing: {
        type: "string",
        enum: [...CONFIG_WING_ORDER],
        description: "La sección de configuración (requerido para 'read', 'write', 'get', 'set')."
      },
      path: {
        type: "string",
        description: "Ruta del valor a leer o modificar en notación de puntos (ej: 'telegram.enabled' o 'profiles.0.active'). Requerido para 'get' y 'set'."
      },
      value: {
        description: "El valor a escribir. Puede ser un JSON string, objeto, array, número, booleano, etc. Requerido para 'write', 'set' y 'activate_model' (donde representa el ID del perfil)."
      },
    },
    required: ["action"],
    additionalProperties: false,
  },
  concurrencySafe: false,
  validate: input => validateZod(manageConfigInputZod, input),
  async run(input, context) {
    const parsed = parseZod(manageConfigInputZod, input, "tool_manage_config input")
    const action = parsed.action
    const wing = parsed.wing

    function getPathValue(obj: any, path: string): any {
      if (!path) return obj
      const parts = path.split(".")
      let current = obj
      for (const part of parts) {
        if (current === null || current === undefined) return undefined
        current = current[part]
      }
      return current
    }

    function setPathValue(obj: any, path: string, val: any): any {
      if (!path) return val
      const parts = path.split(".")
      const last = parts.pop()!
      let current = obj
      for (const part of parts) {
        if (current[part] === undefined || current[part] === null || typeof current[part] !== "object") {
          current[part] = /^\d+$/.test(parts[parts.indexOf(part) + 1] || last) ? [] : {}
        }
        current = current[part]
      }
      current[last] = val
      return obj
    }

    if (action === "activate_model") {
      const profileId = String(parsed.value).trim()
      const target = activateProfile(profileId)
      loadAndApplyModelSettings(process.env)
      return {
        ok: true,
        activeProfile: redactSensitiveValue(target),
        effect: "model_config_reloaded",
      }
    }

    if (!wing) {
      return formatToolError("wing is required")
    }

    if (action === "read") {
      return { wing, value: redactSensitiveValue(readConfigWing(context.rootDir, wing)) }
    }

    if (action === "get") {
      const path = parsed.path || ""
      const config = readConfigWing(context.rootDir, wing)
      const redactedConfig = redactSensitiveValue(config)
      const val = getPathValue(redactedConfig, path)
      return { wing, path, value: val }
    }

    let valueToSave: unknown
    if (action === "write") {
      const val = parseJsonStringValue(parsed.value)
      if (val === undefined) return formatToolError("value is required when action='write'")
      valueToSave = val
    } else if (action === "set") {
      const path = parsed.path || ""
      const val = parseJsonStringValue(parsed.value)
      const currentConfig = JSON.parse(JSON.stringify(readConfigWing(context.rootDir, wing))) // deep copy
      valueToSave = setPathValue(currentConfig, path, val)
    } else {
      return formatToolError(`Unsupported action: ${action}`)
    }

    const normalizedValue = normalizeConfigWingValue(wing, valueToSave)
    const result = writeConfigWing(context.rootDir, wing, normalizedValue as never)
    if (wing === "CONF_SYSTEM" || wing === "CONF_MODELS") {
      loadAndApplyModelSettings(process.env)
    }
    appendActionLog(context.rootDir, "Configuracion tecnica modificada", {
      wing,
      changed: result.changed,
      path: action === "set" ? parsed.path : undefined,
    })
    return {
      wing,
      path: action === "set" ? parsed.path : undefined,
      ok: true,
      changed: result.changed,
      bytes: result.bytes,
      effect: wing === "CONF_SYSTEM" || wing === "CONF_MODELS"
        ? "model_config_reloaded"
        : wing === "CONF_WEBSEARCH" || wing === "CONF_CHANNELS"
          ? "daemon_restart_required"
          : "stored",
    }
  },
},

]
