// Auto-generated by scripts/split_registry.py — do not edit manually.
// Domain: config (1 tools)

import {
  formatToolError,
  manageConfigInputZod,
  normalizeConfigWingValue,
  parseJsonStringValue,
  parseZod,
  validateZod,
} from "../internal.ts"

import {
  loadAndApplyModelSettings,
} from "../../runtime/modelConfig.ts"

import {
  redactSensitiveValue,
} from "../../security/redact.ts"

import {
  appendActionLog,
  readConfigWing,
  writeConfigWing,
} from "../../session/store.ts"

import {
  activateProfile,
} from "../../runtime/modelRegistry.ts"

import {
  CONFIG_WING_ORDER,
  type ConfigWingName,
} from "../../config/configWings.ts"

import type { ToolDefinition } from "../registry.ts"

const DANGEROUS_CONFIG_PATH_SEGMENTS = new Set(["__proto__", "prototype", "constructor"])

function hasDangerousConfigPathSegment(path: string): boolean {
  return path.split(".").some(segment => DANGEROUS_CONFIG_PATH_SEGMENTS.has(segment))
}

function getPathValue(obj: unknown, path: string): unknown {
  if (!path) return obj
  const parts = path.split(".")
  let current: unknown = obj
  for (const part of parts) {
    if (current === null || current === undefined || typeof current !== "object") return undefined
    current = (current as Record<string, unknown>)[part]
  }
  return current
}

function setPathValue(obj: Record<string, unknown>, path: string, val: unknown): Record<string, unknown> {
  if (!path) return val as Record<string, unknown>
  const parts = path.split(".")
  const last = parts.pop()!
  let current: Record<string, unknown> = obj
  for (let i = 0; i < parts.length; i++) {
    const part = parts[i]!
    const nextKey = parts[i + 1] ?? last
    if (current[part] === undefined || current[part] === null || typeof current[part] !== "object") {
      current[part] = /^\d+$/.test(nextKey) ? [] : {}
    }
    current = current[part] as Record<string, unknown>
  }
  current[last] = val
  return obj
}

function valuesEqual(a: unknown, b: unknown): boolean {
  return JSON.stringify(a) === JSON.stringify(b)
}

function normalizeTelegramSetPath(path: string, val: unknown): { path: string; value: unknown } {
  if (path === "telegram.chatId" || path === "telegram.chat_id") {
    const normalizedPath = "telegram.allowedChats"
    if (typeof val === "number" && Number.isFinite(val)) {
      return { path: normalizedPath, value: [val] }
    }
    if (typeof val === "string" && /^\d+$/.test(val.trim())) {
      return { path: normalizedPath, value: [Number(val.trim())] }
    }
    if (Array.isArray(val)) {
      return { path: normalizedPath, value: val }
    }
    return { path: normalizedPath, value: val }
  }
  return { path, value: val }
}

function resolveConfigWriteEffect(wing: ConfigWingName, changed: boolean): string {
  if (!changed) return "none"
  if (wing === "CONF_SYSTEM" || wing === "CONF_MODELS") return "model_config_reloaded"
  if (wing === "CONF_WEBSEARCH") return "config_stored"
  if (wing === "CONF_CHANNELS") return "channels_reload_required"
  return "stored"
}

function normalizeWebSearchSet(
  current: Record<string, unknown>,
  path: string,
  val: unknown,
): { path: string; value: unknown; config: Record<string, unknown> } {
  const config = JSON.parse(JSON.stringify(current)) as Record<string, unknown>
  const normalized = setPathValue(config, path, val)
  const apiKey = typeof normalized.apiKey === "string" ? normalized.apiKey.trim() : ""
  const provider = normalized.provider
  if (path === "apiKey" && apiKey && (provider === undefined || provider === "default")) {
    normalized.provider = "brave"
  }
  return { path, value: val, config: normalized }
}

export const configTools: ToolDefinition[] = [
{
  name: "tool_manage_config",
  permissionTier: "edit",
  description:
    "Read or update technical configuration stored as JSON under memory/config/ (CONF_*.json). " +
    "Do NOT read or write those JSON files manually. " +
    "If Telegram is already enabled with a token and allowedChats, do NOT call set/write again unless the user explicitly asks to reconfigure.\n\n" +
    "Schemas for config blocks (CONF_*.json):\n" +
    "- CONF_WEBSEARCH: { provider: 'default' | 'brave' | 'serper' | 'tavily', apiKey?: string }. Setting apiKey alone auto-enables provider='brave'.\n" +
    "- CONF_CHANNELS: { telegram: { enabled: boolean, token?: string, allowedChats: number[] }, ... }\n" +
    "- CONF_SYSTEM, CONF_MODELS: model and environment settings\n\n" +
    "EXAMPLES:\n" +
    "- Set websearch provider: { action: 'set', config: 'CONF_WEBSEARCH', path: 'provider', value: 'brave' }\n" +
    "- Enable telegram: { action: 'set', config: 'CONF_CHANNELS', path: 'telegram.enabled', value: true }\n" +
    "- Allowed chat: { action: 'set', config: 'CONF_CHANNELS', path: 'telegram.allowedChats', value: [1515784684] }\n" +
    "Use allowedChats (not chatId). action 'get' never changes config.",
  inputSchema: {
    type: "object",
    properties: {
      action: {
        type: "string",
        enum: ["read", "write", "get", "set", "activate_model"],
        description:
          "read/write/get/set on a config block, or activate_model to switch the active model profile.",
      },
      config: {
        type: "string",
        enum: [...CONFIG_WING_ORDER],
        description: "Configuration block name (CONF_MODELS, CONF_CHANNELS, etc.). Required for read, write, get, set.",
      },
      wing: {
        type: "string",
        enum: [...CONFIG_WING_ORDER],
        description: "Deprecated alias for config.",
      },
      path: {
        type: "string",
        description: "Dot path for get/set (e.g. telegram.enabled, telegram.allowedChats).",
      },
      value: {
        description: "Value for write/set/activate_model.",
      },
    },
    required: ["action"],
    additionalProperties: false,
  },
  concurrencySafe: false,
  validate: input => {
    const validationError = validateZod(manageConfigInputZod, input)
    if (validationError) return validationError
    if (input.action === "set" && typeof input.path === "string" && hasDangerousConfigPathSegment(input.path)) {
      return "path contains a forbidden prototype-pollution segment"
    }
    return null
  },
  async run(input, context) {
    const parsed = parseZod(
      manageConfigInputZod,
      { ...input, wing: (input as Record<string, unknown>).wing ?? (input as Record<string, unknown>).config },
      "tool_manage_config input",
    )
    const action = parsed.action
    const configBlock = parsed.wing

    if (typeof input === "object" && input !== null && !("action" in input) && Object.keys(input).length === 1) {
      const loneKey = Object.keys(input)[0]
      if (["provider", "apiKey", "token", "enabled"].includes(loneKey)) {
        return { ok: false, error: `Wrong invocation. Use: { action: 'set', config: 'CONF_WEBSEARCH' (or CONF_CHANNELS), path: '${loneKey}', value: '...' }` }
      }
    }

    if (action === "activate_model") {
      const profileId = String(parsed.value).trim()
      const target = activateProfile(profileId)
      loadAndApplyModelSettings(process.env)
      return {
        ok: true,
        activeProfile: redactSensitiveValue(target),
        effect: "model_config_reloaded",
      }
    }

    if (!configBlock) {
      return formatToolError("config is required (CONF_MODELS, CONF_CHANNELS, etc.)")
    }

    if (action === "read") {
      return { config: configBlock, value: redactSensitiveValue(readConfigWing(context.rootDir, configBlock)) }
    }

    if (action === "get") {
      const path = parsed.path || ""
      const config = readConfigWing(context.rootDir, configBlock)
      const redactedConfig = redactSensitiveValue(config)
      const val = getPathValue(redactedConfig, path)
      return { config: configBlock, path, value: val, effect: "none" }
    }

    let valueToSave: unknown
    let effectivePath = parsed.path || ""

    if (action === "write") {
      const val = parseJsonStringValue(parsed.value)
      if (val === undefined) return formatToolError("value is required when action='write'")
      valueToSave = val
    } else if (action === "set") {
      let path = parsed.path || ""
      let val = parseJsonStringValue(parsed.value)
      if (configBlock === "CONF_CHANNELS") {
        const normalized = normalizeTelegramSetPath(path, val)
        path = normalized.path
        val = normalized.value
      }
      effectivePath = path
      const currentConfig = JSON.parse(JSON.stringify(readConfigWing(context.rootDir, configBlock))) as Record<string, unknown>
      if (configBlock === "CONF_WEBSEARCH") {
        const normalized = normalizeWebSearchSet(currentConfig, path, val)
        path = normalized.path
        val = normalized.value
        if (valuesEqual(currentConfig, normalized.config)) {
          return {
            config: configBlock,
            path,
            ok: true,
            changed: false,
            bytes: 0,
            effect: "none",
            message: "Value already configured; no write performed.",
          }
        }
        valueToSave = normalized.config
      } else {
        const currentAtPath = getPathValue(currentConfig, path)
        if (valuesEqual(currentAtPath, val)) {
          return {
            config: configBlock,
            path,
            ok: true,
            changed: false,
            bytes: 0,
            effect: "none",
            message: "Value already configured; no write performed.",
          }
        }
        valueToSave = setPathValue(currentConfig, path, val)
      }
    } else {
      return formatToolError(`Unsupported action: ${action}`)
    }

    const normalizedValue = normalizeConfigWingValue(configBlock, valueToSave)
    const result = writeConfigWing(context.rootDir, configBlock, normalizedValue as never)
    if (configBlock === "CONF_SYSTEM" || configBlock === "CONF_MODELS") {
      loadAndApplyModelSettings(process.env)
    }
    appendActionLog(context.rootDir, "Configuracion tecnica modificada", {
      config: configBlock,
      changed: result.changed,
      path: action === "set" ? effectivePath : undefined,
    })
    const effect = resolveConfigWriteEffect(configBlock, result.changed)
    const webSearchReady = configBlock === "CONF_WEBSEARCH" && result.changed
      && (effectivePath === "apiKey" || effectivePath === "provider")
    return {
      config: configBlock,
      path: action === "set" ? effectivePath : undefined,
      ok: true,
      changed: result.changed,
      bytes: result.bytes,
      effect,
      ...(webSearchReady ? {
        message: "Web search configured (provider=brave when apiKey was set). Call Web action=search for the user's request now; never repeat the raw API key in your reply.",
      } : result.changed ? {} : { message: "Value already configured; no write performed." }),
    }
  },
},

]
