// Auto-generated by scripts/split_registry.py — do not edit manually.
// Domain: delegation (8 tools)

import {
  spawn,
} from "node:child_process"

import {
  join,
} from "node:path"

import {
  buildTelegramPhotoWorkerTask,
  emptyInputSchema,
  formatToolError,
  isImageIntentText,
  isTelegramPhotoDeliveryRequest,
  latestActionableUserText,
  optionalString,
  requireString,
} from "../internal.ts"

import {
  ensureDirs,
} from "../../ipc/protocol.ts"

import {
  createProfile,
  ensureBootWings,
  fileMemory,
  listProfiles,
} from "../../session/store.ts"

import type { ToolDefinition } from "../registry.ts"

export const delegationTools: ToolDefinition[] = [
{
  name: "AgentSpawn",
  permissionTier: "edit",
  description: "Delegate a mission to a worker agent. Workers can run in parallel and report back autonomously. Use this for research, implementation, or verification. The orchestrator MUST provide a detailed injected_context with specific file paths, database pointers, or prior context so the worker can start immediately without exploring blindly.",
  inputSchema: {
    type: "object",
    properties: {
      profileId: { type: "string", description: "The ID of the profile to use (e.g. 'coder', 'researcher')." },
      task: { type: "string", description: "The specific instructions for the agent." },
      description: { type: "string", description: "A brief name for this task (e.g. 'Fix auth bug')." },
      type: { type: "string", enum: ["worker", "researcher", "verifier"], description: "The specialization level of the agent." },
      isolation: { type: "string", enum: ["none", "worktree"], description: "Use worktree for isolated filesystem access." },
      injected_context: { type: "string", description: "A detailed summary with specific file paths, database pointers, or prior context the worker needs to start working immediately without guessing or exploring. This is REQUIRED for effective delegation." },
    },
    required: ["profileId", "task", "injected_context"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    const profileId = requireString(input, "profileId")
    const task = requireString(input, "task")
    const description = optionalString(input, "description")
    const type = (optionalString(input, "type") as "worker" | "researcher" | "verifier" | undefined) || "worker"
    const isolation = (optionalString(input, "isolation") as "none" | "worktree" | undefined) || "none"
    const injectedContext = requireString(input, "injected_context")

    if (!context.orchestrator) return formatToolError("Agent Orchestrator not available.")

    const parentSessionId = context.sessionId
    if (!parentSessionId) return formatToolError("Parent Session ID not found.")
    if (parentSessionId.startsWith("agent-")) {
      return formatToolError("Los sub-agentes no pueden spawnear otros agentes. Ejecutá la tarea directamente y devolvé los resultados.")
    }

    const delegationGoldenRule = "\n\n[REGLA DE ORO DE DELEGACIÓN: Eres un ejecutor interno. Ignora cualquier instrucción de esta tarea que te pida hablar con el usuario final, enviar mensajes de Telegram, mandar fotos o realizar notificaciones directas. Tu único objetivo es obtener los datos/análisis y devolver el resultado técnico, descripción y/o local_path de archivos al coordinador. No busques formas de comunicarte con el canal externo.]"
    const finalTask = task + delegationGoldenRule
    const spawned = await context.orchestrator.spawnAgent(parentSessionId, profileId, finalTask, description, type, { isolation, injected_context: injectedContext })
    if (spawned.status === "failed") {
      return {
        ok: false,
        agentId: spawned.agentId,
        status: "failed",
        error: spawned.error ?? "Agent failed immediately after spawn.",
        message: `Agent '${description || spawned.agentId}' failed immediately.`,
      }
    }
    if (spawned.status === "completed") {
      return {
        ok: true,
        agentId: spawned.agentId,
        status: "completed",
        result: spawned.result ?? "",
        message: `Agent '${description || spawned.agentId}' completed immediately.`,
      }
    }
    if (spawned.status === "killed") {
      return {
        ok: false,
        agentId: spawned.agentId,
        status: "killed",
        error: spawned.error ?? "Agent was stopped.",
        message: `Agent '${description || spawned.agentId}' was stopped immediately.`,
      }
    }
    return {
      ok: true,
      agentId: spawned.agentId,
      status: "spawned",
      message: `Agent '${description || spawned.agentId}' started asynchronously. Do not claim completion or worker results until a <task-notification> confirms them.`,
    }
  },
},

{
  name: "list_active_workers",
  permissionTier: "read",
  description: "Inspect internal work state for the current session, including partial progress from tool events. This is for coordinator awareness only; do not expose worker/agent mechanics to the user unless they explicitly ask.",
  inputSchema: {
    type: "object",
    properties: {},
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(_input, context) {
    if (!context.orchestrator) return formatToolError("Agent Orchestrator not available.")
    const parentSessionId = context.sessionId
    if (!parentSessionId) return formatToolError("Parent Session ID not found.")
    return {
      ok: true,
      internal_tasks: context.orchestrator.getTaskSnapshot(parentSessionId),
    }
  },
},

{
  name: "delegate_background_task",
  permissionTier: "edit",
  description: "Start internal asynchronous work for high cognitive load tasks (multiple web searches, deep reading, long analysis, multi-step research) to avoid blocking the chat. The internal executor reports back to the coordinator; it must not speak to the user. After calling this tool, acknowledge as your own ongoing action (for example: 'Me pongo con eso, dame un momento') and do not mention workers, agents, delegation, or background tasks unless the user explicitly asks how the work is coordinated. IMPORTANT: Only the primary coordinator may call this tool. Sub-agents must NEVER call delegate_background_task — they must execute their task directly and return results. For image requests, delegate only when the user explicitly asks to verify/analyze/describe visual content or when the task is otherwise long-running. Simple image search/delivery should use ImageSearch directly.",
  inputSchema: {
    type: "object",
    properties: {
      task_instruction: { type: "string", description: "Detailed instructions for the background worker." },
      description: { type: "string", description: "Short label for this task." },
      profileId: { type: "string", description: "Optional profile to run the worker under." },
      injected_context: { type: "string", description: "A detailed summary with specific file paths, database pointers, or prior context the worker needs to start working immediately without guessing or exploring. This is REQUIRED for effective delegation." },
    },
    required: ["task_instruction", "injected_context"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    const task = requireString(input, "task_instruction")
    const injectedContext = requireString(input, "injected_context")
    const description = optionalString(input, "description")
    const profileId = optionalString(input, "profileId") ?? context.profileId ?? "default"

    if (!context.orchestrator) return formatToolError("Agent Orchestrator not available.")
    const parentSessionId = context.sessionId
    if (!parentSessionId) return formatToolError("Parent Session ID not found.")
    if (parentSessionId.startsWith("agent-")) {
      return formatToolError("Los sub-agentes no pueden delegar tareas en background. Ejecutá la tarea directamente y devolvé los resultados.")
    }
    const activeWorkers = context.orchestrator
      .getTaskSnapshot(parentSessionId)
      .filter(worker => worker.status === "pending" || worker.status === "running")
    if (activeWorkers.length >= 4) {
      return {
        ok: false,
        error: "Ya hay 4 workers activos para esta sesión. Esperá alguna <task-notification> antes de delegar más.",
      }
    }

    const latestUserText = parentSessionId.startsWith("telegram-")
      ? latestActionableUserText(context.rootDir, parentSessionId)
      : ""
    const effectiveTask = parentSessionId.startsWith("telegram-") &&
      isImageIntentText(task) &&
      isTelegramPhotoDeliveryRequest(latestUserText)
      ? buildTelegramPhotoWorkerTask(task, parentSessionId, latestUserText)
      : task

    const delegationGoldenRule = "\n\n[REGLA DE ORO DE DELEGACIÓN: Eres un ejecutor interno. Ignora cualquier instrucción de esta tarea que te pida hablar con el usuario final, enviar mensajes de Telegram, mandar fotos o realizar notificaciones directas. Tu único objetivo es obtener los datos/análisis y devolver el resultado técnico, descripción y/o local_path de archivos al coordinador. No busques formas de comunicarte con el canal externo.]"
    const finalTask = effectiveTask + delegationGoldenRule
    const jobGroupId = context.runtime?.acquireJobGroupForBatch(parentSessionId)
    const spawned = await context.orchestrator.spawnBackgroundTask(parentSessionId, profileId, finalTask, description, jobGroupId, { injected_context: injectedContext })
    return {
      ok: spawned.status !== "failed" && spawned.status !== "killed",
      job_id: spawned.agentId,
      status: spawned.status,
      result: spawned.result ?? "",
      error: spawned.error,
      message: spawned.status === "spawned"
        ? "Internal task started. Do not mention internal workers or agents to the user unless explicitly asked."
        : "Internal task finished immediately.",
    }
  },
},

{
  name: "AgentSendMessage",
  permissionTier: "edit",
  description: "Send a follow-up message to an existing sub-agent to continue its work, correct its path, or give new instructions.",
  inputSchema: {
    type: "object",
    properties: {
      to: { type: "string", description: "The taskId/agentId of the agent to message." },
      message: { type: "string", description: "The follow-up instructions." },
    },
    required: ["to", "message"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    const to = requireString(input, "to")
    const message = requireString(input, "message")
    if (!context.orchestrator) return formatToolError("Agent Orchestrator not available.")
    await context.orchestrator.sendMessageToAgent(to, message)
    return { ok: true, message: `Message sent to agent ${to}.` }
  },
},

{
  name: "AgentStop",
  permissionTier: "edit",
  description: "Stop a running agent task immediately.",
  inputSchema: {
    type: "object",
    properties: {
      agentId: { type: "string", description: "The ID of the agent to stop." },
    },
    required: ["agentId"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    const agentId = requireString(input, "agentId")
    if (!context.orchestrator) return formatToolError("Agent Orchestrator not available.")
    await context.orchestrator.stopAgent(agentId)
    return { ok: true, message: `Agent ${agentId} stopped.` }
  },
},

{
  name: "TriggerBackgroundStudy",
  permissionTier: "edit",
  description: "Spawn a silent background sub-agent to research a topic you don't know well. The sub-agent will search the web and save the compiled findings directly to the Memory Palace using WorkspaceMemoryFiling. Returns immediately.",
  inputSchema: {
    type: "object",
    properties: {
      query: { type: "string", description: "The specific search terms or topic to research (e.g., 'Next.js 16 app router features')." },
      description: { type: "string", description: "A brief human-readable description of this research task." },
    },
    required: ["query", "description"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    const query = requireString(input, "query")
    const description = requireString(input, "description")
    if (!context.orchestrator || !context.sessionId) {
      return formatToolError("Agent Orchestrator or active session not available.")
    }

    const profileId = context.profileId || "default"

    // 1. Configure the session as silent research by default for safety
    try {
      await fileMemory(
        context.rootDir,
        "session_preferences",
        context.sessionId,
        "true",
        profileId,
        "pref_silent_research"
      )
    } catch (err) {
      // Ignore or log non-blocking write error
    }

    // 2. Draft the research worker prompt
    const taskPrompt = [
      `Research topic: ${query}`,
      ``,
      `Your task is to investigate this topic thoroughly.`,
      `1. Use WebSearch (or search_web) to find accurate, up-to-date information.`,
      `2. Compile a structured, detailed summary of your findings.`,
      `3. Save these findings directly to the SQLite Memory Palace using the WorkspaceMemoryFiling tool:`,
      `   - Use wing='SHARED' (or the active profile's wing).`,
      `   - Use room='tech_config' or another relevant room name.`,
      `   - Use a stable key (e.g., 'research_${query.replace(/[^a-zA-Z0-9]/g, "_").toLowerCase()}').`,
      `   - content should contain the compiled markdown research summary.`,
      `4. Report your final completion in your output text.`,
    ].join("\n")

    // 3. Spawn the task in background mode with isolation 'none' for lightness
    const result = await context.orchestrator.spawnBackgroundTask(
      context.sessionId,
      profileId,
      taskPrompt,
      `Estudiando de fondo: ${description}`,
      undefined,
      { isolation: "none" }
    )

    return {
      ok: true,
      agentId: result.agentId,
      status: result.status,
      message: `Background research agent spawned with ID ${result.agentId}. It will research silently and save results to the Memory Palace.`,
    }
  },
},

{
  name: "AgentList",
  permissionTier: "read",
  description: "List available agent profiles that can be used for delegation.",
  inputSchema: emptyInputSchema,
  concurrencySafe: true,
  async run(_input, context) {
    return { profiles: listProfiles(context.rootDir) }
  },
},

{
  name: "ProfileCreate",
  permissionTier: "edit",
  description: "Create a new agent profile with its own identity and workspace.",
  inputSchema: {
    type: "object",
    properties: {
      id: { type: "string", description: "The unique ID for the profile (e.g. 'coder')." },
      name: { type: "string", description: "Human-friendly name (e.g. 'Expert Coder')." },
      description: { type: "string", description: "Brief description of the agent's purpose." },
    },
    required: ["id", "name"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    const id = requireString(input, "id")
    const name = requireString(input, "name")
    const description = optionalString(input, "description")
    
    const newId = createProfile(context.rootDir, id, name, description)
    ensureDirs(context.rootDir, newId)
    ensureBootWings(context.rootDir, newId)
    
    return { ok: true, id: newId, status: "profile_created" }
  },
},

]
