// Auto-generated by scripts/split_registry.py — do not edit manually.
// Domain: file (7 tools)

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from "node:fs"

import {
  dirname,
  join,
  relative,
} from "node:path"

import {
  DEFAULT_GREP_LIMIT,
  emptyInputSchema,
  findStringOccurrences,
  formatToolError,
  normalizePathInput,
  optionalBoolean,
  optionalNumber,
  optionalPathInputSchema,
  optionalString,
  requireString,
  resolveWorkspacePath,
  runRg,
  toWorkspaceRelative,
} from "../internal.ts"

import type { ToolDefinition } from "../registry.ts"

export const fileTools: ToolDefinition[] = [
{
  name: "pwd",
  permissionTier: "read",
  description: "Return the current workspace directory.",
  inputSchema: emptyInputSchema,
  concurrencySafe: true,
  async run(_input, context) {
    return { cwd: context.cwd }
  },
},

{
  name: "list_files",
  permissionTier: "read",
  description: "List files in a workspace-relative directory.",
  inputSchema: optionalPathInputSchema,
  concurrencySafe: true,
  async run(input, context) {
    const target = normalizePathInput(input)
    const directory = await resolveWorkspacePath(context.rootDir, context.cwd, target, context, "list_files")
    return readdirSync(directory).map(name => {
      const absolute = join(directory, name)
      const stats = statSync(absolute)
      return {
        name,
        path: toWorkspaceRelative(context.rootDir, absolute),
        type: stats.isDirectory() ? "dir" : "file",
      }
    })
  },
},

{
  name: "Read",
  aliases: ["read_file"],
  permissionTier: "read",
  isReadOnly: true,
  isSearchOrReadCommand: true,
  description: "Read a UTF-8 file from the workspace. Returns either content, a stub (file_too_large/binary/device_file), or not_found. Populates readFileState so subsequent Edit/Write can detect mtime drift.",
  inputSchema: {
    type: "object",
    properties: {
      path: { type: "string" },
      offset: { type: "number" },
      line_limit: { type: "number" },
    },
    required: ["path"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  validate: input => {
    if (typeof input.path !== "string" || input.path.length === 0) return "path must be a non-empty string"
    if (input.offset !== undefined && (typeof input.offset !== "number" || !Number.isInteger(input.offset) || input.offset < 0)) {
      return "offset must be a non-negative integer"
    }
    if (input.line_limit !== undefined && (typeof input.line_limit !== "number" || !Number.isInteger(input.line_limit) || input.line_limit < 0)) {
      return "line_limit must be a non-negative integer"
    }
    return null
  },
  async run(input, context) {
    const path = requireString(input, "path")
    const offset = optionalNumber(input, "offset") ?? 0
    const lineLimit = optionalNumber(input, "line_limit")
    const file = await resolveWorkspacePath(context.rootDir, context.cwd, path, context, "Read")
    const { readFile, MAX_READ_SIZE_BYTES } = await import("../file/read.ts")
    const result = await readFile({
      sessionId: context.sessionId ?? "default",
      rootDir: context.rootDir,
      cwd: context.cwd,
      path: file,
      offset,
      line_limit: lineLimit,
    })
    if (result.type === "not_found") {
      return formatToolError(`File not found: ${path}`)
    }
    if (result.type === "binary") {
      return {
        ...result,
        error: "binary_file_detected",
        message: "Binary file detected. Use a different tool (e.g. media pipeline) to handle binary content.",
      }
    }
    if (result.type === "device_file") {
      return {
        ...result,
        error: "device_file_blocked",
        message: "Reading from /dev, /proc, or /sys is blocked.",
      }
    }
    if (result.type === "file_too_large") {
      return {
        ...result,
        error: "file_too_large",
        message: `File is ${result.bytes} bytes (max ${MAX_READ_SIZE_BYTES}). Use offset/line_limit to paginate.`,
      }
    }
    return result
  },
},

{
  name: "Write",
  aliases: ["write_file"],
  permissionTier: "edit",
  sideEffect: true,
  description: "Create or overwrite a file in the workspace. Snapshots prior content to fileHistory (TTL 30d). Runs secret guard on content. Soft pre-read warning if file existed but Read was not called in this session.",
  inputSchema: {
    type: "object",
    properties: {
      path: { type: "string" },
      content: { type: "string" },
    },
    required: ["path", "content"],
    additionalProperties: false,
  },
  concurrencySafe: false,
  validate: input => {
    if (typeof input.path !== "string" || input.path.length === 0) return "path must be a non-empty string"
    if (typeof input.content !== "string" || input.content.length === 0) return "content must be a non-empty string"
    return null
  },
  async run(input, context) {
    const path = requireString(input, "path")
    const content = requireString(input, "content")
    const file = await resolveWorkspacePath(context.rootDir, context.cwd, path, context, "Write")

    // Notebook reject
    const { isNotebookFile, isMarkdownFile, isSettingsFile, checkEditSize } = await import("./file-edit-helpers.ts")
    if (isNotebookFile(file)) {
      return formatToolError("Cannot Write a .ipynb file. Use the notebook tooling instead.")
    }

    // Secret guard
    const { isSafeToWrite } = await import("../secret-scanner.ts")
    const safety = isSafeToWrite(content)
    if (!safety.safe) {
      return formatToolError(`Secret scanner blocked Write: ${safety.findings.map(f => f.patternId).join(", ")}`)
    }

    // Pre-read check (soft)
    const { isFileStale, getReadFileStateForTool } = await import("../file-state.ts")
    const sessionId = context.sessionId ?? "default"
    const entry = getReadFileStateForTool(sessionId, context.rootDir, file)
    let preReadWarning: string | undefined
    if (existsSync(file) && entry === undefined) {
      preReadWarning = "File existed but no prior Read in this session. Recommend Read first to see current state."
    } else if (existsSync(file) && entry !== undefined) {
      const { stale } = isFileStale(sessionId, context.rootDir, file)
      if (stale) {
        preReadWarning = "File changed since last Read. Re-Read recommended to avoid clobbering concurrent edits."
      }
    }

    // Snapshot before overwrite
    mkdirSync(dirname(file), { recursive: true })
    const existed = existsSync(file)
    if (existed) {
      const { trackEdit } = await import("../file-history.ts")
      const prior = readFileSync(file, "utf8")
      trackEdit(context.rootDir, sessionId, file, prior)
    }

    writeFileSync(file, content, "utf8")
    const out: Record<string, unknown> = {
      path,
      type: existed ? "update" : "create",
      bytes: Buffer.byteLength(content),
    }
    if (preReadWarning) out.warning = preReadWarning
    return out
  },
},

{
  name: "Edit",
  aliases: ["edit_file"],
  permissionTier: "edit",
  sideEffect: true,
  description: "Edit a file in place. Single edit (old_string/new_string) or atomic multi-edit (edits: [...] array, all-or-nothing). Snapshots prior content to fileHistory. Detects mtime drift vs last Read. Rejects .ipynb. Quote normalization supported. Returns structuredPatch on success.",
  inputSchema: {
    type: "object",
    properties: {
      path: { type: "string" },
      old_string: { type: "string", description: "Single-edit mode: the string to replace" },
      new_string: { type: "string", description: "Single-edit mode: the replacement" },
      replace_all: { type: "boolean" },
      match_index: { type: "number", description: "Optional 0-based match index to replace when old_string appears multiple times." },
      edits: {
        type: "array",
        description: "Multi-edit mode: array of {old_string, new_string, replace_all?}. Applied atomically (all-or-nothing).",
        items: {
          type: "object",
          properties: {
            old_string: { type: "string" },
            new_string: { type: "string" },
            replace_all: { type: "boolean" },
          },
          required: ["old_string", "new_string"],
          additionalProperties: false,
        },
      },
    },
    required: ["path"],
    additionalProperties: false,
  },
  concurrencySafe: false,
  validate: input => {
    if (typeof input.path !== "string" || input.path.length === 0) return "path must be a non-empty string"
    const hasSingle = typeof input.old_string === "string"
    const hasMulti = Array.isArray(input.edits)
    if (!hasSingle && !hasMulti) return "either old_string/new_string or edits[] is required"
    if (hasSingle && hasMulti) return "use either old_string/new_string or edits[], not both"
    if (hasSingle) {
      if ((input.old_string as string).length === 0) return "old_string must be a non-empty string"
      if (typeof input.new_string !== "string") return "new_string must be a string"
      if (input.match_index !== undefined && (typeof input.match_index !== "number" || !Number.isInteger(input.match_index) || input.match_index < 0)) {
        return "match_index must be a non-negative integer"
      }
      if (input.match_index !== undefined && input.replace_all === true) {
        return "match_index cannot be combined with replace_all=true"
      }
    }
    if (hasMulti) {
      if ((input.edits as any[]).length === 0) return "edits[] must not be empty"
      for (let i = 0; i < (input.edits as any[]).length; i++) {
        const e = (input.edits as any[])[i]
        if (typeof e.old_string !== "string" || e.old_string.length === 0) {
          return `edits[${i}].old_string must be a non-empty string`
        }
        if (typeof e.new_string !== "string") {
          return `edits[${i}].new_string must be a string`
        }
      }
    }
    return null
  },
  async run(input, context) {
    const path = requireString(input, "path")
    const file = await resolveWorkspacePath(context.rootDir, context.cwd, path, context, "Edit")
    const hasMulti = Array.isArray(input.edits)

    const {
      applyEditToFile,
      applyMultiEditToFile,
      isNotebookFile,
      isNoOpEdit,
      checkEditSize,
      generateUnifiedDiff,
    } = await import("./file-edit-helpers.ts")

    if (isNotebookFile(file)) {
      return formatToolError("Cannot Edit a .ipynb file. Use the notebook tooling instead.")
    }

    const sizeCheck = checkEditSize(file)
    if (!sizeCheck.ok) {
      return formatToolError(sizeCheck.error ?? "File too large for edit")
    }

    // Pre-read check (soft)
    const { getReadFileStateForTool, isFileStale } = await import("../file-state.ts")
    const sessionId = context.sessionId ?? "default"
    const readEntry = getReadFileStateForTool(sessionId, context.rootDir, file)
    let preReadWarning: string | undefined
    if (readEntry === undefined) {
      preReadWarning = "No prior Read in this session. Recommend Read first to see current state."
    } else {
      const { stale } = isFileStale(sessionId, context.rootDir, file)
      if (stale) {
        preReadWarning = "File changed since last Read. Re-Read recommended to avoid clobbering concurrent edits."
      }
    }

    const original = readFileSync(file, "utf8")
    let finalContent: string
    let editSummary: Record<string, unknown>

    if (hasMulti) {
      const edits = (input.edits as any[]).map(e => ({
        old_string: e.old_string,
        new_string: e.new_string,
        replace_all: e.replace_all,
      }))
      const multiResult = applyMultiEditToFile(original, edits, { preserveQuoteStyle: true })
      if (!multiResult.success) {
        return formatToolError(`Multi-edit failed: ${multiResult.error}`)
      }
      finalContent = multiResult.result!
      editSummary = {
        path,
        mode: "multi-edit",
        applied: multiResult.applied,
        bytes: Buffer.byteLength(finalContent),
        structuredPatch: generateUnifiedDiff(original, finalContent, path),
      }
    } else {
      const oldString = requireString(input, "old_string")
      const newString = requireString(input, "new_string")
      const replaceAll = optionalBoolean(input, "replace_all") ?? false
      const matchIndex = optionalNumber(input, "match_index")
      if (isNoOpEdit(oldString, newString)) {
        return formatToolError("No-op edit: old_string and new_string are equivalent after normalization.")
      }
      const applyResult = applyEditToFile(original, oldString, newString, {
        replaceAll,
        matchIndex,
        preserveQuoteStyle: true,
      })
      if (!applyResult.success) {
        return formatToolError(applyResult.error ?? "Edit failed")
      }
      finalContent = applyResult.result!
      editSummary = {
        path,
        mode: "single-edit",
        replaced: applyResult.matches,
        bytes: Buffer.byteLength(finalContent),
        structuredPatch: generateUnifiedDiff(original, finalContent, path),
      }
    }

    // Snapshot before write
    const { trackEdit } = await import("../file-history.ts")
    trackEdit(context.rootDir, sessionId, file, original)

    writeFileSync(file, finalContent, "utf8")
    if (preReadWarning) editSummary.warning = preReadWarning
    return editSummary
  },
},

{
  name: "Glob",
  aliases: ["glob"],
  permissionTier: "read",
  description: "Find files by glob pattern inside the workspace.",
  inputSchema: {
    type: "object",
    properties: {
      pattern: { type: "string" },
      path: { type: "string" },
      head_limit: { type: "number" },
      offset: { type: "number" },
    },
    required: ["pattern"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  validate: input => typeof input.pattern === "string" && input.pattern.length > 0 ? null : "pattern must be a non-empty string",
  async run(input, context) {
    const pattern = requireString(input, "pattern")
    const target = normalizePathInput(input)
    const headLimit = optionalNumber(input, "head_limit") ?? 100
    const offset = optionalNumber(input, "offset") ?? 0
    const absoluteTarget = await resolveWorkspacePath(context.rootDir, context.cwd, target, context, "Find")
    const relativeTarget = toWorkspaceRelative(context.rootDir, absoluteTarget)
    const result = await runRg(["--files", relativeTarget === "." ? "." : relativeTarget, "-g", pattern], context.rootDir)
    const matches = result.stdout.split("\n").map(line => line.trim()).filter(Boolean)
    const filenames = headLimit === 0 ? matches.slice(offset) : matches.slice(offset, offset + headLimit)
    return {
      pattern,
      path: target,
      numFiles: filenames.length,
      filenames,
      truncated: headLimit === 0 ? false : matches.length - offset > headLimit,
      appliedOffset: offset,
      appliedLimit: headLimit === 0 ? undefined : headLimit,
    }
  },
},

{
  name: "Grep",
  aliases: ["grep"],
  permissionTier: "read",
  isReadOnly: true,
  isSearchOrReadCommand: true,
  description: "Search file contents with ripgrep. Supports context lines (-A/-B/-C), type filter (rg --type), VCS exclusions, and glob comma-split. Dual-accepts `ignore_case` and `-i`.",
  inputSchema: {
    type: "object",
    properties: {
      pattern: { type: "string" },
      path: { type: "string" },
      output_mode: { type: "string", enum: ["files_with_matches", "content", "count"] },
      glob: { type: "string" },
      ignore_case: { type: "boolean" },
      "-i": { type: "boolean", description: "Alias for ignore_case (upstream parity)." },
      multiline: { type: "boolean" },
      head_limit: { type: "number" },
      offset: { type: "number" },
      "-B": { type: "number", description: "Lines before each match (content mode only)." },
      "-A": { type: "number", description: "Lines after each match (content mode only)." },
      "-C": { type: "number", description: "Lines of context (alias for context)." },
      context: { type: "number", description: "Lines of context (alias for -C)." },
      "-n": { type: "boolean", description: "Show line numbers (content mode only, default true)." },
      type: { type: "string", description: "File type filter (rg --type): py, js, ts, rust, go, etc." },
    },
    required: ["pattern"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  validate: input => typeof input.pattern === "string" && input.pattern.length > 0 ? null : "pattern must be a non-empty string",
  async run(input, context) {
    const pattern = requireString(input, "pattern")
    const target = normalizePathInput(input)
    const absoluteTarget = await resolveWorkspacePath(context.rootDir, context.cwd, target, context, "Grep")
    const relativeTarget = toWorkspaceRelative(context.rootDir, absoluteTarget)
    const outputMode = optionalString(input, "output_mode") ?? "files_with_matches"
    const ignoreCase = optionalBoolean(input, "ignore_case") ?? optionalBoolean(input, "-i") ?? false
    const multiline = optionalBoolean(input, "multiline") ?? false
    const headLimit = optionalNumber(input, "head_limit") ?? DEFAULT_GREP_LIMIT
    const offset = optionalNumber(input, "offset") ?? 0
    const beforeLines = optionalNumber(input, "-B") ?? optionalNumber(input, "context")
    const afterLines = optionalNumber(input, "-A") ?? optionalNumber(input, "context")
    const contextLines = optionalNumber(input, "-C")
    const showLineNumbers = optionalBoolean(input, "-n") ?? true
    const fileType = optionalString(input, "type")
    const globRaw = optionalString(input, "glob")
    const args: string[] = []
    if (ignoreCase) args.push("-i")
    if (multiline) args.push("-U", "--multiline-dotall")
    if (fileType) args.push("--type", fileType)
    if (contextLines !== undefined) args.push("-C", String(contextLines))
    if (beforeLines !== undefined && contextLines === undefined) args.push("-B", String(beforeLines))
    if (afterLines !== undefined && contextLines === undefined) args.push("-A", String(afterLines))
    for (const vcs of [".git", ".svn", ".hg", ".bzr", ".jj", ".sl"]) {
      args.push("--glob", `!**/${vcs}/**`)
    }
    if (globRaw) {
      const globs = globRaw.split(/[,\s]+/).filter(Boolean)
      for (const g of globs) args.push("--glob", g)
    }
    // Pattern starting with "-" must be passed as -e to rg
    const patternArg = pattern.startsWith("-") ? ["-e", pattern] : [pattern]
    if (outputMode === "content") {
      const finalArgs = [...args]
      if (showLineNumbers) finalArgs.push("-n")
      finalArgs.push(...patternArg, relativeTarget)
      const result = await runRg(finalArgs, context.rootDir)
      const lines = result.stdout.split("\n").filter(Boolean)
      const page = headLimit === 0 ? lines.slice(offset) : lines.slice(offset, offset + headLimit)
      return {
        mode: "content",
        content: page.join("\n"),
        numLines: page.length,
        appliedOffset: offset,
        appliedLimit: headLimit === 0 ? undefined : headLimit,
      }
    }
    if (outputMode === "count") {
      const result = await runRg([...args, "-c", ...patternArg, relativeTarget], context.rootDir)
      const lines = result.stdout.split("\n").filter(Boolean)
      const page = headLimit === 0 ? lines.slice(offset) : lines.slice(offset, offset + headLimit)
      return {
        mode: "count",
        numMatches: page.reduce((total, line) => {
          const count = Number(line.split(":").pop() ?? "0")
          return total + (Number.isFinite(count) ? count : 0)
        }, 0),
        filenames: page,
        appliedOffset: offset,
        appliedLimit: headLimit === 0 ? undefined : headLimit,
      }
    }
    const result = await runRg([...args, "-l", ...patternArg, relativeTarget], context.rootDir)
    const matches = result.stdout.split("\n").map(line => line.trim()).filter(Boolean)
    const page = headLimit === 0 ? matches.slice(offset) : matches.slice(offset, offset + headLimit)
    return {
      mode: "files_with_matches",
      numFiles: page.length,
      filenames: page,
      appliedOffset: offset,
      appliedLimit: headLimit === 0 ? undefined : headLimit,
    }
  },
},

]
