// Auto-generated by scripts/split_registry.py — do not edit manually.
// Domain: file (7 tools)

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from "node:fs"

import {
  dirname,
  join,
  relative,
} from "node:path"

import {
  DEFAULT_GREP_LIMIT,
  emptyInputSchema,
  findStringOccurrences,
  formatToolError,
  normalizePathInput,
  optionalBoolean,
  optionalNumber,
  optionalPathInputSchema,
  optionalString,
  requireString,
  resolveWorkspacePath,
  runRg,
  toWorkspaceRelative,
} from "../internal.ts"

import type { ToolDefinition } from "../registry.ts"

export const fileTools: ToolDefinition[] = [
{
  name: "pwd",
  permissionTier: "read",
  description: "Return the current workspace directory.",
  inputSchema: emptyInputSchema,
  concurrencySafe: true,
  async run(_input, context) {
    return { cwd: context.cwd }
  },
},

{
  name: "list_files",
  permissionTier: "read",
  description: "List files in a workspace-relative directory.",
  inputSchema: optionalPathInputSchema,
  concurrencySafe: true,
  async run(input, context) {
    const target = normalizePathInput(input)
    const directory = await resolveWorkspacePath(context.rootDir, context.cwd, target, context, "list_files")
    return readdirSync(directory).map(name => {
      const absolute = join(directory, name)
      const stats = statSync(absolute)
      return {
        name,
        path: toWorkspaceRelative(context.rootDir, absolute),
        type: stats.isDirectory() ? "dir" : "file",
      }
    })
  },
},

{
  name: "Read",
  aliases: ["read_file"],
  permissionTier: "read",
  description: "Read a UTF-8 file from the workspace.",
  inputSchema: {
    type: "object",
    properties: {
      path: { type: "string" },
      offset: { type: "number" },
      line_limit: { type: "number" },
    },
    required: ["path"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  validate: input => {
    if (typeof input.path !== "string" || input.path.length === 0) return "path must be a non-empty string"
    if (input.offset !== undefined && (typeof input.offset !== "number" || !Number.isInteger(input.offset) || input.offset < 0)) {
      return "offset must be a non-negative integer"
    }
    if (input.line_limit !== undefined && (typeof input.line_limit !== "number" || !Number.isInteger(input.line_limit) || input.line_limit < 0)) {
      return "line_limit must be a non-negative integer"
    }
    return null
  },
  async run(input, context) {
    const path = requireString(input, "path")
    const offset = optionalNumber(input, "offset") ?? 0
    const lineLimit = optionalNumber(input, "line_limit")
    const file = await resolveWorkspacePath(context.rootDir, context.cwd, path, context, "Read")
    const content = readFileSync(file, "utf8")
    const lines = content.split("\n")
    const totalLines = lines.length
    const pagedLines = lineLimit === undefined ? lines.slice(offset) : lines.slice(offset, offset + lineLimit)
    return {
      path,
      content: pagedLines.join("\n"),
      totalLines,
      offset,
      lineLimit,
      returnedLines: pagedLines.length,
      hasMore: offset + pagedLines.length < totalLines,
    }
  },
},

{
  name: "Write",
  aliases: ["write_file"],
  permissionTier: "edit",
  description: "Create or overwrite a file in the workspace.",
  inputSchema: {
    type: "object",
    properties: {
      path: { type: "string" },
      content: { type: "string" },
    },
    required: ["path", "content"],
    additionalProperties: false,
  },
  concurrencySafe: false,
  validate: input => {
    if (typeof input.path !== "string" || input.path.length === 0) return "path must be a non-empty string"
    if (typeof input.content !== "string" || input.content.length === 0) return "content must be a non-empty string"
    return null
  },
  async run(input, context) {
    const path = requireString(input, "path")
    const content = requireString(input, "content")
    const file = await resolveWorkspacePath(context.rootDir, context.cwd, path, context, "Write")
    mkdirSync(dirname(file), { recursive: true })
    const existed = existsSync(file)
    writeFileSync(file, content, "utf8")
    return { path, type: existed ? "update" : "create", bytes: Buffer.byteLength(content) }
  },
},

{
  name: "Edit",
  aliases: ["edit_file"],
  permissionTier: "edit",
  description: "Edit a file in place by replacing an existing string.",
  inputSchema: {
    type: "object",
    properties: {
      path: { type: "string" },
      old_string: { type: "string" },
      new_string: { type: "string" },
      replace_all: { type: "boolean" },
      match_index: { type: "number", description: "Optional 0-based match index to replace when old_string appears multiple times." },
    },
    required: ["path", "old_string", "new_string"],
    additionalProperties: false,
  },
  concurrencySafe: false,
  validate: input => {
    if (typeof input.path !== "string" || input.path.length === 0) return "path must be a non-empty string"
    if (typeof input.old_string !== "string" || input.old_string.length === 0) return "old_string must be a non-empty string"
    if (typeof input.new_string !== "string") return "new_string must be a string"
    if (input.match_index !== undefined && (typeof input.match_index !== "number" || !Number.isInteger(input.match_index) || input.match_index < 0)) {
      return "match_index must be a non-negative integer"
    }
    if (input.match_index !== undefined && input.replace_all === true) {
      return "match_index cannot be combined with replace_all=true"
    }
    return null
  },
  async run(input, context) {
    const path = requireString(input, "path")
    const oldString = requireString(input, "old_string")
    const newString = requireString(input, "new_string")
    const replaceAll = optionalBoolean(input, "replace_all") ?? false
    const matchIndex = optionalNumber(input, "match_index")
    const file = await resolveWorkspacePath(context.rootDir, context.cwd, path, context, "Edit")
    const original = readFileSync(file, "utf8")
    const matches = findStringOccurrences(original, oldString)
    const occurrences = matches.length
    if (occurrences === 0) return formatToolError(`old_string not found in ${path}`)
    if (replaceAll && matchIndex !== undefined) {
      return formatToolError("match_index cannot be combined with replace_all=true")
    }
    if (!replaceAll && occurrences > 1) {
      if (matchIndex === undefined) {
        const lineSummary = matches.map((match, index) => `${index}:${match.line}`).join(", ")
        return formatToolError(`old_string matched ${occurrences} times in ${path} at match_index:line ${lineSummary}; retry with match_index or set replace_all=true`)
      }
      if (!Number.isInteger(matchIndex) || matchIndex < 0 || matchIndex >= occurrences) {
        return formatToolError(`match_index ${matchIndex} is out of range for ${occurrences} matches in ${path}`)
      }
    }
    let updated = original
    let replaced = 0
    if (replaceAll) {
      updated = original.split(oldString).join(newString)
      replaced = occurrences
    } else if (matchIndex !== undefined) {
      const match = matches[matchIndex]
      if (!match) return formatToolError(`match_index ${matchIndex} is out of range for ${occurrences} matches in ${path}`)
      updated = `${original.slice(0, match.index)}${newString}${original.slice(match.index + oldString.length)}`
      replaced = 1
    } else {
      updated = original.replace(oldString, newString)
      replaced = 1
    }
    writeFileSync(file, updated, "utf8")
    return { path, replaced, bytes: Buffer.byteLength(updated) }
  },
},

{
  name: "Glob",
  aliases: ["glob"],
  permissionTier: "read",
  description: "Find files by glob pattern inside the workspace.",
  inputSchema: {
    type: "object",
    properties: {
      pattern: { type: "string" },
      path: { type: "string" },
      head_limit: { type: "number" },
      offset: { type: "number" },
    },
    required: ["pattern"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  validate: input => typeof input.pattern === "string" && input.pattern.length > 0 ? null : "pattern must be a non-empty string",
  async run(input, context) {
    const pattern = requireString(input, "pattern")
    const target = normalizePathInput(input)
    const headLimit = optionalNumber(input, "head_limit") ?? 100
    const offset = optionalNumber(input, "offset") ?? 0
    const absoluteTarget = await resolveWorkspacePath(context.rootDir, context.cwd, target, context, "Find")
    const relativeTarget = toWorkspaceRelative(context.rootDir, absoluteTarget)
    const result = await runRg(["--files", relativeTarget === "." ? "." : relativeTarget, "-g", pattern], context.rootDir)
    const matches = result.stdout.split("\n").map(line => line.trim()).filter(Boolean)
    const filenames = headLimit === 0 ? matches.slice(offset) : matches.slice(offset, offset + headLimit)
    return {
      pattern,
      path: target,
      numFiles: filenames.length,
      filenames,
      truncated: headLimit === 0 ? false : matches.length - offset > headLimit,
      appliedOffset: offset,
      appliedLimit: headLimit === 0 ? undefined : headLimit,
    }
  },
},

{
  name: "Grep",
  aliases: ["grep"],
  permissionTier: "read",
  description: "Search file contents with ripgrep.",
  inputSchema: {
    type: "object",
    properties: {
      pattern: { type: "string" },
      path: { type: "string" },
      output_mode: { type: "string", enum: ["files_with_matches", "content", "count"] },
      glob: { type: "string" },
      ignore_case: { type: "boolean" },
      multiline: { type: "boolean" },
      head_limit: { type: "number" },
      offset: { type: "number" },
    },
    required: ["pattern"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  validate: input => typeof input.pattern === "string" && input.pattern.length > 0 ? null : "pattern must be a non-empty string",
  async run(input, context) {
    const pattern = requireString(input, "pattern")
    const target = normalizePathInput(input)
    const absoluteTarget = await resolveWorkspacePath(context.rootDir, context.cwd, target, context, "Grep")
    const relativeTarget = toWorkspaceRelative(context.rootDir, absoluteTarget)
    const outputMode = optionalString(input, "output_mode") ?? "files_with_matches"
    const glob = optionalString(input, "glob")
    const ignoreCase = optionalBoolean(input, "ignore_case") ?? false
    const multiline = optionalBoolean(input, "multiline") ?? false
    const headLimit = optionalNumber(input, "head_limit") ?? DEFAULT_GREP_LIMIT
    const offset = optionalNumber(input, "offset") ?? 0
    const args: string[] = []
    if (ignoreCase) args.push("-i")
    if (multiline) args.push("-U", "--multiline-dotall")
    if (glob) args.push("--glob", glob)
    if (outputMode === "content") {
      const result = await runRg([...args, "-n", pattern, relativeTarget], context.rootDir)
      const lines = result.stdout.split("\n").filter(Boolean)
      const page = headLimit === 0 ? lines.slice(offset) : lines.slice(offset, offset + headLimit)
      return {
        mode: "content",
        content: page.join("\n"),
        numLines: page.length,
        appliedOffset: offset,
        appliedLimit: headLimit === 0 ? undefined : headLimit,
      }
    }
    if (outputMode === "count") {
      const result = await runRg([...args, "-c", pattern, relativeTarget], context.rootDir)
      const lines = result.stdout.split("\n").filter(Boolean)
      const page = headLimit === 0 ? lines.slice(offset) : lines.slice(offset, offset + headLimit)
      return {
        mode: "count",
        numMatches: page.reduce((total, line) => {
          const count = Number(line.split(":").pop() ?? "0")
          return total + (Number.isFinite(count) ? count : 0)
        }, 0),
        filenames: page,
        appliedOffset: offset,
        appliedLimit: headLimit === 0 ? undefined : headLimit,
      }
    }
    const result = await runRg([...args, "-l", pattern, relativeTarget], context.rootDir)
    const matches = result.stdout.split("\n").map(line => line.trim()).filter(Boolean)
    const page = headLimit === 0 ? matches.slice(offset) : matches.slice(offset, offset + headLimit)
    return {
      mode: "files_with_matches",
      numFiles: page.length,
      filenames: page,
      appliedOffset: offset,
      appliedLimit: headLimit === 0 ? undefined : headLimit,
    }
  },
},

]
