// Auto-generated by scripts/split_registry.py — do not edit manually.
// Domain: forensics (1 tools)

import {
  spawn,
} from "node:child_process"

import {
  buildEventLine,
  inferForensicsIntent,
  optionalNumber,
  optionalString,
  pickForensicsSession,
  resolveForensicsIntent,
  truncateText,
  uniqueLines,
} from "../internal.ts"

import {
  tailEvents,
} from "../../session/store.ts"

import type { ToolDefinition } from "../registry.ts"

export const forensicsTools: ToolDefinition[] = [
{
  name: "SessionForensics",
  permissionTier: "read",
  description: "Inspect persisted session evidence before answering questions about what happened, what was said, which tools/workers ran, or where a prior conclusion came from. This is ALSO the correct tool for questions about internal daemon events such as heartbeat history, memory consolidation runs, background turns, and worklog entries — use this instead of Bash/Grep over source code.",
  inputSchema: {
    type: "object",
    properties: {
      sessionId: { type: "string", description: "Optional session ID. Defaults to the current session, otherwise the latest session for the active profile." },
      intent: { type: "string", enum: ["auto", "history", "actions", "delegation", "origin"], description: "What kind of reconstruction you need." },
      question: { type: "string", description: "Optional natural language cue to help auto-select the right evidence." },
      messageLimit: { type: "number", description: "How many recent messages to inspect. Default 6." },
      worklogLimit: { type: "number", description: "How many recent worklog entries to inspect. Default 8." },
      eventLimit: { type: "number", description: "How many recent runtime events to inspect. Default 12." },
    },
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    const requestedSessionId = optionalString(input, "sessionId") ?? context.sessionId
    const requestedIntent = resolveForensicsIntent(optionalString(input, "intent"))
    const question = optionalString(input, "question")

    // Ampliación de límites máximos para SessionForensics
    const messageLimit = Math.max(1, Math.min(40, optionalNumber(input, "messageLimit") ?? 6))
    const worklogLimit = Math.max(1, Math.min(60, optionalNumber(input, "worklogLimit") ?? 8))
    const eventLimit = Math.max(1, Math.min(80, optionalNumber(input, "eventLimit") ?? 12))

    const session = pickForensicsSession(context.rootDir, context.profileId, requestedSessionId)

    // Extracción de palabras clave significativas (min. 3 caracteres)
    const searchTerms = question
      ? Array.from(new Set(question
          .normalize("NFD")
          .replace(/[\u0300-\u036f]/g, "")
          .toLowerCase()
          .match(/[a-z0-9]{3,}/g) ?? []))
          .filter(term => !["para", "por", "con", "una", "uno", "unos", "unas", "del", "las", "los", "the", "and", "for", "from", "that", "this", "sobre", "como", "cual", "que", "est", "este", "esta", "sus"].includes(term))
      : []

    let events: ReturnType<typeof tailEvents>
    let recentMessages: typeof session.messages
    let recentWorklog: typeof session.worklog

    if (searchTerms.length > 0) {
      // Filtrar todos los mensajes
      const matchedMsgs = session.messages.filter(m => {
        const textNorm = m.text.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase()
        return searchTerms.some(term => textNorm.includes(term))
      })
      recentMessages = matchedMsgs.length > 0 ? matchedMsgs.slice(-messageLimit) : session.messages.slice(-messageLimit)

      // Filtrar todos los worklogs
      const matchedLogs = session.worklog.filter(l => {
        const sumNorm = l.summary.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase()
        return searchTerms.some(term => sumNorm.includes(term))
      })
      recentWorklog = matchedLogs.length > 0 ? matchedLogs.slice(-worklogLimit) : session.worklog.slice(-worklogLimit)

      // Filtrar eventos de un pool más amplio (100 eventos)
      const allEvents = tailEvents(context.rootDir, session.id, 100)
      const matchedEvts = allEvents.filter(e => {
        const evtStr = JSON.stringify(e).normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase()
        return searchTerms.some(term => evtStr.includes(term))
      })
      events = matchedEvts.length > 0 ? matchedEvts.slice(-eventLimit) : allEvents.slice(-eventLimit)
    } else {
      events = tailEvents(context.rootDir, session.id, eventLimit)
      recentMessages = session.messages.slice(-messageLimit)
      recentWorklog = session.worklog.slice(-worklogLimit)
    }

    const effectiveIntent = requestedIntent === "auto" ? inferForensicsIntent(question) : requestedIntent

    const messageLines = recentMessages.map(message => `${message.at} ${message.role}: ${truncateText(message.text, 220)}`)
    const worklogLines = recentWorklog.map(entry => `${entry.at} [${entry.type}] ${truncateText(entry.summary, 220)}`)
    const eventLines = events.map(event => buildEventLine(event as Record<string, unknown>))

    const delegationEvidence = uniqueLines([
      ...events
        .filter(event => event.type === "agent.background.completed")
        .map(event => buildEventLine(event as Record<string, unknown>)),
      ...events
        .filter(event => event.type === "tool.start" || event.type === "tool.finish")
        .filter(event => {
          const tool = typeof (event as { tool?: unknown }).tool === "string" ? String((event as { tool?: unknown }).tool) : ""
          return ["AgentSpawn", "delegate_background_task", "list_active_workers", "AgentSendMessage"].includes(tool)
        })
        .map(event => buildEventLine(event as Record<string, unknown>)),
      ...recentWorklog
        .map(entry => entry.summary)
        .filter(summary => /\b(worker|workers|agent|agente|delegat|spawn|background)\b/i.test(summary)),
    ])

    let summary = ""
    let evidence: string[] = []
    let recommendedSources: string[] = []

    switch (effectiveIntent) {
      case "history":
        summary = "Usá los mensajes persistidos como fuente principal para reconstruir quién dijo qué."
        evidence = messageLines
        recommendedSources = ["messages", "worklog"]
        break
      case "delegation":
        summary = delegationEvidence.length > 0
          ? "Encontré evidencia operativa de delegación/workers en los eventos y/o worklog de la sesión."
          : "No encontré evidencia operativa de delegación/workers en los eventos recientes de la sesión."
        evidence = delegationEvidence.length > 0 ? delegationEvidence : [...eventLines, ...worklogLines].slice(-8)
        recommendedSources = ["events", "worklog", "messages"]
        break
      case "origin": {
        const lastUser = recentMessages.filter(message => message.role === "user").at(-1)
        const lastAssistant = recentMessages.filter(message => message.role === "assistant").at(-1)
        const originEvidence = uniqueLines([
          lastUser ? `Last user message: ${truncateText(lastUser.text, 220)}` : "",
          lastAssistant ? `Last assistant message: ${truncateText(lastAssistant.text, 220)}` : "",
          ...eventLines.filter(line => /tool\.finish|agent\.background\.completed|error/.test(line)),
          ...worklogLines.filter(line => /\b(Tool|Assistant:|Memory agent:|Turn completed|Turn started)\b/.test(line)),
        ])
        summary = "Reconstruí el origen probable desde el último intercambio y la evidencia operativa reciente."
        evidence = originEvidence.slice(0, 10)
        recommendedSources = ["messages", "events", "worklog"]
        break
      }
      case "actions":
      default:
        summary = "Usá worklog y eventos como fuente principal para explicar qué hizo el runtime en esta sesión."
        evidence = uniqueLines([...worklogLines, ...eventLines]).slice(-12)
        recommendedSources = ["worklog", "events", "messages"]
        break
    }

    return {
      ok: true,
      session: {
        id: session.id,
        title: session.title,
        state: session.state,
        createdAt: session.createdAt,
        updatedAt: session.updatedAt,
      },
      intent: effectiveIntent,
      question: question ?? null,
      summary,
      recommendedSources,
      evidence,
      counts: {
        messagesInspected: recentMessages.length,
        worklogInspected: recentWorklog.length,
        eventsInspected: events.length,
      },
      nextStepHint: "If this is still insufficient, inspect raw logs only for runtime/daemon discrepancies rather than conversational history.",
    }
  },
},

]
