// Auto-generated by scripts/split_registry.py — do not edit manually.
// Domain: mcp (3 tools)

import {
  pathToFileURL,
} from "node:url"

import {
  getMcpClient,
  optionalString,
  requireString,
  resolveWorkspacePath,
  toWorkspaceRelative,
} from "../internal.ts"

import {
  getSharedLspClient,
} from "../../lsp/client.ts"

import type { ToolDefinition } from "../registry.ts"

export const mcpTools: ToolDefinition[] = [
{
  name: "ListMcpResourcesTool",
  aliases: ["mcp_list_resources"],
  permissionTier: "read",
  description: "List resources exposed by an MCP server.",
  inputSchema: {
    type: "object",
    properties: {
      server: { type: "string" },
    },
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    const server = optionalString(input, "server") ?? "demo"
    const client = await getMcpClient(context, server)
    return {
      server,
      resources: await client.listResources(),
    }
  },
},

{
  name: "ReadMcpResourceTool",
  aliases: ["mcp_read_resource"],
  permissionTier: "read",
  description: "Read a specific MCP resource by URI.",
  inputSchema: {
    type: "object",
    properties: {
      server: { type: "string" },
      uri: { type: "string" },
    },
    required: ["uri"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  validate: input => typeof input.uri === "string" && input.uri.length > 0 ? null : "uri must be a non-empty string",
  async run(input, context) {
    const server = optionalString(input, "server") ?? "demo"
    const uri = requireString(input, "uri")
    const client = await getMcpClient(context, server)
    return {
      server,
      uri,
      resource: await client.readResource(uri),
    }
  },
},

{
  name: "LspQuery",
  permissionTier: "read",
  description: "Query TypeScript semantic information through the workspace LSP server.",
  inputSchema: {
    type: "object",
    properties: {
      action: { type: "string", enum: ["definition", "references", "hover"] },
      file: { type: "string" },
      line: { type: "number" },
      character: { type: "number" },
    },
    required: ["action", "file", "line", "character"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  validate: input => {
    if (typeof input.action !== "string" || !["definition", "references", "hover"].includes(input.action)) {
      return "action must be one of: definition, references, hover"
    }
    if (typeof input.file !== "string" || input.file.length === 0) return "file must be a non-empty string"
    if (typeof input.line !== "number" || !Number.isInteger(input.line) || input.line < 0) return "line must be a non-negative integer"
    if (typeof input.character !== "number" || !Number.isInteger(input.character) || input.character < 0) {
      return "character must be a non-negative integer"
    }
    return null
  },
  async run(input, context) {
    const action = requireString(input, "action") as "definition" | "references" | "hover"
    const file = requireString(input, "file")
    const line = input.line as number
    const character = input.character as number
    const absoluteFile = await resolveWorkspacePath(context.rootDir, context.rootDir, file, context, "LspNavigation")
    const relativeFile = toWorkspaceRelative(context.rootDir, absoluteFile)
    const fileUri = pathToFileURL(absoluteFile).href
    const client = await getSharedLspClient(context.rootDir)

    let result: unknown
    switch (action) {
      case "definition":
        result = await client.getDefinition(relativeFile, line, character)
        break
      case "references":
        result = await client.getReferences(relativeFile, line, character)
        break
      case "hover":
        result = await client.getHover(relativeFile, line, character)
        break
    }

    return {
      action,
      file: relativeFile,
      uri: fileUri,
      position: { line, character },
      result,
    }
  },
},

]
