// Auto-generated by scripts/split_registry.py — do not edit manually.
// Domain: mcp (3 tools)

import {
  pathToFileURL,
} from "node:url"

import {
  formatToolError,
} from "../internal.ts"

import {
  getMcpClient,
  optionalString,
  requireString,
  resolveWorkspacePath,
  toWorkspaceRelative,
} from "../internal.ts"

import {
  getSharedLspClient,
} from "../../lsp/client.ts"

import type { ToolDefinition, ToolContext } from "../internal.ts"

const legacyMcpTools: ToolDefinition[] = [
{
  name: "ListMcpResourcesTool",
  aliases: ["mcp_list_resources"],
  permissionTier: "read",
  isReadOnly: true,
  isMcp: true,
  isOpenWorld: true,
  description: "List resources exposed by an MCP server.",
  inputSchema: {
    type: "object",
    properties: {
      server: { type: "string" },
    },
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    const server = optionalString(input, "server") ?? "demo"
    const client = await getMcpClient(context, server)
    return {
      server,
      resources: await client.listResources(),
    }
  },
},

{
  name: "ReadMcpResourceTool",
  aliases: ["mcp_read_resource"],
  permissionTier: "read",
  isReadOnly: true,
  isMcp: true,
  isOpenWorld: true,
  description: "Read a specific MCP resource by URI.",
  inputSchema: {
    type: "object",
    properties: {
      server: { type: "string" },
      uri: { type: "string" },
    },
    required: ["uri"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  validate: input => typeof input.uri === "string" && input.uri.length > 0 ? null : "uri must be a non-empty string",
  async run(input, context) {
    const server = optionalString(input, "server") ?? "demo"
    const uri = requireString(input, "uri")
    const client = await getMcpClient(context, server)
    return {
      server,
      uri,
      resource: await client.readResource(uri),
    }
  },
},

{
  name: "McpInvokeTool",
  aliases: ["mcp_invoke"],
  permissionTier: "edit",
  isMcp: true,
  isOpenWorld: true,
  maxResultSizeChars: 100_000,
  description: "Dynamic facade for invoking MCP server tools. Discovers available tools via listMcpTools() cache, validates input, applies token-budget truncation (25K tokens), collapse classification (search/read/write).",
  inputSchema: {
    type: "object",
    properties: {
      server: { type: "string", description: "MCP server name" },
      tool: { type: "string", description: "Tool name to invoke" },
      arguments: { type: "object", description: "Tool arguments" },
    },
    required: ["server", "tool"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  validate: input => {
    if (typeof input.server !== "string" || input.server.length === 0) return "server must be a non-empty string"
    if (typeof input.tool !== "string" || input.tool.length === 0) return "tool must be a non-empty string"
    return null
  },
  async run(input, context) {
    const server = requireString(input, "server")
    const tool = requireString(input, "tool")
    const args = (input.arguments && typeof input.arguments === "object" ? input.arguments : {}) as Record<string, unknown>
    const { getMcpClient } = await import("../internal.ts")
    const { listMcpTools } = await import("../../../core/mcp/tool-registry.ts")
    const { classifyMcpToolForCollapse, normalizeMcpToolName, isReadOnlyMcpTool } = await import("./mcp-collapse.ts")
    const { truncateMcpResult, toolOutputTruncated } = await import("./mcp-truncation.ts")
    const { isMcpPermissionEnabled } = await import("../../../core/mcp/permissions.ts")
    const client = await getMcpClient(context, server)
    const descriptors = await listMcpTools(server, client)
    const normTool = normalizeMcpToolName(tool)
    const descriptor = descriptors.find(d => normalizeMcpToolName(d.name) === normTool)
    if (!descriptor) {
      return formatToolError(`Tool ${tool} not found on server ${server}. Available: ${descriptors.map(d => d.name).join(", ")}`)
    }
    // isOpenWorld enforcement: MCP tools that mutate need explicit permission
    if (descriptor.requiresWritePermission && !isReadOnlyMcpTool(descriptor.name)) {
      const allowed = await isMcpPermissionEnabled(context, server, descriptor.name)
      if (!allowed) {
        return formatToolError(`MCP tool ${server}:${descriptor.name} requires explicit permission`)
      }
    }
    const collapseClass = classifyMcpToolForCollapse(descriptor.name, server)
    const raw = await client.callTool(descriptor.name, args)
    const trunc = truncateMcpResult(raw)
    return {
      server,
      tool: descriptor.name,
      collapseClass,
      truncated: trunc.truncated,
      removedChars: trunc.removedChars,
      result: trunc.result,
      isResultTruncated: toolOutputTruncated(raw, 100_000),
    }
  },
},

]

function runLegacyMcpTool(legacyName: string, input: Record<string, unknown>, context: ToolContext) {
  const tool = legacyMcpTools.find(t => t.name === legacyName)
  if (!tool?.run) return formatToolError(`Internal MCP handler missing: ${legacyName}`)
  return tool.run(input, context)
}

function resolveMcpAction(invoked: string, input: Record<string, unknown>): string {
  const aliasMap: Record<string, string> = {
    ListMcpResourcesTool: "list_resources",
    mcp_list_resources: "list_resources",
    ReadMcpResourceTool: "read_resource",
    mcp_read_resource: "read_resource",
    McpInvokeTool: "invoke",
    mcp_invoke: "invoke",
  }
  if (aliasMap[invoked]) return aliasMap[invoked]
  const explicit = optionalString(input, "action")
  if (explicit === "list_resources" || explicit === "read_resource" || explicit === "invoke") return explicit
  if (typeof input.uri === "string") return "read_resource"
  if (typeof input.tool === "string") return "invoke"
  return "list_resources"
}

const MCP_ACTION_LEGACY: Record<string, string> = {
  list_resources: "ListMcpResourcesTool",
  read_resource: "ReadMcpResourceTool",
  invoke: "McpInvokeTool",
}

const lspQueryTool: ToolDefinition = {
  name: "LspQuery",
  permissionTier: "read",
  isReadOnly: true,
  isSearchOrReadCommand: true,
  description: "Query TypeScript semantic information through the workspace LSP server.",
  inputSchema: {
    type: "object",
    properties: {
      action: { type: "string", enum: ["definition", "references", "hover"] },
      file: { type: "string" },
      line: { type: "number" },
      character: { type: "number" },
    },
    required: ["action", "file", "line", "character"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  validate: input => {
    if (typeof input.action !== "string" || !["definition", "references", "hover"].includes(input.action)) {
      return "action must be one of: definition, references, hover"
    }
    if (typeof input.file !== "string" || input.file.length === 0) return "file must be a non-empty string"
    if (typeof input.line !== "number" || !Number.isInteger(input.line) || input.line < 0) return "line must be a non-negative integer"
    if (typeof input.character !== "number" || !Number.isInteger(input.character) || input.character < 0) {
      return "character must be a non-negative integer"
    }
    return null
  },
  async run(input, context) {
    const action = requireString(input, "action") as "definition" | "references" | "hover"
    const file = requireString(input, "file")
    const line = input.line as number
    const character = input.character as number
    const absoluteFile = await resolveWorkspacePath(context.rootDir, context.rootDir, file, context, "LspNavigation")
    const relativeFile = toWorkspaceRelative(context.rootDir, absoluteFile)
    const fileUri = pathToFileURL(absoluteFile).href
    const client = await getSharedLspClient(context.rootDir)

    let result: unknown
    switch (action) {
      case "definition":
        result = await client.getDefinition(relativeFile, line, character)
        break
      case "references":
        result = await client.getReferences(relativeFile, line, character)
        break
      case "hover":
        result = await client.getHover(relativeFile, line, character)
        break
    }

    return {
      action,
      file: relativeFile,
      uri: fileUri,
      position: { line, character },
      result,
    }
  },
}

export const mcpTools: ToolDefinition[] = [
{
  name: "Mcp",
  aliases: ["ListMcpResourcesTool", "mcp_list_resources", "ReadMcpResourceTool", "mcp_read_resource", "McpInvokeTool", "mcp_invoke"],
  permissionTier: "edit",
  isMcp: true,
  isOpenWorld: true,
  description: "MCP server access. action=list_resources|read_resource|invoke.",
  inputSchema: {
    type: "object",
    properties: {
      action: { type: "string", enum: ["list_resources", "read_resource", "invoke"] },
      server: { type: "string" },
      uri: { type: "string" },
      tool: { type: "string" },
      arguments: { type: "object" },
    },
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    const invoked = context.invokedAs ?? "Mcp"
    const action = resolveMcpAction(invoked, input as Record<string, unknown>)
    const legacyName = MCP_ACTION_LEGACY[action]
    if (!legacyName) return formatToolError(`Unknown MCP action: ${action}`)
    return runLegacyMcpTool(legacyName, input as Record<string, unknown>, context)
  },
},
  lspQueryTool,
]
