// Auto-generated by scripts/split_registry.py — do not edit manually.
// Domain: media (14 tools)

import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs"

import {
  randomUUID,
} from "node:crypto"

import {
  join,
  resolve,
} from "node:path"

import {
  TTS_RESPONSE_FORMATS,
  emptyInputSchema,
  formatToolError,
  inferExtensionFromFormat,
  optionalNumber,
  optionalString,
  requireString,
  resolveTelegramDownload,
  sanitizeFilenameSegment,
} from "../internal.ts"

import {
  deployManagedTtsContainer,
  getManagedTtsBaseUrl,
  getManagedTtsStatus,
  listManagedTtsContainers,
  normalizeTtsConfig,
  removeManagedTtsContainer,
  stopManagedTtsContainer,
} from "../../tts/managed.ts"

import {
  readModelSettings,
} from "../../runtime/modelConfig.ts"

import {
  MONOLITO_ROOT,
} from "../../system/root.ts"

import {
  readChannelsConfig,
  writeChannelsConfig,
} from "../../channels/config.ts"

import {
  deployManagedSttContainer,
  getManagedSttBaseUrl,
  getManagedSttStatus,
  listManagedSttContainers,
  normalizeSttConfig,
  removeManagedSttContainer,
  stopManagedSttContainer,
  transcribeManagedAudioFile,
} from "../../stt/managed.ts"

import {
  getActiveProfile,
} from "../../runtime/modelRegistry.ts"

import {
  resolveGrokAccessToken,
} from "../../runtime/providers/grokAuth.ts"

import {
  ensureDirs,
} from "../../ipc/protocol.ts"

import type { ToolDefinition } from "../registry.ts"

export const mediaTools: ToolDefinition[] = [
{
  name: "SttServiceStatus",
  aliases: ["stt_service_status"],
  permissionTier: "read",
  description: "Show the status of the managed local speech-to-text service container.",
  inputSchema: emptyInputSchema,
  concurrencySafe: true,
  async run() {
    const config = readChannelsConfig()
    const stt = normalizeSttConfig(config.stt)
    const status = await getManagedSttStatus(stt)
    return {
      managed: stt.managed,
      auto_deploy: stt.autoDeploy,
      auto_transcribe: stt.autoTranscribe,
      status,
      base_url: getManagedSttBaseUrl(stt),
      container_name: stt.containerName,
      image: stt.image,
      port: stt.port,
      engine: stt.engine,
      model: stt.model,
    }
  },
},

{
  name: "SttServiceDeploy",
  aliases: ["stt_service_deploy"],
  permissionTier: "edit",
  description: "Deploy or restart the managed local speech-to-text service container using Docker. Cleans conflicting legacy Whisper containers first.",
  inputSchema: emptyInputSchema,
  concurrencySafe: false,
  async run() {
    const config = readChannelsConfig()
    const stt = normalizeSttConfig(config.stt)
    return await deployManagedSttContainer(stt)
  },
},

{
  name: "SttServiceStop",
  aliases: ["stt_service_stop"],
  permissionTier: "edit",
  description: "Stop the managed local speech-to-text service container without deleting it.",
  inputSchema: emptyInputSchema,
  concurrencySafe: false,
  async run() {
    const config = readChannelsConfig()
    const stt = normalizeSttConfig(config.stt)
    return await stopManagedSttContainer(stt)
  },
},

{
  name: "SttServiceRemove",
  aliases: ["stt_service_remove"],
  permissionTier: "edit",
  description: "Remove the managed local speech-to-text service container and conflicting legacy Whisper containers when found.",
  inputSchema: emptyInputSchema,
  concurrencySafe: false,
  async run() {
    const config = readChannelsConfig()
    const stt = normalizeSttConfig(config.stt)
    return await removeManagedSttContainer(stt)
  },
},

{
  name: "SttServiceList",
  aliases: ["stt_service_list"],
  permissionTier: "read",
  description: "List detected local speech-to-text service containers related to the managed image or container name, including legacy Whisper containers.",
  inputSchema: emptyInputSchema,
  concurrencySafe: true,
  async run() {
    const config = readChannelsConfig()
    const stt = normalizeSttConfig(config.stt)
    return { message: await listManagedSttContainers(stt) }
  },
},

{
  name: "TranscribeAudio",
  aliases: ["transcribe_audio"],
  permissionTier: "edit",
  description: "Transcribe a local audio file using the managed speech-to-text backend. Deploys the service automatically when configured.",
  inputSchema: {
    type: "object",
    properties: {
      path: { type: "string", description: "Local path to the audio file to transcribe." },
    },
    required: ["path"],
    additionalProperties: false,
  },
  concurrencySafe: false,
  validate: input => typeof input.path === "string" && input.path.length > 0 ? null : "path must be a non-empty string",
  async run(input) {
    const path = requireString(input, "path")
    const config = readChannelsConfig()
    const stt = normalizeSttConfig(config.stt)
    if (stt.managed && stt.autoDeploy) {
      const deploy = await deployManagedSttContainer(stt)
      if (!deploy.ok) return formatToolError(deploy.message)
    }
    const result = await transcribeManagedAudioFile(path, stt)
    if (!result.ok) return formatToolError(result.error ?? "STT transcription failed")
    return result
  },
},

{
  name: "TtsServiceStatus",
  aliases: ["tts_service_status"],
  permissionTier: "read",
  description: "Show the status of the managed local TTS service container.",
  inputSchema: emptyInputSchema,
  concurrencySafe: true,
  async run() {
    const config = readChannelsConfig()
    const tts = normalizeTtsConfig(config.tts)
    const status = await getManagedTtsStatus(tts)
    return {
      managed: tts.managed,
      auto_deploy: tts.autoDeploy,
      status,
      base_url: getManagedTtsBaseUrl(tts),
      container_name: tts.containerName,
      image: tts.image,
      port: tts.port,
    }
  },
},

{
  name: "TtsServiceDeploy",
  aliases: ["tts_service_deploy"],
  permissionTier: "edit",
  description: "Deploy or restart the managed local TTS service container using Docker. Cleans conflicting legacy OpenAI Edge TTS containers first. If this succeeds, GenerateSpeech can use the managed service without a base_url override.",
  inputSchema: emptyInputSchema,
  concurrencySafe: false,
  async run() {
    const config = readChannelsConfig()
    const tts = normalizeTtsConfig(config.tts)
    const result = await deployManagedTtsContainer(tts)
    if (result.ok) {
      writeChannelsConfig({
        ...config,
        tts: {
          ...config.tts,
          managed: true,
          autoDeploy: true,
          baseUrl: result.baseUrl,
          apiKey: tts.apiKey,
          voice: tts.voice,
          model: tts.model,
          responseFormat: tts.responseFormat,
          speed: tts.speed,
          port: tts.port,
          image: tts.image,
          containerName: tts.containerName,
        },
      })
    }
    return result
  },
},

{
  name: "TtsServiceStop",
  aliases: ["tts_service_stop"],
  permissionTier: "edit",
  description: "Stop the managed local TTS service container without deleting it.",
  inputSchema: emptyInputSchema,
  concurrencySafe: false,
  async run() {
    const config = readChannelsConfig()
    const tts = normalizeTtsConfig(config.tts)
    return await stopManagedTtsContainer(tts)
  },
},

{
  name: "TtsServiceRemove",
  aliases: ["tts_service_remove"],
  permissionTier: "edit",
  description: "Remove the managed local TTS service container. Also removes conflicting legacy OpenAI Edge TTS containers when found.",
  inputSchema: emptyInputSchema,
  concurrencySafe: false,
  async run() {
    const config = readChannelsConfig()
    const tts = normalizeTtsConfig(config.tts)
    return await removeManagedTtsContainer(tts)
  },
},

{
  name: "TtsServiceList",
  aliases: ["tts_service_list"],
  permissionTier: "read",
  description: "List detected local TTS service containers related to the managed image or container name, including legacy OpenAI Edge TTS containers such as tts-edge.",
  inputSchema: emptyInputSchema,
  concurrencySafe: true,
  async run() {
    const config = readChannelsConfig()
    const tts = normalizeTtsConfig(config.tts)
    return { message: await listManagedTtsContainers(tts) }
  },
},

{
  name: "GenerateSpeech",
  aliases: ["generate_speech", "tts_generate"],
  permissionTier: "edit",
  description: "Generate a speech audio file with the configured OpenAI-compatible TTS backend and save it to Monolito scratchpad storage. For Telegram audio requests, call this first, then send the returned local_path with TelegramSendAudio or TelegramSendVoice before claiming the audio was sent.",
  inputSchema: {
    type: "object",
    properties: {
      text: { type: "string", description: "The text to synthesize into speech." },
      base_url: { type: "string", description: "Optional TTS base URL override. The tool will call <base_url>/v1/audio/speech." },
      api_key: { type: "string", description: "Optional TTS API key override." },
      voice: { type: "string", description: "Optional voice override, for example es-AR-ElenaNeural." },
      model: { type: "string", description: "Optional TTS model override, for example tts-1." },
      response_format: { type: "string", enum: ["mp3", "opus", "aac", "flac", "wav", "pcm"], description: "Optional audio format override." },
      speed: { type: "number", description: "Optional playback speed override. Typical range 0.25 to 4.0." },
      filename: { type: "string", description: "Optional filename without directory. Saved under Monolito scratchpad." },
    },
    required: ["text"],
    additionalProperties: false,
  },
  concurrencySafe: false,
  validate: input => {
    if (typeof input.text !== "string" || input.text.trim().length === 0) return "text must be a non-empty string"
    const speed = optionalNumber(input, "speed")
    if (speed !== undefined && (speed <= 0 || speed > 4)) return "speed must be between 0 and 4"
    const format = optionalString(input, "response_format")
    if (format && !TTS_RESPONSE_FORMATS.has(format)) return "response_format must be one of: mp3, opus, aac, flac, wav, pcm"
    return null
  },
  async run(input, context) {
    const text = requireString(input, "text")
    const config = readChannelsConfig()
    const tts = normalizeTtsConfig(config.tts)
    let baseUrl = (optionalString(input, "base_url") ?? tts.baseUrl).replace(/\/+$/g, "")
    if (tts.managed) {
      baseUrl = getManagedTtsBaseUrl(tts)
      if (tts.autoDeploy) {
        const deploy = await deployManagedTtsContainer(tts)
        if (!deploy.ok) return formatToolError(`TTS managed service unavailable and auto-deploy failed: ${deploy.message}`)
      }
    }
    if (!baseUrl && await getManagedTtsStatus(tts) === "running") {
      baseUrl = getManagedTtsBaseUrl(tts)
    }
    if (!baseUrl) {
      return formatToolError("TTS no está configurado. Usá /config set tts_base_url <url> para configurar una API TTS (como la de MiniMax) o activá managed TTS con /config set tts_managed true.")
    }

    const isTtsApiConfigured = baseUrl.length > 0 && (tts.apiKey || optionalString(input, "api_key"))
    if (!isTtsApiConfigured && !tts.managed) {
      return formatToolError("TTS no está configurado. Usá /config set tts_base_url <url> para configurar una API TTS o habilitá managed TTS.")
    }

    const voice = optionalString(input, "voice") ?? tts.voice
    const model = optionalString(input, "model") ?? tts.model
    const responseFormat = optionalString(input, "response_format") ?? tts.responseFormat
    const speed = optionalNumber(input, "speed") ?? tts.speed
    const apiKey = optionalString(input, "api_key") ?? tts.apiKey
    const paths = ensureDirs(context.rootDir, context.profileId)
    const speechDir = join(paths.scratchpadDir, "tts")
    mkdirSync(speechDir, { recursive: true })

    const extension = inferExtensionFromFormat(responseFormat)
    const requestedFilename = optionalString(input, "filename")
    const filename = requestedFilename
      ? sanitizeFilenameSegment(requestedFilename.replace(/\.[^.]+$/, ""))
      : `${sanitizeFilenameSegment(voice)}-${randomUUID().slice(0, 8)}`
    const localPath = join(speechDir, `${filename}.${extension}`)

    const headers: Record<string, string> = { "Content-Type": "application/json" }
    if (apiKey) headers.Authorization = `Bearer ${apiKey}`
    const response = await fetch(`${baseUrl}/v1/audio/speech`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        model,
        input: text,
        voice,
        response_format: responseFormat,
        speed,
      }),
      signal: AbortSignal.timeout(60_000),
    })

    if (!response.ok) {
      const body = await response.text().catch(() => "")
      return formatToolError(`TTS request failed: HTTP ${response.status}${body ? ` - ${body.slice(0, 400)}` : ""}`)
    }

    const buffer = Buffer.from(await response.arrayBuffer())
    writeFileSync(localPath, buffer)

    return {
      ok: true,
      local_path: localPath,
      bytes: buffer.length,
      voice,
      model,
      response_format: responseFormat,
      speed,
    }
  },
},

{
  name: "VisionAnalyze",
  permissionTier: "read",
  description: "Analiza una imagen desde una URL o un path local utilizando la API de visión del modelo de nube activo (Anthropic, OpenAI, Grok). Rápido (~3-5s). Es la herramienta preferida para análisis visual directo. Si la API de nube falla o devuelve resultado vacío, ejecuta fallback automático al motor de visión local. Retorna { description, local_path }. Usá esta herramienta directamente cuando el usuario pide describir, analizar o verificar el contenido de una imagen — no es necesario delegar a un sub-agente para casos simples.",
  inputSchema: {
    type: "object",
    properties: {
      url: { type: "string", description: "URL de la imagen a descargar y analizar." },
      path: { type: "string", description: "Ruta local del archivo de imagen a analizar." },
      file_id: { type: "string", description: "Telegram file_id. Si se proporciona, descarga la imagen desde los servidores de Telegram (útil si la URL de origen bloquea descargas directas)." },
    },
    additionalProperties: false,
  },
  concurrencySafe: true,
  validate: input => {
    if (typeof input.url !== "string" && typeof input.path !== "string" && typeof input.file_id !== "string") {
      return "Debes proporcionar 'url', 'path' o 'file_id' como string."
    }
    return null
  },
  async run(input, context) {
    const url = optionalString(input, "url")
    const pathArg = optionalString(input, "path")
    const fileId = optionalString(input, "file_id")
    
    let buffer: Buffer
    let mediaType = "image/jpeg"
    let localPath = ""
    
    if (fileId) {
      const config = readChannelsConfig()
      if (!config.telegram?.enabled || !config.telegram.token) {
        return formatToolError("Telegram no está configurado. file_id requiere Telegram activo.")
      }
      try {
        const download = await resolveTelegramDownload(config.telegram.token, fileId, context.rootDir)
        if (!download.ok) {
          return formatToolError(`Error descargando desde Telegram: ${JSON.stringify(download)}`)
        }
        buffer = readFileSync(download.local_path)
        localPath = download.local_path
        
        if (localPath.toLowerCase().endsWith(".png")) mediaType = "image/png"
        else if (localPath.toLowerCase().endsWith(".webp")) mediaType = "image/webp"
        else if (localPath.toLowerCase().endsWith(".gif")) mediaType = "image/gif"
      } catch (error: any) {
        return formatToolError(`Error descargando desde Telegram: ${error.message || error}`)
      }
    } else if (url) {
      if (url.toLowerCase().endsWith(".png")) mediaType = "image/png"
      else if (url.toLowerCase().endsWith(".webp")) mediaType = "image/webp"
      else if (url.toLowerCase().endsWith(".gif")) mediaType = "image/gif"
      
      const response = await fetch(url, {
        headers: {
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
          "Accept": "image/*,*/*",
        },
        signal: context.abortSignal,
      })
      if (!response.ok) return formatToolError(`Error descargando imagen desde URL: HTTP ${response.status}`)
      buffer = Buffer.from(await response.arrayBuffer())

      const scratchpadDir = join(MONOLITO_ROOT, "workspace", "scratchpad")
      mkdirSync(scratchpadDir, { recursive: true })
      localPath = join(scratchpadDir, `vision-${randomUUID()}.${mediaType === "image/png" ? "png" : "jpg"}`)
      writeFileSync(localPath, buffer)
    } else if (pathArg) {
      if (pathArg.toLowerCase().endsWith(".png")) mediaType = "image/png"
      else if (pathArg.toLowerCase().endsWith(".webp")) mediaType = "image/webp"
      else if (pathArg.toLowerCase().endsWith(".gif")) mediaType = "image/gif"
      
      const absolutePath = resolve(context.cwd, pathArg)
      if (!existsSync(absolutePath)) return formatToolError(`Archivo no encontrado: ${absolutePath}`)
      buffer = readFileSync(absolutePath)
      localPath = absolutePath
    } else {
      return formatToolError("Debes proporcionar 'url', 'path' o 'file_id'.")
    }

    const base64Image = buffer.toString("base64")
    
    const activeProfile = getActiveProfile()
    let provider = "anthropic_compatible"
    let baseUrl = ""
    let apiKey = ""
    let model = ""

    if (activeProfile) {
      provider = activeProfile.provider
      baseUrl = activeProfile.baseUrl.trim().replace(/\/+$/, "")
      apiKey = activeProfile.apiKey.trim()
      model = activeProfile.model.trim()
    } else {
      const settings = readModelSettings()
      provider = "anthropic_compatible"
      baseUrl = settings.env.ANTHROPIC_BASE_URL.trim().replace(/\/+$/, "")
      apiKey = settings.env.ANTHROPIC_AUTH_TOKEN.trim()
      model = settings.env.ANTHROPIC_MODEL.trim()
    }

    if (provider === "xai-oauth") {
      try {
        const { resolveGrokAccessToken } = await import("../../runtime/providers/grokAuth.ts")
        apiKey = await resolveGrokAccessToken()
      } catch (err) {
        context.logger?.error(`Error resolving Grok access token in VisionAnalyze: ${err}`)
      }
    }

    if (provider === "anthropic_compatible" || provider === "minimax") {
      const cleanBaseUrl = baseUrl.replace(/\/v1\/messages\/?$/, "")
      const endpoint = cleanBaseUrl ? `${cleanBaseUrl}/v1/messages` : "https://api.anthropic.com/v1/messages"
      
      const response = await fetch(endpoint, {
        method: "POST",
        headers: {
          "content-type": "application/json",
          "x-api-key": apiKey || "not-needed",
          "anthropic-version": "2023-06-01"
        },
        body: JSON.stringify({
          model: model,
          max_tokens: 1000,
          messages: [
            {
              role: "user",
              content: [
                {
                  type: "image",
                  source: {
                    type: "base64",
                    media_type: mediaType,
                    data: base64Image
                  }
                },
                {
                  type: "text",
                  text: "Describe exactly what is in this image in detail."
                }
              ]
            }
          ]
        }),
        signal: context.abortSignal
      })

      if (!response.ok) {
        const text = await response.text()
        return formatToolError(`Anthropic Vision API failed (${response.status}): ${text}`)
      }

      const data = await response.json() as { content?: Array<{ text?: string }>; choices?: Array<{ message?: { content?: string } }> }
      const description = data.content?.[0]?.text || ""
      if (!description) {
        return formatToolError("Vision API returned an empty description. The active model may not support image inputs, or the image was rejected by the provider. Switch to a vision-capable model and try again.")
      }
      return { ok: true, description, local_path: localPath }
    } else {
      const endpoint = baseUrl ? `${baseUrl}/v1/chat/completions` : "https://api.openai.com/v1/chat/completions"
      
      const response = await fetch(endpoint, {
        method: "POST",
        headers: {
          "content-type": "application/json",
          "authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify({
          model: model,
          max_tokens: 1000,
          messages: [
            {
              role: "user",
              content: [
                {
                  type: "image_url",
                  image_url: {
                    url: `data:${mediaType};base64,${base64Image}`
                  }
                },
                {
                  type: "text",
                  text: "Describe exactly what is in this image in detail."
                }
              ]
            }
          ]
        }),
        signal: context.abortSignal
      })

      if (!response.ok) {
        const text = await response.text()
        return formatToolError(`OpenAI Vision API failed (${response.status}): ${text}`)
      }

      const data = await response.json() as { content?: Array<{ text?: string }>; choices?: Array<{ message?: { content?: string } }> }
      const description = data.choices?.[0]?.message?.content || ""
      if (!description) {
        return formatToolError("Vision API returned an empty description. The active model may not support image inputs, or the image was rejected by the provider. Switch to a vision-capable model and try again.")
      }
      return { ok: true, description, local_path: localPath }
    }
  },
},

{
  name: "GenerateImage",
  permissionTier: "edit",
  description: "Genera una imagen a partir de una descripción detallada (prompt). Soporta xAI Grok (grok-imagine-image) por defecto si la sesión está autenticada, o DALL-E si está configurado.",
  inputSchema: {
    type: "object",
    properties: {
      prompt: { type: "string", description: "Descripción detallada de la imagen a generar (ej: 'Un gato de estilo cyberpunk con ojos de neón brillante')." },
      aspect_ratio: { type: "string", enum: ["1:1", "16:9", "9:16", "4:3", "3:4", "3:2", "2:3"], description: "Relación de aspecto de la imagen generada. Por defecto es '1:1'." },
      quality: { type: "string", enum: ["standard", "quality"], description: "Calidad de generación. Por defecto es 'standard'. 'quality' produce mayor nivel de detalle (solo soportado por Grok)." },
      provider: { type: "string", enum: ["xai", "openai"], description: "Forzar un proveedor específico. Por defecto detecta automáticamente basándose en las credenciales del perfil activo." }
    },
    required: ["prompt"],
    additionalProperties: false
  },
  concurrencySafe: true,
  validate: input => {
    if (typeof input.prompt !== "string" || input.prompt.trim().length === 0) {
      return "El prompt de generación no puede estar vacío."
    }
    return null
  },
  async run(input, context) {
    try {
      const prompt = requireString(input, "prompt")
      const aspect_ratio = optionalString(input, "aspect_ratio") || "1:1"
      const quality = optionalString(input, "quality") || "standard"
      const providerOverride = optionalString(input, "provider")

      // 1. Resolve Provider and Credentials
      let provider = "xai"
      let baseUrl = "https://api.x.ai/v1"
      let apiKey = ""
      let model = ""

      const activeProfile = getActiveProfile()

      if (providerOverride === "xai") {
        provider = "xai"
      } else if (providerOverride === "openai") {
        provider = "openai"
      } else {
        // Auto-detect
        if (activeProfile && ((activeProfile.provider as string) === "xai-oauth" || (activeProfile.provider as string) === "xai" || activeProfile.baseUrl.includes("x.ai"))) {
          provider = "xai"
        } else {
          const { loadGrokTokens } = await import("../../runtime/providers/grokAuth.ts")
          const hasGrokTokens = await loadGrokTokens().then(t => !!t).catch(() => false)
          const hasGrokEnv = !!process.env.XAI_API_KEY
          if (hasGrokTokens || hasGrokEnv) {
            provider = "xai"
          } else if (activeProfile && (activeProfile.provider === "openai_compatible" || activeProfile.provider === "anthropic_compatible")) {
            provider = "openai"
          } else {
            provider = "xai"
          }
        }
      }

      // Resolve credentials
      if (provider === "xai") {
        baseUrl = "https://api.x.ai/v1"
        if (activeProfile && ((activeProfile.provider as string) === "xai-oauth" || (activeProfile.provider as string) === "xai")) {
          apiKey = activeProfile.apiKey.trim()
          if ((activeProfile.provider as string) === "xai-oauth") {
            try {
              const { resolveGrokAccessToken } = await import("../../runtime/providers/grokAuth.ts")
              apiKey = await resolveGrokAccessToken()
            } catch (err) {
              context.logger?.error(`Error resolving Grok access token: ${err}`)
            }
          }
        } else {
          if (process.env.XAI_API_KEY) {
            apiKey = process.env.XAI_API_KEY.trim()
          } else {
            try {
              const { resolveGrokAccessToken } = await import("../../runtime/providers/grokAuth.ts")
              apiKey = await resolveGrokAccessToken()
            } catch (err) {
              // Ignore, we fail later
            }
          }
        }
        model = quality === "quality" ? "grok-imagine-image-quality" : "grok-imagine-image"
      } else {
        // OpenAI
        if (activeProfile) {
          baseUrl = activeProfile.baseUrl.trim().replace(/\/+$/, "")
          apiKey = activeProfile.apiKey.trim()
          model = activeProfile.model.trim() || "dall-e-3"
        } else {
          baseUrl = process.env.OPENAI_BASE_URL?.trim() || "https://api.openai.com/v1"
          apiKey = process.env.OPENAI_API_KEY?.trim() || ""
          model = "dall-e-3"
        }
      }

      if (!apiKey) {
        return formatToolError(
          `No se encontraron credenciales válidas para el proveedor '${provider}'. ` +
          `Por favor, configura xAI Grok OAuth ejecutando 'monolito auth xai-oauth' en tu terminal, ` +
          `o configura la variable de entorno XAI_API_KEY / OPENAI_API_KEY.`
        )
      }

      // 2. Prepare Endpoint and Payload
      let endpoint = `${baseUrl.replace(/\/+$/, "")}/images/generations`
      let payload: Record<string, any> = {}

      if (provider === "xai" || baseUrl.includes("x.ai")) {
        payload = {
          model: model,
          prompt: prompt,
          aspect_ratio: aspect_ratio,
          resolution: "1k"
        }
      } else {
        let size = "1024x1024"
        if (aspect_ratio === "16:9") {
          size = "1792x1024"
        } else if (aspect_ratio === "9:16") {
          size = "1024x1792"
        } else if (aspect_ratio === "4:3") {
          size = "1024x768"
        } else if (aspect_ratio === "3:4") {
          size = "768x1024"
        }
        payload = {
          model: model || "dall-e-3",
          prompt: prompt,
          size: size,
          n: 1
        }
      }

      context.logger?.info(`Iniciando generación de imagen con '${provider}' y modelo '${model}'...`)

      // 3. Request
      const response = await fetch(endpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify(payload),
        signal: context.abortSignal
      })

      if (!response.ok) {
        const errorText = await response.text()
        return formatToolError(`La API de generación de imágenes falló (${response.status}): ${errorText}`)
      }

      const result = await response.json() as { data?: Array<{ b64_json?: string; url?: string }> }
      const data = result.data || []
      if (data.length === 0) {
        return formatToolError("La API no devolvió ninguna imagen en la respuesta.")
      }

      const first = data[0]
      const b64 = first.b64_json
      const imageUrl = first.url

      // 4. Save Locally
      const scratchpadDir = join(MONOLITO_ROOT, "workspace", "scratchpad")
      mkdirSync(scratchpadDir, { recursive: true })

      let localPath = ""
      let isPng = true

      if (b64) {
        const buffer = Buffer.from(b64, "base64")
        localPath = join(scratchpadDir, `img-gen-${randomUUID()}.png`)
        writeFileSync(localPath, buffer)
      } else if (imageUrl) {
        const imgResponse = await fetch(imageUrl, { signal: context.abortSignal })
        if (!imgResponse.ok) {
          return formatToolError(`No se pudo descargar la imagen generada desde la URL: HTTP ${imgResponse.status}`)
        }
        const buffer = Buffer.from(await imgResponse.arrayBuffer())
        if (imageUrl.toLowerCase().endsWith(".jpg") || imageUrl.toLowerCase().endsWith(".jpeg")) {
          isPng = false
        }
        localPath = join(scratchpadDir, `img-gen-${randomUUID()}.${isPng ? "png" : "jpg"}`)
        writeFileSync(localPath, buffer)
      } else {
        return formatToolError("La respuesta no contiene ni 'b64_json' ni 'url'.")
      }

      context.logger?.info(`Imagen generada exitosamente en: ${localPath}`)

      return JSON.stringify({
        success: true,
        local_path: localPath,
        url: imageUrl || null,
        provider: provider,
        model: model,
        prompt: prompt,
        aspect_ratio: aspect_ratio
      }, null, 2)

    } catch (err: any) {
      return formatToolError(`Error durante la generación de la imagen: ${err.message}`)
    }
  }
},

]
