// Auto-generated by scripts/split_registry.py — do not edit manually.
// Domain: media (14 tools)

import {
  existsSync,
  mkdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs"

import {
  randomUUID,
} from "node:crypto"

import {
  join,
  resolve,
} from "node:path"

import {
  TTS_RESPONSE_FORMATS,
  emptyInputSchema,
  execFileAsync,
  formatToolError,
  inferExtensionFromFormat,
  multipartUploadFile,
  optionalNumber,
  optionalString,
  requireString,
  resolveTelegramDownload,
  sanitizeFilenameSegment,
} from "../internal.ts"

import {
  normalizeTtsConfig,
  readChannelsConfig,
  writeChannelsConfig,
} from "../../channels/config.ts"

import {
  readConfigWing,
} from "../../session/store.ts"

import {
  readModelSettings,
} from "../../runtime/modelConfig.ts"

import {
  MONOLITO_ROOT,
} from "../../system/root.ts"

import {
  appendActionLog,
} from "../../session/store.ts"

import {
  deployManagedSttContainer,
  getManagedSttBaseUrl,
  getManagedSttStatus,
  listManagedSttContainers,
  normalizeSttConfig,
  removeManagedSttContainer,
  stopManagedSttContainer,
  transcribeManagedAudioFile,
} from "../../stt/managed.ts"

import {
  getActiveProfile,
} from "../../runtime/modelRegistry.ts"

import {
  resolveGrokAccessToken,
} from "../../runtime/providers/grokAuth.ts"

import {
  ensureDirs,
} from "../../ipc/protocol.ts"

import type { ToolDefinition } from "../registry.ts"

let lastSuccessfulScreenshotCmd: string | null = null;

export const mediaTools: ToolDefinition[] = [
{
  name: "SttServiceStatus",
  aliases: ["stt_service_status"],
  permissionTier: "read",
  description: "Show the status of the managed local speech-to-text service container.",
  inputSchema: emptyInputSchema,
  concurrencySafe: true,
  async run() {
    const config = readChannelsConfig()
    const stt = normalizeSttConfig(config.stt)
    const status = await getManagedSttStatus(stt)
    return {
      managed: stt.managed,
      auto_deploy: stt.autoDeploy,
      auto_transcribe: stt.autoTranscribe,
      status,
      base_url: getManagedSttBaseUrl(stt),
      container_name: stt.containerName,
      image: stt.image,
      port: stt.port,
      engine: stt.engine,
      model: stt.model,
    }
  },
},

{
  name: "SttServiceDeploy",
  aliases: ["stt_service_deploy"],
  permissionTier: "edit",
  description: "Deploy or restart the managed local speech-to-text service container using Docker. Cleans conflicting legacy Whisper containers first.",
  inputSchema: emptyInputSchema,
  concurrencySafe: false,
  async run() {
    const config = readChannelsConfig()
    const stt = normalizeSttConfig(config.stt)
    return await deployManagedSttContainer(stt)
  },
},

{
  name: "SttServiceStop",
  aliases: ["stt_service_stop"],
  permissionTier: "edit",
  description: "Stop the managed local speech-to-text service container without deleting it.",
  inputSchema: emptyInputSchema,
  concurrencySafe: false,
  async run() {
    const config = readChannelsConfig()
    const stt = normalizeSttConfig(config.stt)
    return await stopManagedSttContainer(stt)
  },
},

{
  name: "SttServiceRemove",
  aliases: ["stt_service_remove"],
  permissionTier: "edit",
  description: "Remove the managed local speech-to-text service container and conflicting legacy Whisper containers when found.",
  inputSchema: emptyInputSchema,
  concurrencySafe: false,
  async run() {
    const config = readChannelsConfig()
    const stt = normalizeSttConfig(config.stt)
    return await removeManagedSttContainer(stt)
  },
},

{
  name: "SttServiceList",
  aliases: ["stt_service_list"],
  permissionTier: "read",
  description: "List detected local speech-to-text service containers related to the managed image or container name, including legacy Whisper containers.",
  inputSchema: emptyInputSchema,
  concurrencySafe: true,
  async run() {
    const config = readChannelsConfig()
    const stt = normalizeSttConfig(config.stt)
    return { message: await listManagedSttContainers(stt) }
  },
},

{
  name: "TranscribeAudio",
  aliases: ["transcribe_audio"],
  permissionTier: "edit",
  description: "Transcribe a local audio file using the managed speech-to-text backend. Deploys the service automatically when configured.",
  inputSchema: {
    type: "object",
    properties: {
      path: { type: "string", description: "Local path to the audio file to transcribe." },
    },
    required: ["path"],
    additionalProperties: false,
  },
  concurrencySafe: false,
  validate: input => typeof input.path === "string" && input.path.length > 0 ? null : "path must be a non-empty string",
  async run(input) {
    const path = requireString(input, "path")
    const config = readChannelsConfig()
    const stt = normalizeSttConfig(config.stt)
    if (stt.managed && stt.autoDeploy) {
      const deploy = await deployManagedSttContainer(stt)
      if (!deploy.ok) return formatToolError(deploy.message)
    }
    const result = await transcribeManagedAudioFile(path, stt)
    if (!result.ok) return formatToolError(result.error ?? "STT transcription failed")
    return result
  },
},

{
  name: "GenerateSpeech",
  aliases: ["generate_speech", "tts_generate"],
  permissionTier: "edit",
  description: "Generate a speech audio file with the configured TTS backend and save it to Monolito scratchpad storage. Supports MiniMax via /v1/t2a_v2 and any OpenAI-compatible hosted provider via /v1/audio/speech (e.g. api.openai.com). If tts.provider is 'minimax' or the voice alias is in tts.clonedVoices, MiniMax is used automatically. The previous managed-local-Docker TTS backend was removed. For Telegram audio requests, call this first, then send the returned local_path with TelegramSendAudio or TelegramSendVoice before claiming the audio was sent.",
  inputSchema: {
    type: "object",
    properties: {
      text: { type: "string", description: "The text to synthesize into speech." },
      provider: { type: "string", enum: ["openai", "minimax"], description: "TTS provider override. Default detecta por tts.provider o baseUrl. Si el voice es un alias en tts.clonedVoices, se fuerza minimax." },
      base_url: { type: "string", description: "Optional TTS base URL override. The tool will call <base_url>/v1/audio/speech (OpenAI) or <base_url>/v1/t2a_v2 (MiniMax)." },
      api_key: { type: "string", description: "Optional TTS API key override." },
      voice: { type: "string", description: "Optional voice override. For MiniMax acepta un alias (resuelto via tts.clonedVoices) o un voice_id directo. Para OpenAI-compatible, ej: es-AR-ElenaNeural, alloy, nova." },
      model: { type: "string", description: "Optional TTS model override. OpenAI: ej tts-1. MiniMax: ej speech-2.8-hd." },
      response_format: { type: "string", enum: ["mp3", "opus", "aac", "flac", "wav", "pcm"], description: "Optional audio format override." },
      speed: { type: "number", description: "Optional playback speed override. OpenAI: 0.25-4.0. MiniMax: 0.5-2.0 (se clampea automaticamente)." },
      filename: { type: "string", description: "Optional filename without directory. Saved under Monolito scratchpad." },
      language_boost: { type: "string", description: "Optional language boost override for MiniMax (e.g. 'Spanish', 'English', 'Chinese', 'Portuguese', 'auto')." },
    },
    required: ["text"],
    additionalProperties: false,
  },
  concurrencySafe: false,
  validate: input => {
    if (typeof input.text !== "string" || input.text.trim().length === 0) return "text must be a non-empty string"
    const speed = optionalNumber(input, "speed")
    if (speed !== undefined && (speed <= 0 || speed > 4)) return "speed must be between 0 and 4"
    const format = optionalString(input, "response_format")
    if (format && !TTS_RESPONSE_FORMATS.has(format)) return "response_format must be one of: mp3, opus, aac, flac, wav, pcm"
    const provider = optionalString(input, "provider")
    if (provider && provider !== "openai" && provider !== "minimax") {
      return "provider must be 'openai' or 'minimax'"
    }
    return null
  },
  async run(input, context) {
    const text = requireString(input, "text")
    const config = readChannelsConfig()
    const tts = normalizeTtsConfig(config.tts)
    const inputVoice = optionalString(input, "voice")
    // Resolucion automatica de provider: si el voice es un alias de voz clonada, forzar minimax
    let provider = optionalString(input, "provider") as "openai" | "minimax" | undefined
    if (!provider) {
      if (inputVoice && tts.clonedVoices?.[inputVoice]) {
        provider = "minimax"
      } else if (tts.provider === "minimax") {
        provider = "minimax"
      } else if (tts.baseUrl.toLowerCase().includes("minimax.io")) {
        provider = "minimax"
      } else {
        provider = "openai"
      }
    }

    const voice = inputVoice ?? (provider === "minimax" ? tts.defaultClonedVoice || tts.voice : tts.voice)
    const model = optionalString(input, "model") ?? (provider === "minimax" ? (tts.t2aModel || "speech-2.8-hd") : tts.model)
    const responseFormat = optionalString(input, "response_format") ?? tts.responseFormat
    const speed = optionalNumber(input, "speed") ?? tts.speed
    // Resolucion de credenciales para TTS: SIEMPRE MiniMax, independiente del LLM principal.
    // El endpoint /v1/t2a_v2 de MiniMax usa credenciales MiniMax, no las del LLM (Grok/Claude/etc.).
    // Prioridad:
    // 1. input.api_key (override explícito)
    // 2. MINIMAX_API_KEY env var (SIEMPRE primero para TTS)
    // 3. tts.apiKey (config específico de TTS)
    // NUNCA: activeProfile.apiKey (es del LLM, no de TTS)
    // NUNCA: ANTHROPIC_AUTH_TOKEN (es del LLM, no de TTS)
    let apiKey = (optionalString(input, "api_key") ?? "").trim()
    if (!apiKey) {
      const minimaxEnv = (process.env.MINIMAX_API_KEY || "").trim()
      if (minimaxEnv) apiKey = minimaxEnv
    }
    if (!apiKey) apiKey = (tts.apiKey ?? "").trim()
    if (!apiKey) {
      // Buscar credenciales MiniMax en CONF_MODELS (cualquier profile con provider=minimax)
      const modelsWing = readConfigWing(context.rootDir, "CONF_MODELS") as { profiles?: Array<{ provider?: string; apiKey?: string }> } | null
      const minimaxProfile = (modelsWing?.profiles || []).find(p => p.provider === "minimax" && p.apiKey)
      if (minimaxProfile?.apiKey) apiKey = minimaxProfile.apiKey.trim()
    }

    const paths = ensureDirs(context.rootDir, context.profileId)
    const speechDir = join(paths.scratchpadDir, "tts")
    mkdirSync(speechDir, { recursive: true })

    const extension = inferExtensionFromFormat(responseFormat)
    const requestedFilename = optionalString(input, "filename")
    const filename = requestedFilename
      ? sanitizeFilenameSegment(requestedFilename.replace(/\.[^.]+$/, ""))
      : `${sanitizeFilenameSegment(voice || "tts")}-${randomUUID().slice(0, 8)}`
    const localPath = join(speechDir, `${filename}.${extension}`)

    if (provider === "minimax") {
      // Branch MiniMax: /v1/t2a_v2 con body y response custom (hex en data.audio).
      if (!apiKey) {
        return formatToolError("MiniMax TTS requiere MINIMAX_API_KEY o tts.apiKey (credenciales independientes del LLM principal).")
      }
      let baseUrl = ((optionalString(input, "base_url") ?? tts.baseUrl) || "https://api.minimax.io/v1").replace(/\/+$/g, "")
      if (!/\/v\d+$/.test(baseUrl)) baseUrl = `${baseUrl}/v1`
      // Resolver voice: alias -> voice_id
      const resolvedVoice = tts.clonedVoices?.[voice || ""] ?? voice
      if (!resolvedVoice) {
        return formatToolError("MiniMax TTS requiere voice (alias o voice_id). Configurá uno o usá tts.defaultClonedVoice.")
      }
      // MiniMax acepta speed 0.5-2.0. Clampear.
      const speedClamped = Math.max(0.5, Math.min(2.0, speed || 1))
      if (Math.abs(speedClamped - (speed || 1)) > 0.001) {
        context.logger?.warn(`[GenerateSpeech] speed ${speed} fuera de rango MiniMax (0.5-2.0), clampeado a ${speedClamped}`)
      }
      const format = (["mp3", "wav", "pcm"].includes(responseFormat) ? responseFormat : "mp3") as "mp3" | "wav" | "pcm"
      const sampleRate = format === "wav" ? 24000 : 16000
      const audioSetting: Record<string, unknown> = {
        sample_rate: sampleRate,
        format,
      }
      if (format === "mp3") {
        audioSetting.bitrate = 128000
      }
      const languageBoost = optionalString(input, "language_boost") ?? tts.languageBoost
      const body: Record<string, any> = {
        model: model || "speech-2.8-hd",
        text,
        voice_setting: { voice_id: resolvedVoice, speed: speedClamped, vol: 1.0, pitch: 0 },
        audio_setting: audioSetting,
      }
      if (languageBoost) {
        body.language_boost = languageBoost
      }
      const response = await fetch(`${baseUrl}/t2a_v2`, {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
        body: JSON.stringify(body),
        signal: AbortSignal.timeout(60_000),
      })
      if (!response.ok) {
        const errBody = await response.text().catch(() => "")
        return formatToolError(`MiniMax TTS failed: HTTP ${response.status}${errBody ? ` - ${errBody.slice(0, 400)}` : ""}`)
      }
      const respJson = await response.json() as { data?: { audio?: string }; base_resp?: { status_code?: number; status_msg?: string } }
      if (respJson.base_resp?.status_code && respJson.base_resp.status_code !== 0) {
        return formatToolError(`MiniMax TTS rechazado: ${respJson.base_resp.status_msg || respJson.base_resp.status_code}`)
      }
      const hexAudio = respJson.data?.audio
      if (!hexAudio) return formatToolError("MiniMax TTS no devolvio data.audio")
      const buffer = Buffer.from(hexAudio, "hex")
      writeFileSync(localPath, buffer)
      return {
        ok: true,
        provider: "minimax",
        local_path: localPath,
        bytes: buffer.length,
        voice: resolvedVoice,
        voice_alias: tts.clonedVoices?.[voice || ""] ? voice : undefined,
        model: body.model,
        response_format: format,
        speed: speedClamped,
        language_boost: languageBoost || undefined,
      }
    }

    // Branch OpenAI-compatible (hosted providers, default for non-MiniMax).
    let baseUrl = (optionalString(input, "base_url") ?? tts.baseUrl).replace(/\/+$/g, "")
    if (!baseUrl) {
      return formatToolError("TTS OpenAI-compatible no está configurado. Usá /config set tts_base_url <url> (ej. https://api.openai.com/v1) o cambiá a provider='minimax' con tts.apiKey.")
    }

    const isTtsApiConfigured = baseUrl.length > 0 && (apiKey || optionalString(input, "api_key"))
    if (!isTtsApiConfigured) {
      return formatToolError("TTS OpenAI-compatible requiere apiKey. Configurá tts.apiKey con /config set tts_api_key <key> o pasá api_key en el tool call.")
    }

    const headers: Record<string, string> = { "Content-Type": "application/json" }
    if (apiKey) headers.Authorization = `Bearer ${apiKey}`
    const response = await fetch(`${baseUrl}/v1/audio/speech`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        model,
        input: text,
        voice,
        response_format: responseFormat,
        speed,
      }),
      signal: AbortSignal.timeout(60_000),
    })

    if (!response.ok) {
      const body = await response.text().catch(() => "")
      return formatToolError(`TTS request failed: HTTP ${response.status}${body ? ` - ${body.slice(0, 400)}` : ""}`)
    }

    const buffer = Buffer.from(await response.arrayBuffer())
    writeFileSync(localPath, buffer)

    return {
      ok: true,
      provider: "openai",
      local_path: localPath,
      bytes: buffer.length,
      voice,
      model,
      response_format: responseFormat,
      speed,
    }
  },
},

{
  name: "VoiceClone",
  aliases: ["voice_clone"],
  permissionTier: "edit",
  description: "Sube un audio de muestra (mp3/m4a/wav/ogg, 10s-5min, <=20MB) a MiniMax, crea una voz clonada y la persiste en la config de TTS bajo un alias amigable. Permite listar (local y remoto en MiniMax), borrar localmente, purgar en MiniMax, y renombrar. Requiere tts.provider='minimax' y tts.apiKey (o MINIMAX_API_KEY).",
  inputSchema: {
    type: "object",
    properties: {
      action: { type: "string", enum: ["clone", "list", "list_remote", "delete", "purge", "rename", "sync"], description: "Accion a realizar. IMPORTANTE: cuando el usuario pregunte por voces en MiniMax, en el provider, remotas, en la nube, o similares, usá SIEMPRE 'list_remote' (que llama a MiniMax GET /v1/get_voice). 'list' solo lee la config local (CONF_CHANNELS.tts.clonedVoices) y NO muestra lo que está en MiniMax. Las demás acciones: 'clone' (nueva voz), 'delete' (solo local), 'purge' (MiniMax DELETE /v1/delete_voice + local), 'rename' (purge+clone con nuevo alias), 'sync' (sincroniza voces remotas de MiniMax a la config local adoptando voces huérfanas)." },
      alias: { type: "string", description: "Nombre amigable para la voz clonada (ej: 'cristian', 'mia'). Requerido para clone/delete. Solo chars [a-z0-9_-], 1-32 chars." },
      source: {
        type: "object",
        description: "Fuente del audio de muestra. Requerido para clone.",
        properties: {
          type: { type: "string", enum: ["path", "telegram_file_id"] },
          value: { type: "string", description: "Path local absoluto o file_id de Telegram." },
        },
        required: ["type", "value"],
        additionalProperties: false,
      },
      voice_id: { type: "string", description: "voice_id a borrar o purgar. Alternativa a alias para delete/purge." },
      new_alias: { type: "string", description: "Nuevo nombre amigable para la voz clonada (requerido para rename). Solo chars [a-z0-9_-], 1-32 chars." },
      model: { type: "string", description: "Modelo de voice clone. Default: t2aModel de la config (o 'speech-2.8-hd')." },
      text: { type: "string", description: "Texto opcional de muestra que el provider usa para el clone. Default: '' (MiniMax infiere del audio)." },
      set_default: { type: "boolean", description: "Si true, marca este alias como defaultClonedVoice. Default: false." },
    },
    required: ["action"],
    additionalProperties: false,
  },
  sideEffect: true,
  concurrencySafe: false,
  validate: input => {
    const action = input.action
    if (action !== "clone" && action !== "list" && action !== "list_remote" && action !== "delete" && action !== "purge" && action !== "rename" && action !== "sync") {
      return "action must be 'clone', 'list', 'list_remote', 'delete', 'purge', 'rename' or 'sync'"
    }
    if (action === "clone") {
      if (!input.alias || typeof input.alias !== "string") return "alias is required for clone"
      if (!/^[a-z0-9_-]{1,32}$/.test(input.alias)) {
        return "alias debe ser alfanumerico, guion o guion bajo, max 32 chars"
      }
      const src = input.source as { type?: unknown; value?: unknown } | undefined
      if (!src || (src.type !== "path" && src.type !== "telegram_file_id")) {
        return "source.type must be 'path' or 'telegram_file_id'"
      }
      if (!src.value || typeof src.value !== "string") return "source.value is required"
    }
    if ((action === "delete" || action === "purge") && !input.alias && !input.voice_id) {
      return "alias or voice_id is required for delete/purge"
    }
    if (action === "rename") {
      if (!input.alias || typeof input.alias !== "string") return "alias (old) is required for rename"
      if (!/^[a-z0-9_-]{1,32}$/.test(input.alias)) {
        return "alias viejo debe ser alfanumerico, guion o guion bajo, max 32 chars"
      }
      if (!input.new_alias || typeof input.new_alias !== "string") return "new_alias is required for rename"
      if (!/^[a-z0-9_-]{1,32}$/.test(input.new_alias)) {
        return "new_alias debe ser alfanumerico, guion o guion bajo, max 32 chars"
      }
      const src = input.source as { type?: unknown; value?: unknown } | undefined
      if (!src || (src.type !== "path" && src.type !== "telegram_file_id")) {
        return "source (new audio) is required for rename"
      }
      if (!src.value || typeof src.value !== "string") return "source.value is required"
    }
    return null
  },
  async run(input, context) {
    const action = input.action as "clone" | "list" | "list_remote" | "delete" | "purge" | "rename" | "sync"
    const config = readChannelsConfig()
    const tts = normalizeTtsConfig(config.tts)
    const activeProfile = getActiveProfile()

    // Provider resolution: explicit tts.provider wins, but if unset, fall
    // back to the active model profile (when it's minimax) so users who
    // have a working MiniMax model profile can call VoiceClone without an
    // extra /config set tts_provider step. This is the most common case
    // in practice.
    const explicitProvider = tts.provider
    const activeIsMiniMax = !!activeProfile && ((activeProfile.provider as string) === "minimax" || activeProfile.baseUrl.toLowerCase().includes("minimax"))
    if (explicitProvider !== "minimax" && !activeIsMiniMax) {
      return formatToolError(
        "Voice clone requiere tts.provider='minimax' o un profile activo de minimax. " +
        "Configuralo con /config set tts_provider minimax (y tts.apiKey si tu profile activo no es minimax)."
      )
    }

    // Resolucion de credenciales para VoiceClone: SIEMPRE MiniMax, independiente del LLM principal.
    // El endpoint /v1/voice_clone de MiniMax usa credenciales MiniMax, no las del LLM.
    // Prioridad:
    // 1. tts.apiKey (config específico de TTS)
    // 2. MINIMAX_API_KEY env var (SIEMPRE para TTS/VoiceClone)
    // NUNCA: activeProfile.apiKey (es del LLM, no de TTS)
    // NUNCA: ANTHROPIC_AUTH_TOKEN (es del LLM, no de TTS)
    let apiKey = (tts.apiKey || "").trim()
    if (!apiKey) {
      const minimaxEnv = (process.env.MINIMAX_API_KEY || "").trim()
      if (minimaxEnv) apiKey = minimaxEnv
    }
    if (!apiKey) {
      // Buscar credenciales MiniMax en CONF_MODELS (cualquier profile con provider=minimax)
      const modelsWing = readConfigWing(context.rootDir, "CONF_MODELS") as { profiles?: Array<{ provider?: string; apiKey?: string }> } | null
      const minimaxProfile = (modelsWing?.profiles || []).find(p => p.provider === "minimax" && p.apiKey)
      if (minimaxProfile?.apiKey) apiKey = minimaxProfile.apiKey.trim()
    }
    if (!apiKey) {
      return formatToolError("Voice clone requiere MINIMAX_API_KEY o tts.apiKey (credenciales independientes del LLM principal).")
    }
    // Resolve the MiniMax API base URL.
    let baseUrl = (tts.baseUrl || "https://api.minimax.io/v1").replace(/\/+$/g, "")
    if (!/\/v\d+$/.test(baseUrl)) baseUrl = `${baseUrl}/v1`

    // Helper clone flow to reuse between clone and rename actions
    const runCloneFlow = async (targetAlias: string, sourceArg: { type: string; value: string }, setAsDefault: boolean) => {
      const alias = targetAlias.trim().toLowerCase()
      // 1. Resolver path local
      let localPath = ""
      const sourceType = sourceArg.type
      const sourceValue = sourceArg.value
      if (sourceType === "path") {
        localPath = resolve(context.cwd, sourceValue)
      } else {
        // telegram_file_id
        if (!config.telegram?.enabled || !config.telegram.token) {
          throw new Error("source.type='telegram_file_id' requiere Telegram activo y configurado.")
        }
        const download = await resolveTelegramDownload(config.telegram.token, sourceValue, context.rootDir, `voice-clone-${alias}`)
        if (!download.ok) throw new Error(`Error descargando audio de Telegram: ${JSON.stringify(download)}`)
        localPath = download.local_path
      }

      // 2. Validar tamano y extension
      if (!existsSync(localPath)) throw new Error(`Archivo no encontrado: ${localPath}`)
      const stats = statSync(localPath)
      if (stats.size > 20 * 1024 * 1024) throw new Error(`Audio excede 20MB (${stats.size} bytes).`)
      const ext = localPath.split(".").at(-1)?.toLowerCase() || ""
      if (!["mp3", "m4a", "wav", "ogg"].includes(ext)) {
        throw new Error(`Formato no soportado: .${ext}. Usar mp3, m4a, wav u ogg.`)
      }

      // 3. Upload a MiniMax
      context.logger?.info(`[VoiceClone] Subiendo ${localPath} a MiniMax /v1/files/upload...`)
      const upload = await multipartUploadFile(
        `${baseUrl}/files/upload`,
        localPath,
        "file",
        { purpose: "voice_clone" },
        { Authorization: `Bearer ${apiKey}` },
        90_000,
      )
      if (!upload.ok) {
        throw new Error(`Upload fallo: HTTP ${upload.status} ${typeof upload.json === "string" ? upload.json : JSON.stringify(upload.json).slice(0, 300)}`)
      }
      if (!upload.json || typeof upload.json !== "object") {
        throw new Error(`Upload respondio algo inesperado: ${String(upload.json).slice(0, 300)}`)
      }
      const fileId = (upload.json as { file?: { file_id?: number } | null; file_id?: string }).file?.file_id
        ?? (upload.json as { file_id?: string }).file_id
      if (!fileId) throw new Error(`Upload no devolvio file_id: ${JSON.stringify(upload.json).slice(0, 300)}`)

      // 4. Voice clone
      const cloneModel = (optionalString(input, "model") || tts.t2aModel || "speech-2.8-hd").trim()
      context.logger?.info(`[VoiceClone] file_id=${fileId} model=${cloneModel} alias=${alias}`)
      const cloneResp = await fetch(`${baseUrl}/voice_clone`, {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
        body: JSON.stringify({
          file_id: fileId,
          voice_id: alias,                     // MiniMax acepta string arbitrario como voice_id
          model: cloneModel,
          text: optionalString(input, "text") || "",
        }),
        signal: AbortSignal.timeout(60_000),
      })
      if (!cloneResp.ok) {
        const body = await cloneResp.text().catch(() => "")
        throw new Error(`Voice clone fallo: HTTP ${cloneResp.status}${body ? ` - ${body.slice(0, 400)}` : ""}`)
      }
      const cloneJson = await cloneResp.json() as { voice_id?: string; base_resp?: { status_code?: number; status_msg?: string } }
      if (cloneJson.base_resp?.status_code && cloneJson.base_resp.status_code !== 0) {
        const isDuplicate = cloneJson.base_resp.status_code === 2056 || 
                            String(cloneJson.base_resp.status_msg).toLowerCase().includes("duplicate")
        if (isDuplicate) {
          context.logger?.info(`[VoiceClone] La voz ya existe remotamente con voice_id=${alias}. Adoptándola en la configuración local.`)
          const refreshedConfig = readChannelsConfig()
          const refreshedTts = normalizeTtsConfig(refreshedConfig.tts)
          const newVoices = { ...(refreshedTts.clonedVoices || {}), [alias]: alias }
          const persistedTts: Record<string, unknown> = {
            ...(refreshedConfig.tts || {}),
            clonedVoices: newVoices,
            defaultClonedVoice: setAsDefault ? alias : refreshedTts.defaultClonedVoice
          }
          if (!explicitProvider && activeIsMiniMax) {
            persistedTts.provider = "minimax"
            if (!persistedTts.apiKey && activeProfile?.apiKey) persistedTts.apiKey = activeProfile.apiKey
          }
          writeChannelsConfig({
            ...refreshedConfig,
            tts: persistedTts,
          })
          appendActionLog(context.rootDir, "Voz clonada adoptada por duplicado", {
            alias,
            voice_id: alias,
            note: "Ya existia en MiniMax remotamente",
          })
          return {
            ok: true,
            action: "clone",
            alias,
            voice_id: alias,
            model: cloneModel,
            is_default: setAsDefault,
            note: "La voz ya existía en MiniMax. Se adoptó y mapeó localmente con éxito.",
          }
        }
        throw new Error(`Voice clone rechazado: ${cloneJson.base_resp.status_msg || cloneJson.base_resp.status_code}`)
      }
      const voiceId = cloneJson.voice_id || alias

      // 5. Persistir (recargar config para tener cambios del paso anterior)
      const refreshedConfig = readChannelsConfig()
      const refreshedTts = normalizeTtsConfig(refreshedConfig.tts)
      const newVoices = { ...(refreshedTts.clonedVoices || {}), [alias]: voiceId }
      const persistedTts: Record<string, unknown> = {
        ...(refreshedConfig.tts || {}),
        clonedVoices: newVoices,
        defaultClonedVoice: setAsDefault ? alias : refreshedTts.defaultClonedVoice
      }
      if (!explicitProvider && activeIsMiniMax) {
        persistedTts.provider = "minimax"
        if (!persistedTts.apiKey && activeProfile?.apiKey) persistedTts.apiKey = activeProfile.apiKey
      }
      writeChannelsConfig({
        ...refreshedConfig,
        tts: persistedTts,
      })
      appendActionLog(context.rootDir, "Voz clonada creada", {
        alias,
        voice_id: voiceId,
        file_id: String(fileId),
        model: cloneModel,
      })

      return {
        ok: true,
        action: "clone",
        alias,
        voice_id: voiceId,
        file_id: String(fileId),
        model: cloneModel,
        is_default: setAsDefault,
        local_path: localPath,
        note: "Usa el alias en GenerateSpeech (voice='cristian') o setea tts.defaultClonedVoice para invocarla sin parametro.",
      }
    }

    if (action === "list") {
      // Lista local (config del monolito). Rápido, no llama a MiniMax.
      return {
        provider: "minimax",
        base_url: baseUrl,
        default_cloned_voice: tts.defaultClonedVoice || null,
        voices: tts.clonedVoices || {},
        count: Object.keys(tts.clonedVoices || {}).length,
      }
    }

    if (action === "list_remote") {
      // GET /v1/get_voice voice_type=voice_cloning (MiniMax real)
      const resp = await fetch(`${baseUrl}/get_voice`, {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
        body: JSON.stringify({ voice_type: "voice_cloning" }),
        signal: AbortSignal.timeout(30_000),
      })
      if (!resp.ok) {
        const body = await resp.text().catch(() => "")
        return formatToolError(`list_remote fallo: HTTP ${resp.status}${body ? ` - ${body.slice(0, 300)}` : ""}`)
      }
      const json = await resp.json() as { voice_cloning?: Array<{ voice_id: string; description?: string[]; created_time?: string }>; base_resp?: { status_code?: number; status_msg?: string } }
      if (json.base_resp?.status_code && json.base_resp.status_code !== 0) {
        return formatToolError(`list_remote rechazado: ${json.base_resp.status_msg || json.base_resp.status_code}`)
      }

      // Auto-sync remote voices to local config (adopt orphans + prune stale)
      const remoteVoices = json.voice_cloning || []
      const localVoices = tts.clonedVoices || {}
      let updated = false
      const newVoices = { ...localVoices }
      const newlyAdopted: string[] = []
      const newlyPruned: string[] = []

      for (const remote of remoteVoices) {
        const remoteId = remote.voice_id
        const alreadyMapped = Object.entries(localVoices).some(([alias, id]) => id === remoteId || alias === remoteId)
        if (!alreadyMapped) {
          newVoices[remoteId] = remoteId
          newlyAdopted.push(remoteId)
          updated = true
        }
      }

      for (const [alias, voiceId] of Object.entries(newVoices)) {
        const existsRemotely = remoteVoices.some(remote => remote.voice_id === voiceId || remote.voice_id === alias)
        if (!existsRemotely) {
          delete newVoices[alias]
          newlyPruned.push(alias)
          updated = true
        }
      }

      if (updated) {
        let newDefault = tts.defaultClonedVoice || ""
        if (newDefault && newlyPruned.includes(newDefault)) {
          newDefault = ""
        }
        writeChannelsConfig({
          ...config,
          tts: {
            ...(config.tts || {}),
            clonedVoices: newVoices,
            defaultClonedVoice: newDefault,
          }
        })
      }

      return {
        provider: "minimax",
        base_url: baseUrl,
        voice_type: "voice_cloning",
        voices: json.voice_cloning || [],
        count: (json.voice_cloning || []).length,
        newly_synchronized: newlyAdopted.length > 0 ? newlyAdopted : undefined,
        newly_pruned: newlyPruned.length > 0 ? newlyPruned : undefined,
        note: "Las voces clonadas aparecen solo después de usarse al menos una vez con GenerateSpeech.",
      }
    }

    if (action === "sync") {
      // GET /v1/get_voice to sync local with remote
      const resp = await fetch(`${baseUrl}/get_voice`, {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
        body: JSON.stringify({ voice_type: "voice_cloning" }),
        signal: AbortSignal.timeout(30_000),
      })
      if (!resp.ok) {
        const body = await resp.text().catch(() => "")
        return formatToolError(`sync fallo al consultar MiniMax: HTTP ${resp.status}${body ? ` - ${body.slice(0, 300)}` : ""}`)
      }
      const json = await resp.json() as { voice_cloning?: Array<{ voice_id: string; description?: string[]; created_time?: string }>; base_resp?: { status_code?: number; status_msg?: string } }
      if (json.base_resp?.status_code && json.base_resp.status_code !== 0) {
        return formatToolError(`sync rechazado: ${json.base_resp.status_msg || json.base_resp.status_code}`)
      }

      const remoteVoices = json.voice_cloning || []
      const localVoices = tts.clonedVoices || {}
      let updated = false
      const newVoices = { ...localVoices }
      const newlyAdopted: string[] = []
      const newlyPruned: string[] = []

      for (const remote of remoteVoices) {
        const remoteId = remote.voice_id
        const alreadyMapped = Object.entries(localVoices).some(([alias, id]) => id === remoteId || alias === remoteId)
        if (!alreadyMapped) {
          newVoices[remoteId] = remoteId
          newlyAdopted.push(remoteId)
          updated = true
        }
      }

      for (const [alias, voiceId] of Object.entries(newVoices)) {
        const existsRemotely = remoteVoices.some(remote => remote.voice_id === voiceId || remote.voice_id === alias)
        if (!existsRemotely) {
          delete newVoices[alias]
          newlyPruned.push(alias)
          updated = true
        }
      }

      if (updated) {
        let newDefault = tts.defaultClonedVoice || ""
        if (newDefault && newlyPruned.includes(newDefault)) {
          newDefault = ""
        }
        writeChannelsConfig({
          ...config,
          tts: {
            ...(config.tts || {}),
            clonedVoices: newVoices,
            defaultClonedVoice: newDefault,
          }
        })
      }

      return {
        ok: true,
        action: "sync",
        synchronized: newlyAdopted,
        count_synchronized: newlyAdopted.length,
        pruned: newlyPruned,
        count_pruned: newlyPruned.length,
        voices: newVoices,
        total_count: Object.keys(newVoices).length,
      }
    }

    if (action === "purge") {
      // DELETE /v1/delete_voice en MiniMax + borrar de config local
      const alias = optionalString(input, "alias")
      const voiceId = optionalString(input, "voice_id")
      const target = alias ? (tts.clonedVoices?.[alias] ?? alias) : voiceId
      if (!target) return formatToolError(`No se encontro la voz alias='${alias}' o voice_id='${voiceId}'`)

      // Llamar a MiniMax DELETE
      let remoteDeleted = false
      let remoteError: string | null = null
      try {
        const delResp = await fetch(`${baseUrl}/delete_voice`, {
          method: "POST",
          headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
          body: JSON.stringify({ voice_type: "voice_cloning", voice_id: target }),
          signal: AbortSignal.timeout(30_000),
        })
        if (delResp.ok) {
          const delJson = await delResp.json() as { base_resp?: { status_code?: number; status_msg?: string } }
          if (!delJson.base_resp?.status_code || delJson.base_resp.status_code === 0) {
            remoteDeleted = true
          } else {
            remoteError = delJson.base_resp.status_msg || String(delJson.base_resp.status_code)
          }
        } else {
          const body = await delResp.text().catch(() => "")
          remoteError = `HTTP ${delResp.status}${body ? ` - ${body.slice(0, 200)}` : ""}`
        }
      } catch (e) {
        remoteError = e instanceof Error ? e.message : String(e)
      }

      // Borrar de config local (siempre, aunque MiniMax falle)
      const newVoices = { ...(tts.clonedVoices || {}) }
      let removedAlias: string | null = null
      if (alias && newVoices[alias] === target) {
        delete newVoices[alias]
        removedAlias = alias
      } else {
        for (const [k, v] of Object.entries(newVoices)) {
          if (v === target) { delete newVoices[k]; removedAlias = k; break }
        }
      }
      const newDefault = tts.defaultClonedVoice === removedAlias ? "" : tts.defaultClonedVoice
      writeChannelsConfig({
        ...config,
        tts: { ...(config.tts || {}), clonedVoices: newVoices, defaultClonedVoice: newDefault },
      })

      return {
        ok: remoteDeleted || !remoteError,
        action: "purge",
        removed_alias: removedAlias,
        voice_id: target,
        remote_deleted: remoteDeleted,
        remote_error: remoteError || undefined,
        note: remoteDeleted
          ? "Borrada en MiniMax (DELETE /v1/delete_voice) y en config local."
          : `Borrada de config local. MiniMax: ${remoteError || "no se pudo confirmar"}.`,
      }
    }

    if (action === "rename") {
      // Purge alias viejo + clone con nuevo alias (requiere nuevo audio)
      const oldAlias = String(input.alias || "").trim().toLowerCase()
      const newAlias = String(input.new_alias || "").trim().toLowerCase()
      if (!oldAlias) return formatToolError("alias (old) is required for rename")
      if (!newAlias) return formatToolError("new_alias is required for rename")
      const oldVoiceId = tts.clonedVoices?.[oldAlias]
      if (!oldVoiceId) return formatToolError(`No existe alias='${oldAlias}' en config local`)

      // 1. Purge (MiniMax + local)
      const purgeResult = await (async () => {
        try {
          const delResp = await fetch(`${baseUrl}/delete_voice`, {
            method: "POST",
            headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
            body: JSON.stringify({ voice_type: "voice_cloning", voice_id: oldVoiceId }),
            signal: AbortSignal.timeout(30_000),
          })
          const delJson = await delResp.json().catch(() => ({})) as { base_resp?: { status_code?: number } }
          // Borrar local
          const newVoices = { ...(tts.clonedVoices || {}) }
          delete newVoices[oldAlias]
          const newDefault = tts.defaultClonedVoice === oldAlias ? "" : tts.defaultClonedVoice
          writeChannelsConfig({ ...config, tts: { ...(config.tts || {}), clonedVoices: newVoices, defaultClonedVoice: newDefault } })
          return { ok: delResp.ok && (!delJson.base_resp?.status_code || delJson.base_resp.status_code === 0) }
        } catch {
          return { ok: false }
        }
      })()

      // 2. Clone con nuevo alias en la misma llamada
      try {
        const cloneResult = await runCloneFlow(newAlias, input.source as { type: string; value: string }, input.set_default === true)
        return {
          ok: true,
          action: "rename",
          old_alias: oldAlias,
          new_alias: newAlias,
          purged: purgeResult.ok,
          clone: cloneResult,
        }
      } catch (err) {
        return formatToolError(`Rename falló en la etapa de clonación: ${err instanceof Error ? err.message : String(err)} (la voz vieja '${oldAlias}' fue purgada: ${purgeResult.ok ? "sí" : "no"})`)
      }
    }

    if (action === "delete") {
      const alias = optionalString(input, "alias")
      const target = alias ? tts.clonedVoices?.[alias] : optionalString(input, "voice_id")
      if (!target) return formatToolError(`No se encontro la voz alias='${alias}' o voice_id='${input.voice_id}'`)
      // Solo borra de config local. Para borrar también en MiniMax usá 'purge'.
      const newVoices = { ...(tts.clonedVoices || {}) }
      let removedAlias: string | null = null
      if (alias && newVoices[alias] === target) {
        delete newVoices[alias]
        removedAlias = alias
      } else {
        // buscar alias por voice_id
        for (const [k, v] of Object.entries(newVoices)) {
          if (v === target) { delete newVoices[k]; removedAlias = k; break }
        }
      }
      const newDefault = tts.defaultClonedVoice === removedAlias ? "" : tts.defaultClonedVoice
      writeChannelsConfig({
        ...config,
        tts: { ...(config.tts || {}), clonedVoices: newVoices, defaultClonedVoice: newDefault },
      })
      return {
        ok: true,
        action: "delete",
        removed_alias: removedAlias,
        voice_id: target,
        note: "Solo borrado de config local. Para borrar también en MiniMax usá action='purge'.",
      }
    }

    // action === "clone"
    const alias = (input.alias as string).trim().toLowerCase()
    if (tts.clonedVoices?.[alias]) {
      return formatToolError(`El alias '${alias}' ya existe (voice_id=${tts.clonedVoices[alias]}). Usa action='delete' primero o elegi otro alias.`)
    }

    return await runCloneFlow(alias, input.source as { type: string; value: string }, input.set_default === true)
  },
},

{
  name: "VisionAnalyze",
  permissionTier: "read",
  description: "Analiza una imagen desde una URL, un path local o un file_id de Telegram, utilizando la API de visión del modelo de nube activo (Anthropic, OpenAI, Grok). Rápido (~3-5s). No hay fallback local: si la API de nube falla o el modelo activo no soporta visión, devuelve un error claro y sugerí cambiar a un modelo con visión. Retorna { description, local_path }. Usá esta herramienta directamente cuando el usuario pide describir, analizar o verificar el contenido de una imagen — no es necesario delegar a un sub-agente para casos simples.",
  inputSchema: {
    type: "object",
    properties: {
      url: { type: "string", description: "URL de la imagen a descargar y analizar." },
      path: { type: "string", description: "Ruta local del archivo de imagen a analizar." },
      file_id: { type: "string", description: "Telegram file_id. Si se proporciona, descarga la imagen desde los servidores de Telegram (útil si la URL de origen bloquea descargas directas)." },
    },
    additionalProperties: false,
  },
  concurrencySafe: true,
  validate: input => {
    if (typeof input.url !== "string" && typeof input.path !== "string" && typeof input.file_id !== "string") {
      return "Debes proporcionar 'url', 'path' o 'file_id' como string."
    }
    return null
  },
  async run(input, context) {
    const url = optionalString(input, "url")
    const pathArg = optionalString(input, "path")
    const fileId = optionalString(input, "file_id")
    
    let buffer: Buffer
    let mediaType = "image/jpeg"
    let localPath = ""
    
    if (fileId) {
      const config = readChannelsConfig()
      if (!config.telegram?.enabled || !config.telegram.token) {
        return formatToolError("Telegram no está configurado. file_id requiere Telegram activo.")
      }
      try {
        const download = await resolveTelegramDownload(config.telegram.token, fileId, context.rootDir)
        if (!download.ok) {
          return formatToolError(`Error descargando desde Telegram: ${JSON.stringify(download)}`)
        }
        buffer = readFileSync(download.local_path)
        localPath = download.local_path
        
        if (localPath.toLowerCase().endsWith(".png")) mediaType = "image/png"
        else if (localPath.toLowerCase().endsWith(".webp")) mediaType = "image/webp"
        else if (localPath.toLowerCase().endsWith(".gif")) mediaType = "image/gif"
      } catch (error: any) {
        return formatToolError(`Error descargando desde Telegram: ${error.message || error}`)
      }
    } else if (url) {
      if (url.toLowerCase().endsWith(".png")) mediaType = "image/png"
      else if (url.toLowerCase().endsWith(".webp")) mediaType = "image/webp"
      else if (url.toLowerCase().endsWith(".gif")) mediaType = "image/gif"
      
      const response = await fetch(url, {
        headers: {
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
          "Accept": "image/*,*/*",
        },
        signal: context.abortSignal,
      })
      if (!response.ok) return formatToolError(`Error descargando imagen desde URL: HTTP ${response.status}`)
      buffer = Buffer.from(await response.arrayBuffer())

      const scratchpadDir = join(MONOLITO_ROOT, "workspace", "scratchpad")
      mkdirSync(scratchpadDir, { recursive: true })
      localPath = join(scratchpadDir, `vision-${randomUUID()}.${mediaType === "image/png" ? "png" : "jpg"}`)
      writeFileSync(localPath, buffer)
    } else if (pathArg) {
      if (pathArg.toLowerCase().endsWith(".png")) mediaType = "image/png"
      else if (pathArg.toLowerCase().endsWith(".webp")) mediaType = "image/webp"
      else if (pathArg.toLowerCase().endsWith(".gif")) mediaType = "image/gif"
      
      const absolutePath = resolve(context.cwd, pathArg)
      if (!existsSync(absolutePath)) return formatToolError(`Archivo no encontrado: ${absolutePath}`)
      buffer = readFileSync(absolutePath)
      localPath = absolutePath
    } else {
      return formatToolError("Debes proporcionar 'url', 'path' o 'file_id'.")
    }

    const base64Image = buffer.toString("base64")
    
    const activeProfile = getActiveProfile()
    let provider = "anthropic_compatible"
    let baseUrl = ""
    let apiKey = ""
    let model = ""

    if (activeProfile) {
      provider = activeProfile.provider
      baseUrl = activeProfile.baseUrl.trim().replace(/\/+$/, "")
      apiKey = activeProfile.apiKey.trim()
      model = activeProfile.model.trim()
    } else {
      const settings = readModelSettings()
      provider = "anthropic_compatible"
      baseUrl = settings.env.ANTHROPIC_BASE_URL.trim().replace(/\/+$/, "")
      apiKey = settings.env.ANTHROPIC_AUTH_TOKEN.trim()
      model = settings.env.ANTHROPIC_MODEL.trim()
    }

    if (provider === "xai-oauth") {
      try {
        const { resolveGrokAccessToken } = await import("../../runtime/providers/grokAuth.ts")
        apiKey = await resolveGrokAccessToken()
      } catch (err) {
        context.logger?.error(`Error resolving Grok access token in VisionAnalyze: ${err}`)
      }
    }

    if (provider === "anthropic_compatible" || provider === "minimax") {
      const cleanBaseUrl = baseUrl.replace(/\/v1\/messages\/?$/, "")
      const endpoint = cleanBaseUrl ? `${cleanBaseUrl}/v1/messages` : "https://api.anthropic.com/v1/messages"
      
      const response = await fetch(endpoint, {
        method: "POST",
        headers: {
          "content-type": "application/json",
          "x-api-key": apiKey || "not-needed",
          "anthropic-version": "2023-06-01"
        },
        body: JSON.stringify({
          model: model,
          max_tokens: 1000,
          messages: [
            {
              role: "user",
              content: [
                {
                  type: "image",
                  source: {
                    type: "base64",
                    media_type: mediaType,
                    data: base64Image
                  }
                },
                {
                  type: "text",
                  text: "Describe exactly what is in this image in detail."
                }
              ]
            }
          ]
        }),
        signal: context.abortSignal
      })

      if (!response.ok) {
        const text = await response.text()
        return formatToolError(`Anthropic Vision API failed (${response.status}): ${text}`)
      }

      const data = await response.json() as { content?: Array<{ text?: string }>; choices?: Array<{ message?: { content?: string } }> }
      const description = data.content?.[0]?.text || ""
      if (!description) {
        return formatToolError("Vision API returned an empty description. The active model may not support image inputs, or the image was rejected by the provider. Switch to a vision-capable model and try again.")
      }
      return { ok: true, description, local_path: localPath }
    } else {
      const endpoint = baseUrl ? `${baseUrl}/v1/chat/completions` : "https://api.openai.com/v1/chat/completions"
      
      const response = await fetch(endpoint, {
        method: "POST",
        headers: {
          "content-type": "application/json",
          "authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify({
          model: model,
          max_tokens: 1000,
          messages: [
            {
              role: "user",
              content: [
                {
                  type: "image_url",
                  image_url: {
                    url: `data:${mediaType};base64,${base64Image}`
                  }
                },
                {
                  type: "text",
                  text: "Describe exactly what is in this image in detail."
                }
              ]
            }
          ]
        }),
        signal: context.abortSignal
      })

      if (!response.ok) {
        const text = await response.text()
        return formatToolError(`OpenAI Vision API failed (${response.status}): ${text}`)
      }

      const data = await response.json() as { content?: Array<{ text?: string }>; choices?: Array<{ message?: { content?: string } }> }
      const description = data.choices?.[0]?.message?.content || ""
      if (!description) {
        return formatToolError("Vision API returned an empty description. The active model may not support image inputs, or the image was rejected by the provider. Switch to a vision-capable model and try again.")
      }
      return { ok: true, description, local_path: localPath }
    }
  },
},

{
  name: "GenerateImage",
  permissionTier: "edit",
  description: "Genera una imagen a partir de una descripción detallada (prompt). Soporta xAI Grok (grok-imagine-image) por defecto si la sesión está autenticada, MiniMax (image-01) si el perfil activo es MiniMax, o DALL-E si está configurado.",
  inputSchema: {
    type: "object",
    properties: {
      prompt: { type: "string", description: "Descripción detallada de la imagen a generar (ej: 'Un gato de estilo cyberpunk con ojos de neón brillante')." },
      aspect_ratio: { type: "string", enum: ["1:1", "16:9", "9:16", "4:3", "3:4", "3:2", "2:3"], description: "Relación de aspecto de la imagen generada. Por defecto es '1:1'." },
      quality: { type: "string", enum: ["standard", "quality"], description: "Calidad de generación. Por defecto es 'standard'. 'quality' produce mayor nivel de detalle (solo soportado por Grok)." },
      provider: { type: "string", enum: ["xai", "openai", "minimax"], description: "Forzar un proveedor específico. Por defecto detecta automáticamente basándose en las credenciales del perfil activo." }
    },
    required: ["prompt"],
    additionalProperties: false
  },
  concurrencySafe: true,
  validate: input => {
    if (typeof input.prompt !== "string" || input.prompt.trim().length === 0) {
      return "El prompt de generación no puede estar vacío."
    }
    return null
  },
  async run(input, context) {
    try {
      const prompt = requireString(input, "prompt")
      const aspect_ratio = optionalString(input, "aspect_ratio") || "1:1"
      const quality = optionalString(input, "quality") || "standard"
      const providerOverride = optionalString(input, "provider")

      // 1. Resolve Provider and Credentials
      let provider = "xai"
      let baseUrl = "https://api.x.ai/v1"
      let apiKey = ""
      let model = ""

      const activeProfile = getActiveProfile()

      if (providerOverride === "xai") {
        provider = "xai"
      } else if (providerOverride === "openai") {
        provider = "openai"
      } else if (providerOverride === "minimax") {
        provider = "minimax"
      } else {
        // Auto-detect
        if (activeProfile && ((activeProfile.provider as string) === "xai-oauth" || (activeProfile.provider as string) === "xai" || activeProfile.baseUrl.includes("x.ai"))) {
          provider = "xai"
        } else if (activeProfile && ((activeProfile.provider as string) === "minimax" || activeProfile.baseUrl.toLowerCase().includes("minimax"))) {
          provider = "minimax"
        } else {
          const { loadGrokTokens } = await import("../../runtime/providers/grokAuth.ts")
          const hasGrokTokens = await loadGrokTokens().then(t => !!t).catch(() => false)
          const hasGrokEnv = !!process.env.XAI_API_KEY
          if (hasGrokTokens || hasGrokEnv) {
            provider = "xai"
          } else if (activeProfile && (activeProfile.provider === "openai_compatible" || activeProfile.provider === "anthropic_compatible")) {
            provider = "openai"
          } else {
            provider = "xai"
          }
        }
      }

      // Resolve credentials
      if (provider === "xai") {
        baseUrl = "https://api.x.ai/v1"
        if (activeProfile && ((activeProfile.provider as string) === "xai-oauth" || (activeProfile.provider as string) === "xai")) {
          apiKey = activeProfile.apiKey.trim()
          if ((activeProfile.provider as string) === "xai-oauth") {
            try {
              const { resolveGrokAccessToken } = await import("../../runtime/providers/grokAuth.ts")
              apiKey = await resolveGrokAccessToken()
            } catch (err) {
              context.logger?.error(`Error resolving Grok access token: ${err}`)
            }
          }
        } else {
          if (process.env.XAI_API_KEY) {
            apiKey = process.env.XAI_API_KEY.trim()
          } else {
            try {
              const { resolveGrokAccessToken } = await import("../../runtime/providers/grokAuth.ts")
              apiKey = await resolveGrokAccessToken()
            } catch (err) {
              // Ignore, we fail later
            }
          }
        }
        model = quality === "quality" ? "grok-imagine-image-quality" : "grok-imagine-image"
      } else if (provider === "minimax") {
        // MiniMax — image-01 (default). API key del perfil activo, o
        // fallback a MINIMAX_API_KEY / ANTHROPIC_AUTH_TOKEN (la misma que
        // se usa para chat con el endpoint Anthropic-compatible).
        baseUrl = "https://api.minimax.io/v1"
        if (activeProfile && (activeProfile.provider as string) === "minimax") {
          apiKey = activeProfile.apiKey.trim()
        } else {
          apiKey = (process.env.MINIMAX_API_KEY ?? process.env.ANTHROPIC_AUTH_TOKEN ?? "").trim()
        }
        // Importante: ignorar activeProfile.model porque es el modelo de
        // CHAT (ej: "MiniMax-M3") y MiniMax rechaza con 2013 cuando se
        // le pasa un modelo que no soporta image_generation. Hardcodeamos
        // image-01 que es el único modelo de imagen soportado.
        model = "image-01"
      } else {
        // OpenAI
        if (activeProfile) {
          baseUrl = activeProfile.baseUrl.trim().replace(/\/+$/, "")
          apiKey = activeProfile.apiKey.trim()
          model = activeProfile.model.trim() || "dall-e-3"
        } else {
          baseUrl = process.env.OPENAI_BASE_URL?.trim() || "https://api.openai.com/v1"
          apiKey = process.env.OPENAI_API_KEY?.trim() || ""
          model = "dall-e-3"
        }
      }

      if (!apiKey) {
        return formatToolError(
          `No se encontraron credenciales válidas para el proveedor '${provider}'. ` +
          `Para xAI Grok, ejecutá 'monolito auth xai-oauth' en tu terminal o configurá XAI_API_KEY. ` +
          `Para OpenAI, configurá OPENAI_API_KEY. ` +
          `Para MiniMax, asegurate de tener un perfil activo con provider='minimax' o configurá MINIMAX_API_KEY (o ANTHROPIC_AUTH_TOKEN como fallback).`
        )
      }

      // 2. Prepare Endpoint and Payload
      let endpoint = `${baseUrl.replace(/\/+$/, "")}/images/generations`
      let payload: Record<string, any> = {}

      if (provider === "xai" || baseUrl.includes("x.ai")) {
        payload = {
          model: model,
          prompt: prompt,
          aspect_ratio: aspect_ratio,
          resolution: "1k"
        }
      } else if (provider === "minimax") {
        // MiniMax image_generation API (no es OpenAI-compatible).
        // Docs: https://platform.minimax.io/docs/guides/image-generation
        endpoint = `${baseUrl.replace(/\/+$/, "")}/image_generation`
        payload = {
          model: model || "image-01",
          prompt: prompt,
          aspect_ratio: aspect_ratio,
          response_format: "base64"
        }
      } else {
        // OpenAI DALL-E — body OpenAI-style.
        let size = "1024x1024"
        if (aspect_ratio === "16:9") {
          size = "1792x1024"
        } else if (aspect_ratio === "9:16") {
          size = "1024x1792"
        } else if (aspect_ratio === "4:3") {
          size = "1024x768"
        } else if (aspect_ratio === "3:4") {
          size = "768x1024"
        }
        payload = {
          model: model || "dall-e-3",
          prompt: prompt,
          size: size,
          n: 1
        }
      }

      context.logger?.info(`Iniciando generación de imagen con '${provider}' y modelo '${model}'...`)

      // 3. Request
      const response = await fetch(endpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify(payload),
        signal: context.abortSignal
      })

      if (!response.ok) {
        const errorText = await response.text()
        return formatToolError(`La API de generación de imágenes falló (${response.status}): ${errorText}`)
      }

      const result = await response.json() as {
        data?:
          | Array<{ b64_json?: string; url?: string }>
          | { image_base64?: string[] }
      }
      let b64: string | undefined
      let imageUrl: string | undefined

      if (provider === "minimax") {
        // MiniMax: data es { image_base64: [base64, ...] } (no array).
        const dataObj = (result.data as { image_base64?: string[] } | undefined) ?? {}
        const arr = dataObj.image_base64 || []
        if (arr.length === 0) {
          return formatToolError("La API de MiniMax no devolvió ninguna imagen en la respuesta.")
        }
        b64 = arr[0]
      } else {
        // OpenAI / xAI: data es array de { b64_json, url }.
        const arr = (result.data as Array<{ b64_json?: string; url?: string }> | undefined) || []
        if (arr.length === 0) {
          return formatToolError("La API no devolvió ninguna imagen en la respuesta.")
        }
        const first = arr[0]
        b64 = first.b64_json
        imageUrl = first.url
      }

      // 4. Save Locally
      const scratchpadDir = join(MONOLITO_ROOT, "workspace", "scratchpad")
      mkdirSync(scratchpadDir, { recursive: true })

      let localPath = ""
      let isPng = true

      if (b64) {
        const buffer = Buffer.from(b64, "base64")
        localPath = join(scratchpadDir, `img-gen-${randomUUID()}.png`)
        writeFileSync(localPath, buffer)
      } else if (imageUrl) {
        const imgResponse = await fetch(imageUrl, { signal: context.abortSignal })
        if (!imgResponse.ok) {
          return formatToolError(`No se pudo descargar la imagen generada desde la URL: HTTP ${imgResponse.status}`)
        }
        const buffer = Buffer.from(await imgResponse.arrayBuffer())
        if (imageUrl.toLowerCase().endsWith(".jpg") || imageUrl.toLowerCase().endsWith(".jpeg")) {
          isPng = false
        }
        localPath = join(scratchpadDir, `img-gen-${randomUUID()}.${isPng ? "png" : "jpg"}`)
        writeFileSync(localPath, buffer)
      } else {
        return formatToolError("La respuesta no contiene ni 'b64_json' ni 'url'.")
      }

      context.logger?.info(`Imagen generada exitosamente en: ${localPath}`)

      return JSON.stringify({
        success: true,
        local_path: localPath,
        url: imageUrl || null,
        provider: provider,
        model: model,
        prompt: prompt,
        aspect_ratio: aspect_ratio
      }, null, 2)

    } catch (err: any) {
      return formatToolError(`Error durante la generación de la imagen: ${err.message}`)
    }
  }
},
{
  name: "CaptureScreenshot",
  aliases: ["capture_screenshot", "screenshot"],
  permissionTier: "read",
  description: "Captura inmediatamente una pantalla de la PC local y la guarda en la carpeta de capturas del scratchpad. Úsala cada vez que el usuario te pregunte qué es lo que ves en su pantalla, qué hay en su PC, o te pida mirar o analizar su pantalla. Devuelve { ok: true, local_path }.",
  inputSchema: emptyInputSchema,
  concurrencySafe: false,
  async run(input, context) {
    const paths = ensureDirs(context.rootDir, context.profileId)
    const screenshotDir = join(paths.scratchpadDir, "screenshots")
    mkdirSync(screenshotDir, { recursive: true })
    const filename = `screenshot-${Date.now()}.png`
    const localPath = join(screenshotDir, filename)

    const commands = [
      { name: "gnome-screenshot", args: ["-f", localPath] },
      { name: "import", args: ["-window", "root", localPath] },
      { name: "scrot", args: [localPath] },
      { name: "maim", args: [localPath] },
      { name: "grim", args: [localPath] }
    ]

    if (lastSuccessfulScreenshotCmd) {
      const idx = commands.findIndex(c => c.name === lastSuccessfulScreenshotCmd)
      if (idx > 0) {
        const [cmd] = commands.splice(idx, 1)
        commands.unshift(cmd)
      }
    }

    for (const cmd of commands) {
      try {
        await execFileAsync(cmd.name, cmd.args)
        if (existsSync(localPath)) {
          lastSuccessfulScreenshotCmd = cmd.name
          return { ok: true, local_path: localPath }
        }
      } catch (err) {
        // Ignorar y probar siguiente
      }
    }

    return formatToolError("No se pudo capturar la pantalla con ninguna utilidad (gnome-screenshot, import, scrot, maim, grim).")
  },
},

]
