// Auto-generated by scripts/split_registry.py — do not edit manually.
// Domain: memory (9 tools)

import {
  join,
} from "node:path"

import {
  bootCreateWingInputZod,
  bootWriteInputZod,
  emptyInputSchema,
  formatToolError,
  optionalString,
  parseZod,
  requireString,
  validateZod,
} from "../internal.ts"

import {
  addGraphTriple,
  bootWingExists,
  createBootWing,
  ensureBootWings,
  fileMemory,
  invalidateGraphTriple,
  listBootWings,
  listRooms,
  listWings,
  queryGraphEntity,
  readBootWing,
  recallMemory,
  writeBootWing,
} from "../../session/store.ts"

import {
  BOOT_WING_ORDER,
  isBootWingName,
} from "../../bootstrap/bootWings.ts"

import {
  isEmbeddingsUnavailableError,
} from "../../session/embeddings.ts"

import type { ToolDefinition } from "../registry.ts"

export const memoryTools: ToolDefinition[] = [
{
  name: "BootRead",
  permissionTier: "read",
  description: "Read a deterministic or dynamically created BOOT wing from SQLite without relying on legacy workspace files.",
  inputSchema: {
    type: "object",
    properties: {
      wing: { type: "string" },
    },
    required: ["wing"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    try {
      const wing = requireString(input, "wing")
      ensureBootWings(context.rootDir, context.profileId ?? "default")
      if (!bootWingExists(context.rootDir, wing, context.profileId ?? "default")) {
        return formatToolError(`BOOT wing ${wing} not found in profile ${context.profileId ?? "default"}. Use BootListWings to inspect available wings.`)
      }
      const content = readBootWing(context.rootDir, wing, context.profileId ?? "default")
      if (content == null) return formatToolError(`BOOT wing ${wing} not found in profile ${context.profileId ?? "default"}`)
      return { wing, content, profile: context.profileId ?? "default" }
    } catch (error) {
      return formatToolError(error)
    }
  },
},

{
  name: "BootListWings",
  permissionTier: "read",
  description: "List BOOT wings currently registered in SQLite for the active profile. Run this before BootCreateWing or BootWrite when choosing a wing.",
  inputSchema: emptyInputSchema,
  concurrencySafe: true,
  async run(_input, context) {
    try {
      const profile = context.profileId ?? "default"
      const wings = listBootWings(context.rootDir, profile)
      return JSON.stringify({ profile, wings })
    } catch (error) {
      return formatToolError(error)
    }
  },
},

{
  name: "BootCreateWing",
  permissionTier: "edit",
  description: "Create a new empty BOOT wing in SQLite for the active profile. The model MUST call BootListWings first and only use this when the desired alphanumeric/snake_case wing is absent.",
  inputSchema: {
    type: "object",
    properties: {
      wing: {
        type: "string",
        description: "New BOOT wing name. Use alphanumeric/snake_case only, starting with a letter.",
        pattern: "^[A-Za-z][A-Za-z0-9_]*$",
      },
    },
    required: ["wing"],
    additionalProperties: false,
  },
  concurrencySafe: false,
  validate: input => validateZod(bootCreateWingInputZod, input),
  async run(input, context) {
    try {
      const parsed = parseZod(bootCreateWingInputZod, input, "BootCreateWing input")
      const wing = parsed.wing.trim()
      if (!isBootWingName(wing)) {
        return formatToolError(
          `Cannot create custom BOOT wing "${wing}". Only standard wings are allowed: ${BOOT_WING_ORDER.join(", ")}. ` +
          `For custom episodic data, use WorkspaceMemoryFiling instead.`
        )
      }
      const profile = context.profileId ?? "default"
      if (bootWingExists(context.rootDir, wing, profile)) {
        return formatToolError(`BOOT wing ${wing} already exists in profile ${profile}. Use BootWrite to update it.`)
      }
      const result = createBootWing(context.rootDir, wing, profile, "")
      return { ok: true, wing, created: result.created, profile }
    } catch (error) {
      return formatToolError(error)
    }
  },
},

{
  name: "BootWrite",
  permissionTier: "edit",
  description: "Replace or append to the content of an existing BOOT wing in SQLite. Use BootListWings first; if the wing does not exist, create it with BootCreateWing before writing. WARNING: Use ONLY for core, permanent identity rules. For episodic memories, temporary data, or conversational facts, use WorkspaceMemoryFiling instead.",
  inputSchema: {
    type: "object",
    properties: {
      wing: { type: "string" },
      content: { type: "string" },
      action: { type: "string", enum: ["overwrite", "append"], description: "Action to perform. Default is 'overwrite'." },
    },
    required: ["wing", "content"],
    additionalProperties: false,
  },
  concurrencySafe: false,
  validate: input => validateZod(bootWriteInputZod, input),
  async run(input, context) {
    try {
      const parsed = parseZod(bootWriteInputZod, input, "BootWrite input")
      const wing = parsed.wing
      const profileId = context.profileId ?? "default"
      if (!bootWingExists(context.rootDir, wing, profileId)) {
        return formatToolError(`BOOT wing ${wing} does not exist in profile ${profileId}. Use BootListWings, then BootCreateWing if you need a new wing.`)
      }
      const append = parsed.action === "append"
      const result = writeBootWing(context.rootDir, wing, parsed.content, profileId, append)
      return { wing, ok: true, changed: result.changed, bytes: result.bytes, profile: profileId }
    } catch (error) {
      return formatToolError(error)
    }
  },
},

{
  name: "WorkspaceMemoryFiling",
  permissionTier: "edit",
  description: "Store facts, decisions, or snippets in the SQLite Memory Palace. Use wing='SHARED' for team-wide memory visible to every profile. Use wing='session_preferences' with room=sessionId and key='pref_silent_research' (content='true'/'false') to dynamically toggle silent background updates for this session.",
  inputSchema: {
    type: "object",
    properties: {
      wing: { type: "string", description: "Wing name. Use 'SHARED' for global memory, or 'session_preferences' to toggle session-scoped preferences (with room=sessionId)." },
      room: { type: "string", description: "Topical room within the wing (e.g. 'architecture', 'auth')." },
      key: { type: "string", description: "Optional stable key to group or retrieve a specific memory later." },
      content: { type: "string", description: "The raw verbatim detail or decision to save." },
    },
    required: ["wing", "room", "content"],
    additionalProperties: false,
  },
  concurrencySafe: false,
  async run(input, context) {
    const wing = requireString(input, "wing")
    const room = requireString(input, "room")
    const key = optionalString(input, "key")
    const content = requireString(input, "content")
    const id = await fileMemory(context.rootDir, wing, room, content, context.profileId, key)
    return { ok: true, id, wing, room, key: key ?? null, shared: wing.trim().toUpperCase() === "SHARED" }
  },
},

{
  name: "WorkspaceMemoryRecall",
  permissionTier: "read",
  description: "Recall memories from the SQLite Memory Palace. Results are limited to the current profile plus global SHARED memories. Calls without filters still respect that isolation.",
  inputSchema: {
    type: "object",
    properties: {
      wing: { type: "string", description: "Optional filter for a specific wing." },
      room: { type: "string", description: "Optional filter for a specific room to narrow down." },
      key: { type: "string", description: "Optional stable key filter for an exact memory group." },
      query: { type: "string", description: "Optional natural language query for deep semantic search." }
    },
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    const wing = optionalString(input, "wing")
    const room = optionalString(input, "room")
    const key = optionalString(input, "key")
    const query = optionalString(input, "query")

    let results: any[] = []
    let warning: string | null = null
    let semanticSearchActive = !!query
    try {
      results = await recallMemory(context.rootDir, wing, room, query, context.profileId, key)
    } catch (error) {
      if (!query || !isEmbeddingsUnavailableError(error)) return formatToolError(error)
      semanticSearchActive = false
      warning = "La memoria semántica no está disponible en este momento; muestro memoria básica reciente."
      results = await recallMemory(context.rootDir, wing, room, undefined, context.profileId, key)
    }
    
    if (!wing && !room && !key && !query) {
      return {
        wings: listWings(context.rootDir, context.profileId),
        recentMemories: results,
        warning,
      }
    }
    if (wing && !room && !key && !query) {
      return {
        wing,
        rooms: listRooms(context.rootDir, wing, context.profileId),
        memories: results,
        warning,
      }
    }
    return {
      wing,
      room,
      key,
      query,
      semanticSearchActive,
      warning,
      memories: results
    }
  },
},

{
  name: "KgAdd",
  permissionTier: "edit",
  description: "Add a temporal knowledge-graph triple scoped to the current profile.",
  inputSchema: {
    type: "object",
    properties: {
      subject: { type: "string", description: "Entity or subject node." },
      predicate: { type: "string", description: "Relationship label." },
      object: { type: "string", description: "Entity, value, or object node." },
      valid_from: { type: "string", description: "Optional ISO timestamp for when the fact became valid." },
    },
    required: ["subject", "predicate", "object"],
    additionalProperties: false,
  },
  concurrencySafe: false,
  async run(input, context) {
    const subject = requireString(input, "subject")
    const predicate = requireString(input, "predicate")
    const object = requireString(input, "object")
    const validFrom = optionalString(input, "valid_from") ?? new Date().toISOString()
    const profileId = context.profileId ?? "default"
    const id = addGraphTriple(context.rootDir, profileId, subject, predicate, object, validFrom)
    return { ok: true, id, profileId, subject, predicate, object, valid_from: validFrom, active: true }
  },
},

{
  name: "KgInvalidate",
  permissionTier: "edit",
  description: "Invalidate an active temporal knowledge-graph triple by setting valid_to.",
  inputSchema: {
    type: "object",
    properties: {
      subject: { type: "string", description: "Entity or subject node." },
      predicate: { type: "string", description: "Relationship label." },
      object: { type: "string", description: "Entity, value, or object node." },
      valid_to: { type: "string", description: "Optional ISO timestamp for when the fact stopped being valid." },
    },
    required: ["subject", "predicate", "object"],
    additionalProperties: false,
  },
  concurrencySafe: false,
  async run(input, context) {
    const subject = requireString(input, "subject")
    const predicate = requireString(input, "predicate")
    const object = requireString(input, "object")
    const validTo = optionalString(input, "valid_to") ?? new Date().toISOString()
    const profileId = context.profileId ?? "default"
    const result = invalidateGraphTriple(context.rootDir, profileId, subject, predicate, object, validTo)
    return {
      ok: result.changes > 0,
      profileId,
      subject,
      predicate,
      object,
      valid_to: validTo,
      invalidated: result.changes,
    }
  },
},

{
  name: "KgQuery",
  permissionTier: "read",
  description: "Query temporal knowledge-graph facts for an entity within the current profile.",
  inputSchema: {
    type: "object",
    properties: {
      entity: { type: "string", description: "Entity to search as subject or object." },
    },
    required: ["entity"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    const entity = requireString(input, "entity")
    const profileId = context.profileId ?? "default"
    const facts = queryGraphEntity(context.rootDir, profileId, entity)
    return {
      ok: true,
      profileId,
      entity,
      facts,
    }
  },
},

]
