// Auto-generated by scripts/split_registry.py — do not edit manually.
// Domain: memory (9 tools)

import {
  join,
} from "node:path"

import {
  bootCreateWingInputZod,
  bootWriteInputZod,
  emptyInputSchema,
  formatToolError,
  optionalString,
  parseZod,
  requireString,
  validateZod,
} from "../internal.ts"

import {
  addGraphTriple,
  bootWingExists,
  createBootWing,
  ensureBootWings,
  fileMemory,
  invalidateGraphTriple,
  listBootWings,
  listMemoryNamespaces,
  listMemorySections,
  queryGraphEntity,
  readBootWing,
  recallMemory,
  getSemanticMessageContext,
  upsertCuratedMemory,
  writeBootWing,
} from "../../session/store.ts"

import {
  BOOT_WING_ORDER,
  isBootWingName,
} from "../../bootstrap/bootWings.ts"

import type { ToolDefinition } from "../registry.ts"

function resolveCuratedMemoryLocation(input: Record<string, unknown>) {
  const namespace = optionalString(input, "namespace") ?? optionalString(input, "wing")
  const section = optionalString(input, "section") ?? optionalString(input, "room")
  return { namespace, section }
}

export const memoryTools: ToolDefinition[] = [
{
  name: "BootRead",
  permissionTier: "read",
  description: "Read a BOOT wing from memory/boot/*.md (or memory.md for BOOT_MEMORY).",
  inputSchema: {
    type: "object",
    properties: {
      wing: { type: "string" },
    },
    required: ["wing"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    try {
      const wing = requireString(input, "wing")
      ensureBootWings(context.rootDir, context.profileId ?? "default")
      if (!bootWingExists(context.rootDir, wing, context.profileId ?? "default")) {
        return formatToolError(`BOOT wing ${wing} not found in profile ${context.profileId ?? "default"}. Use BootListWings to inspect available wings.`)
      }
      const content = readBootWing(context.rootDir, wing, context.profileId ?? "default")
      if (content == null) return formatToolError(`BOOT wing ${wing} not found in profile ${context.profileId ?? "default"}`)
      return { wing, content, profile: context.profileId ?? "default" }
    } catch (error) {
      return formatToolError(error)
    }
  },
},

{
  name: "BootListWings",
  permissionTier: "read",
  description: "List BOOT wings registered in memory/boot/*.md for the active profile.",
  inputSchema: emptyInputSchema,
  concurrencySafe: true,
  async run(_input, context) {
    try {
      const profile = context.profileId ?? "default"
      const wings = listBootWings(context.rootDir, profile)
      return JSON.stringify({ profile, wings })
    } catch (error) {
      return formatToolError(error)
    }
  },
},

{
  name: "BootCreateWing",
  permissionTier: "edit",
  description: "Create a new empty BOOT wing markdown file for the active profile. Call BootListWings first and only use this when the desired wing is absent.",
  inputSchema: {
    type: "object",
    properties: {
      wing: {
        type: "string",
        description: "New BOOT wing name. Use alphanumeric/snake_case only, starting with a letter.",
        pattern: "^[A-Za-z][A-Za-z0-9_]*$",
      },
    },
    required: ["wing"],
    additionalProperties: false,
  },
  concurrencySafe: false,
  validate: input => validateZod(bootCreateWingInputZod, input),
  async run(input, context) {
    try {
      const parsed = parseZod(bootCreateWingInputZod, input, "BootCreateWing input")
      const wing = parsed.wing.trim()
      if (!isBootWingName(wing)) {
        return formatToolError(
          `Cannot create custom BOOT wing "${wing}". Only standard wings are allowed: ${BOOT_WING_ORDER.join(", ")}. ` +
          `For custom episodic data, use WorkspaceMemoryFiling instead.`
        )
      }
      const profile = context.profileId ?? "default"
      if (bootWingExists(context.rootDir, wing, profile)) {
        return formatToolError(`BOOT wing ${wing} already exists in profile ${profile}. Use BootWrite to update it.`)
      }
      const result = createBootWing(context.rootDir, wing, profile, "")
      return { ok: true, wing, created: result.created, profile }
    } catch (error) {
      return formatToolError(error)
    }
  },
},

{
  name: "BootWrite",
  permissionTier: "edit",
  description: "Replace or append to a BOOT wing in memory/boot/*.md (or memory.md for BOOT_MEMORY). Use BootListWings first.",
  inputSchema: {
    type: "object",
    properties: {
      wing: { type: "string" },
      content: { type: "string" },
      action: { type: "string", enum: ["overwrite", "append"], description: "Action to perform. Default is 'overwrite'." },
    },
    required: ["wing", "content"],
    additionalProperties: false,
  },
  concurrencySafe: false,
  validate: input => validateZod(bootWriteInputZod, input),
  async run(input, context) {
    try {
      const parsed = parseZod(bootWriteInputZod, input, "BootWrite input")
      const wing = parsed.wing
      const profileId = context.profileId ?? "default"
      if (!bootWingExists(context.rootDir, wing, profileId)) {
        return formatToolError(`BOOT wing ${wing} does not exist in profile ${profileId}. Use BootListWings, then BootCreateWing if you need a new wing.`)
      }
      const append = parsed.action === "append"
      const result = writeBootWing(context.rootDir, wing, parsed.content, profileId, append)
      return { wing, ok: true, changed: result.changed, bytes: result.bytes, profile: profileId }
    } catch (error) {
      return formatToolError(error)
    }
  },
},

{
  name: "WorkspaceMemoryFiling",
  permissionTier: "edit",
  description: "Store facts in memory.md as a ## section (curated digest). Use namespace='SHARED' for profile-wide memory.",
  inputSchema: {
    type: "object",
    properties: {
      namespace: { type: "string", description: "Memory namespace. Use 'SHARED' for global memory, or 'session_preferences' with section=sessionId for session-scoped preferences." },
      section: { type: "string", description: "Topical section heading (e.g. 'architecture', 'auth')." },
      key: { type: "string", description: "Optional stable key to group or retrieve a specific memory later." },
      content: { type: "string", description: "The raw verbatim detail or decision to save." },
    },
    required: ["namespace", "section", "content"],
    additionalProperties: false,
  },
  concurrencySafe: false,
  validate: input => {
    const { namespace, section } = resolveCuratedMemoryLocation(input)
    if (!namespace) return "namespace is required"
    if (!section) return "section is required"
    if (typeof input.content !== "string" || input.content.trim().length === 0) return "content is required"
    return null
  },
  async run(input, context) {
    const { namespace, section } = resolveCuratedMemoryLocation(input)
    if (!namespace || !section) return formatToolError("namespace and section are required")
    const key = optionalString(input, "key")
    const content = requireString(input, "content")
    const result = key
      ? await upsertCuratedMemory(context.rootDir, namespace, section, content, context.profileId, key)
      : { id: await fileMemory(context.rootDir, namespace, section, content, context.profileId), action: "inserted" as const }
    return { ok: true, id: result.id, action: result.action, namespace, section, key: key ?? null, shared: namespace.trim().toUpperCase() === "SHARED" }
  },
},

{
  name: "WorkspaceMemoryRecall",
  permissionTier: "read",
  description: "Search memory.md sections by keyword. Main agent already has memory.md loaded; use this for targeted section lookup or archive search.",
  inputSchema: {
    type: "object",
    properties: {
      namespace: { type: "string", description: "Optional filter for a specific namespace." },
      section: { type: "string", description: "Optional filter for a specific section heading." },
      key: { type: "string", description: "Optional stable key filter for an exact memory group." },
      query: { type: "string", description: "Optional keyword query over memory.md section content." }
    },
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    const namespace = optionalString(input, "namespace") ?? optionalString(input, "wing")
    const section = optionalString(input, "section") ?? optionalString(input, "room")
    const key = optionalString(input, "key")
    const query = optionalString(input, "query")

    let results: any[] = []
    const keywordSearchActive = !!query
    try {
      results = await recallMemory(context.rootDir, namespace, section, query, context.profileId, key)
    } catch (error) {
      return formatToolError(error)
    }
    
    if (!namespace && !section && !key && !query) {
      return {
        namespaces: listMemoryNamespaces(context.rootDir, context.profileId),
        recentMemories: results,
      }
    }
    if (namespace && !section && !key && !query) {
      return {
        namespace,
        sections: listMemorySections(context.rootDir, namespace, context.profileId),
        memories: results,
      }
    }
    return {
      namespace,
      section,
      key,
      query,
      keywordSearchActive,
      memories: results
    }
  },
},

{
  name: "KgAdd",
  permissionTier: "edit",
  description: "Add a temporal knowledge-graph triple scoped to the current profile.",
  inputSchema: {
    type: "object",
    properties: {
      subject: { type: "string", description: "Entity or subject node." },
      predicate: { type: "string", description: "Relationship label." },
      object: { type: "string", description: "Entity, value, or object node." },
      valid_from: { type: "string", description: "Optional ISO timestamp for when the fact became valid." },
    },
    required: ["subject", "predicate", "object"],
    additionalProperties: false,
  },
  concurrencySafe: false,
  async run(input, context) {
    const subject = requireString(input, "subject")
    const predicate = requireString(input, "predicate")
    const object = requireString(input, "object")
    const validFrom = optionalString(input, "valid_from") ?? new Date().toISOString()
    const profileId = context.profileId ?? "default"
    const id = addGraphTriple(context.rootDir, profileId, subject, predicate, object, validFrom)
    return { ok: true, id, profileId, subject, predicate, object, valid_from: validFrom, active: true }
  },
},

{
  name: "KgInvalidate",
  permissionTier: "edit",
  description: "Invalidate an active temporal knowledge-graph triple by setting valid_to.",
  inputSchema: {
    type: "object",
    properties: {
      subject: { type: "string", description: "Entity or subject node." },
      predicate: { type: "string", description: "Relationship label." },
      object: { type: "string", description: "Entity, value, or object node." },
      valid_to: { type: "string", description: "Optional ISO timestamp for when the fact stopped being valid." },
    },
    required: ["subject", "predicate", "object"],
    additionalProperties: false,
  },
  concurrencySafe: false,
  async run(input, context) {
    const subject = requireString(input, "subject")
    const predicate = requireString(input, "predicate")
    const object = requireString(input, "object")
    const validTo = optionalString(input, "valid_to") ?? new Date().toISOString()
    const profileId = context.profileId ?? "default"
    const result = invalidateGraphTriple(context.rootDir, profileId, subject, predicate, object, validTo)
    return {
      ok: result.changes > 0,
      profileId,
      subject,
      predicate,
      object,
      valid_to: validTo,
      invalidated: result.changes,
    }
  },
},

{
  name: "KgQuery",
  permissionTier: "read",
  description: "Query temporal knowledge-graph facts for an entity within the current profile.",
  inputSchema: {
    type: "object",
    properties: {
      entity: { type: "string", description: "Entity to search as subject or object." },
    },
    required: ["entity"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    const entity = requireString(input, "entity")
    const profileId = context.profileId ?? "default"
    const facts = queryGraphEntity(context.rootDir, profileId, entity)
    return {
      ok: true,
      profileId,
      entity,
      facts,
    }
  },
},

{
  name: "SearchHistory",
  aliases: ["search_history"],
  permissionTier: "read",
  description: "Search prior chat messages by keyword over session history JSONL. Returns matching turns with context. Use when the user asks about something from an older conversation not in memory.md.",
  inputSchema: {
    type: "object",
    properties: {
      query: { type: "string", description: "Keywords to search in message history." },
      limit: { type: "number", description: "Max results (default 8)." },
    },
    required: ["query"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    const query = requireString(input, "query")
    const limit = typeof input.limit === "number" ? Math.min(20, Math.max(1, input.limit)) : 8
    try {
      const rows = getSemanticMessageContext(context.rootDir, query, limit)
      return {
        query,
        count: rows.length,
        matches: rows.map(r => ({
          session_id: r.session_id,
          role: r.role,
          at: r.at,
          text: r.text.length > 1200 ? `${r.text.slice(0, 1200)}...` : r.text,
        })),
      }
    } catch (error) {
      return formatToolError(error)
    }
  },
},

]
