// Auto-generated by scripts/split_registry.py — do not edit manually.
// Domain: shell (2 tools)

import {
  createWriteStream,
  existsSync,
  openSync,
  unlinkSync,
  writeFileSync,
} from "node:fs"

import {
  join,
  relative,
  resolve,
} from "node:path"

import {
  randomUUID,
} from "node:crypto"

import {
  spawn,
} from "node:child_process"

import {
  DEFAULT_BASH_TIMEOUT_MS,
  MAX_EXEC_BUFFER,
  buildTraceEnv,
  execFileAsync,
  formatToolError,
  optionalBoolean,
  optionalNumber,
  parseAbsoluteTimeToUtc,
  parseZod,
  requireString,
  scheduleTaskInputZod,
  validateZod,
} from "../internal.ts"

import {
  ensureDirs,
} from "../../ipc/protocol.ts"

import type { ToolDefinition } from "../registry.ts"

export const shellTools: ToolDefinition[] = [
{
  name: "schedule_task",
  permissionTier: "edit",
  description: `Unified tool for scheduling and managing reminders and cron jobs. Always use this tool for anything time/reminder related.

Actions:
- "list": Returns all scheduled recurring cron jobs with their index numbers.
- "add": Adds a new job. Three modes:
  * One-shot relative (delay_seconds): fires once after N seconds.
  * One-shot absolute (at or time): fires once at a specific absolute local time (e.g., '15:30' or '2026-05-18 10:00').
  * Recurring (cron_expression): adds a persistent cron job. Best for 'every day at 8am'.
Requires: message, chat_id, timezone. Plus either delay_seconds, at/time, OR cron_expression.
- "remove": Removes a recurring cron job by its index (1-based, from "list").`,
  inputSchema: {
    type: "object",
    properties: {
      action: { type: "string", enum: ["list", "add", "remove"], description: "Operation to perform." },
      message: { type: "string", description: "[add] The reminder/notification text to send via Telegram." },
      chat_id: { type: "number", description: "[add] Telegram chat ID." },
      delay_seconds: { type: "number", description: "[add, one-shot relative] Seconds from now to fire. Mutually exclusive with at, time, and cron_expression." },
      at: { type: "string", description: "[add, one-shot absolute] Absolute time to fire (e.g. '15:30', '2026-05-18 10:00'). Mutually exclusive with delay_seconds, time, and cron_expression. CRITICAL: If the user only specified a time (e.g. '02:31'), pass only that time string '02:31' exactly without calculating or prepending a date, so that the tool can correctly decide if it's today or tomorrow using the user's local timezone." },
      time: { type: "string", description: "[add, one-shot absolute] Alias for 'at'. Absolute time to fire. Mutually exclusive with delay_seconds, at, and cron_expression. CRITICAL: If the user only specified a time (e.g. '02:31'), pass only that time string '02:31' exactly without calculating or prepending a date, so that the tool can correctly decide if it's today or tomorrow using the user's local timezone." },
      cron_expression: { type: "string", description: "[add, recurring] Standard cron expression, e.g. '0 10 * * *' for 10am daily." },
      timezone: { type: "string", description: "[add] The IANA timezone of the user (e.g. 'America/Argentina/Buenos_Aires'). Required when adding any job." },
      job_index: { type: "number", description: "[remove] 1-based index of the cron job to remove (from 'list')." },
    },
    required: ["action"],
    additionalProperties: false,
  },
  validate: input => validateZod(scheduleTaskInputZod, input),
  async run(input) {
    const parsed = parseZod(scheduleTaskInputZod, input, "schedule_task input")
    const action = parsed.action

    // ── LIST ──────────────────────────────────────────────────────────────
    if (action === "list") {
      try {
        const { stdout } = await execFileAsync("crontab", ["-l"])
        if (!stdout.trim()) return "No recurring jobs scheduled."
        const lines = stdout.split("\n")
        const jobs = lines
          .map((line, i) => ({ line: line.trim(), i }))
          .filter(({ line }) => line && !line.startsWith("#") && !line.startsWith("CRON_TZ="))
        if (jobs.length === 0) return "No recurring jobs scheduled."
        return jobs.map(({ line, i: _i }, idx) => `[${idx + 1}] ${line}`).join("\n")
      } catch (error: any) {
        if (error.stderr?.includes("no crontab for")) return "No recurring jobs scheduled."
        throw new Error(error.stderr || error.message)
      }
    }

    // ── REMOVE ────────────────────────────────────────────────────────────
    if (action === "remove") {
      const jobIndex = parsed.job_index
      if (!jobIndex || jobIndex < 1) return formatToolError("job_index is required and must be >= 1")
      let existing = ""
      try {
        const { stdout } = await execFileAsync("crontab", ["-l"])
        existing = stdout
      } catch (error: any) {
        if (!error.stderr?.includes("no crontab for")) throw new Error(error.stderr || error.message)
      }
      const lines = existing.split("\n")
      const jobEntries = lines
        .map((line, originalIndex) => ({ line: line.trim(), originalIndex }))
        .filter(entry => entry.line && !entry.line.startsWith("#") && !entry.line.startsWith("CRON_TZ="))
      if (jobIndex > jobEntries.length) return formatToolError(`Job index ${jobIndex} out of range (only ${jobEntries.length} jobs).`)
      
      const targetEntry = jobEntries[jobIndex - 1]
      const targetIndex = targetEntry.originalIndex
      const targetJob = targetEntry.line
      
      if (targetIndex > 0 && lines[targetIndex - 1].startsWith("CRON_TZ=")) {
        lines.splice(targetIndex - 1, 2)
      } else {
        lines.splice(targetIndex, 1)
      }
      const newContent = lines.join("\n").trim()
      const tempPath = join("/tmp", `crontab-${randomUUID()}`)
      try {
        writeFileSync(tempPath, newContent + "\n")
        await execFileAsync("crontab", [tempPath])
        return `Removed job [${jobIndex}]: ${targetJob}`
      } catch (error: any) {
        throw new Error(`Failed to update crontab: ${error.stderr || error.message}`)
      } finally {
        if (existsSync(tempPath)) try { require("node:fs").unlinkSync(tempPath) } catch {}
      }
    }

    // ── ADD ───────────────────────────────────────────────────────────────
    if (action === "add") {
      const { message, chat_id, timezone, delay_seconds, at, time, cron_expression } = parsed

      // Inject into Monolito's orchestrator session memory so the agent becomes conscious of the reminder
      const cliScript = join(process.cwd(), "src/apps/cli.ts")
      const monolitoCmd = `${process.execPath} --experimental-strip-types "${cliScript}" resume orchestrator -p "RECORDATORIO DEL SISTEMA: ${message.replace(/"/g, '\\"')}"`

      // 1. One-shot relative: delay_seconds
      if (delay_seconds !== undefined) {
        const shellCmd = `sleep ${Math.floor(delay_seconds)} && ${monolitoCmd}`
        const child = spawn("bash", ["-c", shellCmd], { detached: true, stdio: "ignore" })
        child.unref()
        const fireAt = new Date(Date.now() + delay_seconds * 1000)
        const fireAtStr = fireAt.toLocaleTimeString("es-AR", {
          hour: "2-digit",
          minute: "2-digit",
          second: "2-digit",
          timeZone: timezone,
        })
        return `One-shot reminder scheduled for ${fireAtStr} (in ${Math.round(delay_seconds / 60)} min) using timezone ${timezone}.\nMessage: "${message}"`
      }

      // 2. One-shot absolute: at or time
      const absoluteTimeStr = at ?? time
      if (absoluteTimeStr !== undefined) {
        const targetUtcDate = parseAbsoluteTimeToUtc(absoluteTimeStr, timezone)
        const currentUtcMs = Date.now()
        const diffMs = targetUtcDate.getTime() - currentUtcMs
        
        if (diffMs <= 0) {
          return formatToolError("The scheduled absolute time is in the past.")
        }
        
        const computedDelaySeconds = diffMs / 1000
        const shellCmd = `sleep ${Math.floor(computedDelaySeconds)} && ${monolitoCmd}`
        const child = spawn("bash", ["-c", shellCmd], { detached: true, stdio: "ignore" })
        child.unref()
        
        const fireAtStr = targetUtcDate.toLocaleTimeString("es-AR", {
          hour: "2-digit",
          minute: "2-digit",
          second: "2-digit",
          timeZone: timezone,
        })
        return `One-shot absolute reminder scheduled for ${fireAtStr} (in ${Math.round(computedDelaySeconds / 60)} min) using timezone ${timezone}.\nMessage: "${message}"`
      }

      // 3. Recurring: append to crontab
      if (cron_expression !== undefined) {
        let existing = ""
        try {
          const { stdout } = await execFileAsync("crontab", ["-l"])
          existing = stdout
        } catch (error: any) {
          if (!error.stderr?.includes("no crontab for")) throw new Error(error.stderr || error.message)
        }
        const newLine = `CRON_TZ="${timezone}"\n${cron_expression} ${monolitoCmd}`
        const newContent = (existing.trim() ? existing.trimEnd() + "\n" : "") + newLine + "\n"
        const tempPath = join("/tmp", `crontab-${randomUUID()}`)
        try {
          writeFileSync(tempPath, newContent)
          await execFileAsync("crontab", [tempPath])
          return `Recurring job added: ${newLine}`
        } catch (error: any) {
          throw new Error(`Failed to write crontab: ${error.stderr || error.message}`)
        } finally {
          if (existsSync(tempPath)) try { require("node:fs").unlinkSync(tempPath) } catch {}
        }
      }
    }

    return formatToolError(`Unknown action: ${action}`)
  },
},

{
  name: "Bash",
  aliases: ["bash"],
  permissionTier: "edit",
  sideEffect: true,
  isReadOnly: false,
  description: "Execute a shell command locally from the workspace. Optional: run_in_background=true for long-running commands. Permission gate: AST-parses command, runs 12 security validators, evaluates per-segment with permission rules, blocks critical/high findings, asks on parse-unavailable or cross-segment cd+git, returns exit code interpretation. Output truncated at 30K chars (64MB cap). PROHIBIDO: No uses esta herramienta para invocar APIs externas de LLM o visión.",
  inputSchema: {
    type: "object",
    properties: {
      command: { type: "string" },
      timeout: { type: "number" },
      run_in_background: { type: "boolean" },
    },
    required: ["command"],
    additionalProperties: false,
  },
  concurrencySafe: false,
  validate: input => typeof input.command === "string" && input.command.trim().length > 0 ? null : "command must be a non-empty string",
  async run(input, context) {
    const command = requireString(input, "command")
    const timeout = optionalNumber(input, "timeout") ?? DEFAULT_BASH_TIMEOUT_MS
    const runInBackground = optionalBoolean(input, "run_in_background") ?? false

    // Permission gate: AST + permission rules + segmentation + security validators
    const { gateBashCommand } = await import("./bash/permissionGate.ts")
    type BashPermissionRule = {
      tool: string
      action: "allow" | "deny" | "ask"
      prefix?: string
      input?: string
    }
    // Read permission rules from policyConfigZod
    const { readConfigWing } = await import("../../session/store.ts")
    const policyRaw = (() => {
      try {
        return readConfigWing(context.rootDir, "CONF_POLICY" as any) as unknown
      } catch { return null }
    })()
    const bashRules: BashPermissionRule[] = []
    if (typeof policyRaw === "string" && policyRaw) {
      try {
        const policy = JSON.parse(policyRaw)
        for (const rule of policy?.permissions?.rules ?? []) {
          if (rule.tool?.startsWith("Bash") && rule.prefix) {
            bashRules.push({
              tool: "Bash",
              action: rule.action,
              prefix: rule.prefix,
              input: rule.input,
            })
          }
        }
      } catch { /* ignore */ }
    }
    const gateResult = gateBashCommand(command, {
      rules: bashRules,
      acceptEditsMode: false,
    })
    if (gateResult.decision === "deny") {
      return formatToolError(`Bash denied: ${gateResult.reason}`)
    }
    // attach findings to result
    const securityFindings = gateResult.findings
    const destructiveFindings = gateResult.findings.filter(f => f.rule === "destructive")
    const destructiveWarning = destructiveFindings.length > 0
      ? `Destructive command detected: ${destructiveFindings.map(f => f.description).join("; ")}`
      : undefined

    const shell = process.env.SHELL || "/bin/zsh"
    const env = buildTraceEnv(context.traceId)
    const instanceLogPath = context.logger?.logPath
    let runResult: Record<string, unknown>
    if (runInBackground) {
      const taskId = randomUUID()
      const paths = ensureDirs(context.rootDir)
      const outputPath = instanceLogPath ?? join(paths.logsDir, `background-${taskId}.log`)
      const stdout = openSync(outputPath, "a")
      const stderr = openSync(outputPath, "a")
      const child = spawn(shell, ["-lc", command], {
        cwd: context.cwd,
        detached: true,
        stdio: ["ignore", stdout, stderr],
        env,
        signal: context.abortSignal,
      })
      child.on("error", () => {})
      child.unref()
      runResult = {
        background: true,
        taskId,
        pid: child.pid,
        outputPath,
        command,
      }
    } else if (instanceLogPath) {
      const stdoutChunks: Buffer[] = []
      const stderrChunks: Buffer[] = []
      const outputStream = createWriteStream(instanceLogPath, { flags: "a" })
      const child = spawn(shell, ["-lc", command], {
        cwd: context.cwd,
        stdio: ["ignore", "pipe", "pipe"],
        env,
        signal: context.abortSignal,
      })
      const timeoutId = setTimeout(() => {
        child.kill("SIGKILL")
      }, timeout)
      child.stdout?.on("data", chunk => {
        const buffer = Buffer.isBuffer(chunk) ? chunk : Buffer.from(String(chunk))
        stdoutChunks.push(buffer)
        outputStream.write(buffer)
      })
      child.stderr?.on("data", chunk => {
        const buffer = Buffer.isBuffer(chunk) ? chunk : Buffer.from(String(chunk))
        stderrChunks.push(buffer)
        outputStream.write(buffer)
      })
      const exitCode = await new Promise<number | null>(resolve => {
        child.on("error", () => resolve(null))
        child.on("close", code => resolve(code === null ? null : code))
      })
      clearTimeout(timeoutId)
      outputStream.end()
      runResult = {
        command,
        cwd: context.cwd,
        stdout: Buffer.concat(stdoutChunks).toString(),
        stderr: Buffer.concat(stderrChunks).toString(),
        interrupted: exitCode === null,
        exitCode,
      }
    } else {
      try {
        const result = await execFileAsync(shell, ["-lc", command], {
          cwd: context.cwd,
          timeout,
          maxBuffer: MAX_EXEC_BUFFER,
          env,
          signal: context.abortSignal,
        })
        runResult = {
          command,
          cwd: context.cwd,
          stdout: result.stdout,
          stderr: result.stderr,
          interrupted: false,
          exitCode: 0,
        }
      } catch (error) {
        const typed = error as Error & { code?: number | string; killed?: boolean; stdout?: string; stderr?: string }
        runResult = {
          command,
          cwd: context.cwd,
          stdout: typed.stdout ?? "",
          stderr: typed.stderr ?? typed.message,
          interrupted: typed.killed ?? false,
          exitCode: typeof typed.code === "number" ? typed.code : null,
        }
      }
    }

    // Attach low/medium security findings + destructive warning
    const lowSeverity = securityFindings.filter(f => f.severity === "low" || f.severity === "medium")
    if (lowSeverity.length > 0) {
      runResult.security_notices = lowSeverity.map(f => `${f.rule}: ${f.description}`)
    }
    if (destructiveWarning) {
      runResult.warning = destructiveWarning
    }
    return runResult
  },
},

]
