// Auto-generated by scripts/split_registry.py — do not edit manually.
// Domain: skills (6 tools)

import {
  join,
} from "node:path"

import {
  emptyInputSchema,
  readSkillGuardConfig,
  scanSkillGuideForThreats,
  shouldRecordSkillUse,
} from "../internal.ts"

import {
  archiveDynamicSkill,
  deleteDynamicSkill,
  getDynamicSkill,
  incrementSkillTelemetry,
  listDynamicSkills,
  restoreArchivedSkill,
  saveDynamicSkill,
  upsertSemanticTool,
} from "../../session/store.ts"

import type { ToolDefinition } from "../registry.ts"

export const skillsTools: ToolDefinition[] = [
{
  name: "CreateSkill",
  permissionTier: "edit",
  description: "Crea o actualiza un skill dinámico (habilidad) que proporciona una guía instructiva procedimental (SOP - Standard Operating Procedure) detallada en Markdown sobre cómo encadenar herramientas nativas de Monolito para realizar tareas complejas de forma robusta. Los skills NO son scripts ejecutables. Son manuales operativos que el asistente puede descubrir y leer a través de la herramienta `skill_view` para evitar errores comunes y aplicar mejores prácticas. Si el skill requiere herramientas nativas específicas (ej: ['VisionAnalyze']), decláralas en el array requiresTools.",
  inputSchema: {
    type: "object",
    properties: {
      name: {
        type: "string",
        description: "Nombre único del skill (debe empezar con 'skill_' y usar snake_case, ej: 'skill_commit_build')."
      },
      description: {
        type: "string",
        description: "Una descripción clara y concisa del propósito del skill. Se inyecta en el prompt del sistema y se usa para la búsqueda vectorial."
      },
      guide: {
        type: "string",
        description: "Manual detallado en Markdown (instrucciones paso a paso, numbered steps, herramientas a usar, pitfalls y mitigaciones) sobre cómo resolver el flujo."
      },
      requiresTools: {
        type: "array",
        items: { type: "string" },
        description: "Array opcional de nombres de herramientas nativas de Monolito requeridas para ejecutar este skill (ej: ['VisionAnalyze', 'TelegramSendPhoto'])."
      }
    },
    required: ["name", "description", "guide"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    try {
      const name = String(input.name).trim()
      if (!name.startsWith("skill_")) {
        return { ok: false, error: "El nombre del skill debe empezar con 'skill_'." }
      }
      const description = String(input.description).trim()
      const guide = String(input.guide)
      const requiresTools = Array.isArray(input.requiresTools)
        ? input.requiresTools.map(t => String(t).trim())
        : undefined

      // Provenance: skills created from a synthetic SkillsAgent turn or by a
      // sub-agent are marked as "agent" (eligible for curator). User turns are
      // marked as "user" (protected from curator).
      const provenance: "agent" | "user" = (
        context.sessionId?.startsWith("agent-") ||
        context.sessionId === "skills-synthetic" ||
        // Internal flag set by runSkillsCreate in runtime.ts
        (context as { isSkillsSynthetic?: boolean }).isSkillsSynthetic === true
      ) ? "agent" : "user"

      // Optional security scan for agent-created skills.
      let securityWarning: string | null = null
      if (provenance === "agent") {
        const skillGuardEnabled = readSkillGuardConfig(context.rootDir)
        if (skillGuardEnabled) {
          const scan = scanSkillGuideForThreats(guide)
          if (scan.threat) {
            securityWarning = `Security scan flagged content (pattern: ${scan.pattern}). Review before persisting.`
          }
        }
      }

      const now = new Date().toISOString()
      const skill = {
        name,
        description,
        author: provenance === "agent" ? "skills-agent" : "user",
        guide,
        requiresTools,
        active: true,
        provenance,
        createdAt: now,
        updatedAt: now,
      }

      saveDynamicSkill(context.rootDir, skill)
      // Vectorize semantically right away. The <available_skills> block in the
      // system prompt is built live from listDynamicSkills on every turn — no
      // explicit cache to invalidate.
      await upsertSemanticTool(context.rootDir, name, `Dynamic Skill: ${name} - ${description}`)

      const warningSuffix = securityWarning ? ` WARNING: ${securityWarning}` : ""
      return { ok: true, message: `Skill '${name}' creado (provenance=${provenance}) e indexado semánticamente.${warningSuffix}` }
    } catch (err: any) {
      return { ok: false, error: `Error creando el skill: ${err.message}` }
    }
  }
},

{
  name: "DeleteSkill",
  permissionTier: "edit",
  description: "Elimina permanentemente un skill dinámico por su nombre. Las skills con provenance='user' están protegidas contra borrado desde turnos sintéticos (curator, sub-agents) — pero el usuario, hablando a través del LLM en un turno normal, SÍ puede borrarlas. Si querés desactivarla sin perderla, usá ArchiveSkill.",
  inputSchema: {
    type: "object",
    properties: {
      name: {
        type: "string",
        description: "Nombre del skill a eliminar (ej: 'skill_deploy_website')."
      }
    },
    required: ["name"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    try {
      const name = String(input.name).trim()
      const skill = getDynamicSkill(context.rootDir, name)
      if (!skill) {
        return { ok: false, error: `El skill '${name}' no existe.` }
      }
      // Provenance protection applies ONLY when the call comes from a
      // non-user context. The user, through a normal turn, is the ultimate
      // authority over their own skills. The protection is here to stop
      // the curator (synthetic turn) or sub-agents from accidentally
      // deleting things the user created.
      const callerIsUserTurn = (
        !context.sessionId?.startsWith("agent-") &&
        context.sessionId !== "skills-synthetic" &&
        (context as { isSkillsSynthetic?: boolean }).isSkillsSynthetic !== true
      )
      if ((skill.provenance || "user") === "user" && !callerIsUserTurn) {
        return { ok: false, error: `Skill '${name}' tiene provenance='user' y no se puede borrar desde un turno sintético (curator/sub-agent). Usá ArchiveSkill para desactivarla reversiblemente, o pedí al usuario que la borre desde un turno normal.` }
      }
      deleteDynamicSkill(context.rootDir, name)
      return { ok: true, message: `Skill '${name}' eliminado exitosamente del registro y del vector store.` }
    } catch (err: any) {
      return { ok: false, error: `Error eliminando el skill: ${err.message}` }
    }
  }
},

{
  name: "ArchiveSkill",
  permissionTier: "edit",
  description: "Archiva (desactiva reversiblemente) un skill dinámico. La skill queda en la base de datos pero deja de aparecer en el bloque <available_skills> del system prompt. Usá RestoreSkill para reactivarla. Usado por el curator para limpiar skills obsoletas sin perderlas.",
  inputSchema: {
    type: "object",
    properties: {
      name: {
        type: "string",
        description: "Nombre del skill a archivar (ej: 'skill_legacy_workflow')."
      },
      reason: {
        type: "string",
        description: "Razón breve del archivado (opcional). Se guarda en el campo archiveReason."
      }
    },
    required: ["name"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    try {
      const name = String(input.name).trim()
      const reason = input.reason ? String(input.reason).trim() : undefined
      const result = archiveDynamicSkill(context.rootDir, name, reason)
      if (!result.ok) return { ok: false, error: result.error }
      return { ok: true, message: `Skill '${name}' archivado${reason ? ` (motivo: ${reason})` : ""}. Usá RestoreSkill para reactivarlo.` }
    } catch (err: any) {
      return { ok: false, error: `Error archivando el skill: ${err.message}` }
    }
  }
},

{
  name: "RestoreSkill",
  permissionTier: "edit",
  description: "Restaura un skill archivado, volviéndolo a hacer visible en el bloque <available_skills> del system prompt.",
  inputSchema: {
    type: "object",
    properties: {
      name: {
        type: "string",
        description: "Nombre del skill a restaurar (ej: 'skill_legacy_workflow')."
      }
    },
    required: ["name"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    try {
      const name = String(input.name).trim()
      const result = restoreArchivedSkill(context.rootDir, name)
      if (!result.ok) return { ok: false, error: result.error }
      return { ok: true, message: `Skill '${name}' restaurado y activo nuevamente.` }
    } catch (err: any) {
      return { ok: false, error: `Error restaurando el skill: ${err.message}` }
    }
  }
},

{
  name: "ListSkills",
  permissionTier: "read",
  description: "Lista todas las habilidades dinámicas creadas, mostrando su estado, provenance y telemetría de uso.",
  inputSchema: emptyInputSchema,
  concurrencySafe: true,
  async run(input, context) {
    try {
      // Include archived ones so the curator can see them; the LLM in normal
      // turns rarely calls this and is allowed to see archived state.
      const skills = listDynamicSkills(context.rootDir, { includeArchived: true })
      if (skills.length === 0) {
        return "No hay skills dinámicos registrados en este momento."
      }
      const formatted = skills.map(s => {
        const telemetry = s.telemetry || { use_count: 0, last_used_at: "nunca", failure_count: 0 }
        const provenance = s.provenance || "user"
        const status = s.active ? "ACTIVO" : `ARCHIVADO${s.archiveReason ? `: ${s.archiveReason}` : ""}`
        return `* ${s.name} [${provenance}] (${status})
- Descripción: ${s.description}
- Autor: ${s.author}
- Usos: ${telemetry.use_count} | Fallos: ${telemetry.failure_count}
- Último Uso: ${telemetry.last_used_at}
- Creado: ${s.createdAt || "desconocido"}
- Herramientas Requeridas: ${s.requiresTools && s.requiresTools.length > 0 ? s.requiresTools.join(", ") : "Ninguna"}`
      }).join("\n\n")
      return `Skills dinámicos registrados:\n\n${formatted}`
    } catch (err: any) {
      return `Error listando skills: ${err.message}`
    }
  }
},

{
  name: "skill_view",
  permissionTier: "read",
  description: "Recupera las instrucciones procedimentales detalladas (SOP - Standard Operating Procedure) de un skill dinámico específico por su nombre.",
  inputSchema: {
    type: "object",
    properties: {
      name: {
        type: "string",
        description: "Nombre del skill a consultar (debe empezar con 'skill_', ej: 'skill_commit_build')."
      }
    },
    required: ["name"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    try {
      const name = String(input.name).trim()
      const skill = getDynamicSkill(context.rootDir, name)
      if (!skill) {
        return `El skill '${name}' no existe en el registro.`
      }
      if (!skill.active) {
        return `El skill '${name}' existe pero está inactivo en este momento.`
      }
      // Telemetry: increment use_count with debounce. Skipping writes if the
      // last_used_at is within the debounce window prevents SQLite thrashing
      // when the LLM reads the same skill multiple times in one turn.
      if (shouldRecordSkillUse(skill)) {
        try {
          incrementSkillTelemetry(context.rootDir, name, true)
        } catch (telemetryErr) {
          // Telemetry failures must not break the tool — log and continue.
          context.logger?.warn?.(`skill_view telemetry failed for '${name}': ${telemetryErr}`)
        }
      }
      return `# Skill: ${skill.name} (SOP Manual)\n\n${skill.guide}`
    } catch (err: any) {
      return `Error al consultar el skill: ${err.message}`
    }
  }
},

]
