// Auto-generated by scripts/split_registry.py — do not edit manually.
// Domain: telegram (8 tools)

import {
  mkdirSync,
  writeFileSync,
} from "node:fs"

import {
  join,
} from "node:path"

import {
  TELEGRAM_AUDIO_FORMATS,
  TELEGRAM_VOICE_FORMATS,
  formatToolError,
  isLocalPath,
  isPhotoAlreadySent,
  markPhotoAsSent,
  optionalString,
  requireString,
  resolveMonolitoPath,
  resolveTelegramDownload,
  sanitizeFilenameSegment,
  telegramApiCall,
  telegramApiCallWithFile,
} from "../internal.ts"

import {
  ensureDirs,
} from "../../ipc/protocol.ts"

import {
  readChannelsConfig,
} from "../../channels/config.ts"

import type { ToolDefinition } from "../registry.ts"

export const telegramTools: ToolDefinition[] = [
{
  name: "TelegramSend",
  aliases: ["telegram_send"],
  permissionTier: "edit",
  description: "Send a message to a Telegram chat. Requires Telegram to be configured and enabled via /channels.",
  inputSchema: {
    type: "object",
    properties: {
      chat_id: { type: "number", description: "The Telegram chat ID to send the message to." },
      text: { type: "string", description: "The text message to send." },
      parse_mode: { type: "string", enum: ["Markdown", "MarkdownV2", "HTML"], description: "Optional parse mode for formatting." },
    },
    required: ["chat_id", "text"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  sideEffect: true,
  validate: input => {
    if (typeof input.chat_id !== "number") return "chat_id must be a number"
    if (typeof input.text !== "string" || input.text.length === 0) return "text must be a non-empty string"
    return null
  },
  async run(input) {
    const chatId = input.chat_id as number
    const text = input.text as string
    const parseMode = optionalString(input, "parse_mode")
    const config = readChannelsConfig()
    if (!config.telegram?.enabled || !config.telegram.token) {
      return formatToolError("Telegram is not configured or not enabled. Use /channels to set it up.")
    }
    const body: Record<string, unknown> = { chat_id: chatId, text }
    if (parseMode) body.parse_mode = parseMode
    const response = await fetch(`https://api.telegram.org/bot${config.telegram.token}/sendMessage`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
      signal: AbortSignal.timeout(15000),
    })
    const data = await response.json() as { ok: boolean; result?: unknown; description?: string }
    if (!data.ok) {
      return formatToolError(`Telegram API error: ${data.description ?? response.status}`)
    }
    return { ok: true, chat_id: chatId, message: data.result }
  },
},

{
  name: "TelegramSendAudio",
  aliases: ["telegram_send_audio"],
  permissionTier: "edit",
  description: "Send an audio file to a Telegram chat. Accepts a Telegram file_id, an HTTP URL, or a local file path. Local files should usually be mp3, m4a, or aac.",
  inputSchema: {
    type: "object",
    properties: {
      chat_id: { type: "number", description: "The Telegram chat ID to send the audio to." },
      audio: { type: "string", description: "Telegram file_id, HTTP URL, or local file path." },
      caption: { type: "string", description: "Optional caption for the audio." },
      title: { type: "string", description: "Optional title shown by Telegram." },
      performer: { type: "string", description: "Optional performer shown by Telegram." },
    },
    required: ["chat_id", "audio"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  sideEffect: true,
  validate: input => {
    if (typeof input.chat_id !== "number") return "chat_id must be a number"
    if (typeof input.audio !== "string" || input.audio.length === 0) return "audio must be a non-empty string"
    if (isLocalPath(input.audio) && !TELEGRAM_AUDIO_FORMATS.has((input.audio.split(".").pop() ?? "").toLowerCase())) {
      return "local audio files should use mp3, m4a, or aac"
    }
    return null
  },
  async run(input) {
    const chatId = input.chat_id as number
    const audio = requireString(input, "audio")
    const caption = optionalString(input, "caption")
    const title = optionalString(input, "title")
    const performer = optionalString(input, "performer")
    const config = readChannelsConfig()
    if (!config.telegram?.enabled || !config.telegram.token) {
      return formatToolError("Telegram is not configured or not enabled. Use /channels to set it up.")
    }
    const params: Record<string, unknown> = { chat_id: chatId, audio }
    if (caption) params.caption = caption
    if (title) params.title = title
    if (performer) params.performer = performer
    const data = isLocalPath(audio)
      ? await telegramApiCallWithFile(config.telegram.token, "sendAudio", "audio", audio, params)
      : await telegramApiCall(config.telegram.token, "sendAudio", params)
    if (!data.ok) return formatToolError(`Telegram API error: ${data.description ?? "sendAudio failed"}`)
    return { ok: true, chat_id: chatId, message: data.result }
  },
},

{
  name: "TelegramSendVoice",
  aliases: ["telegram_send_voice"],
  permissionTier: "edit",
  description: "Send a voice note to a Telegram chat. Accepts a Telegram file_id, an HTTP URL, or a local file path. Local files should usually be ogg or opus.",
  inputSchema: {
    type: "object",
    properties: {
      chat_id: { type: "number", description: "The Telegram chat ID to send the voice note to." },
      voice: { type: "string", description: "Telegram file_id, HTTP URL, or local file path." },
      caption: { type: "string", description: "Optional caption for the voice note." },
    },
    required: ["chat_id", "voice"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  sideEffect: true,
  validate: input => {
    if (typeof input.chat_id !== "number") return "chat_id must be a number"
    if (typeof input.voice !== "string" || input.voice.length === 0) return "voice must be a non-empty string"
    if (isLocalPath(input.voice) && !TELEGRAM_VOICE_FORMATS.has((input.voice.split(".").pop() ?? "").toLowerCase())) {
      return "local voice files should use ogg or opus"
    }
    return null
  },
  async run(input) {
    const chatId = input.chat_id as number
    const voice = requireString(input, "voice")
    const caption = optionalString(input, "caption")
    const config = readChannelsConfig()
    if (!config.telegram?.enabled || !config.telegram.token) {
      return formatToolError("Telegram is not configured or not enabled. Use /channels to set it up.")
    }
    const params: Record<string, unknown> = { chat_id: chatId, voice }
    if (caption) params.caption = caption
    const data = isLocalPath(voice)
      ? await telegramApiCallWithFile(config.telegram.token, "sendVoice", "voice", voice, params)
      : await telegramApiCall(config.telegram.token, "sendVoice", params)
    if (!data.ok) return formatToolError(`Telegram API error: ${data.description ?? "sendVoice failed"}`)
    return { ok: true, chat_id: chatId, message: data.result }
  },
},

{
  name: "TelegramSendPhoto",
  permissionTier: "edit",
  description: "Send a photo to a Telegram chat. Accepts a Telegram file_id, an HTTP URL, or a local file path.",
  inputSchema: {
    type: "object",
    properties: {
      chat_id: { type: "number", description: "The Telegram chat ID to send the photo to." },
      photo: { type: "string", description: "Telegram file_id, HTTP URL, or local file path." },
      caption: { type: "string", description: "Optional caption for the photo." },
      parse_mode: { type: "string", enum: ["Markdown", "MarkdownV2", "HTML"], description: "Optional parse mode for the caption." },
      ignore_cache: { type: "boolean", description: "Set to true to ignore send cache and force sending even if sent before." },
    },
    required: ["chat_id", "photo"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  sideEffect: true,
  validate: input => {
    if (typeof input.chat_id !== "number") return "chat_id must be a number"
    if (typeof input.photo !== "string" || input.photo.length === 0) return "photo must be a non-empty string"
    if (input.ignore_cache !== undefined && typeof input.ignore_cache !== "boolean") return "ignore_cache must be a boolean"
    return null
  },
  async run(input, context) {
    const chatId = input.chat_id as number
    const photo = requireString(input, "photo")
    const caption = optionalString(input, "caption")
    const parseMode = optionalString(input, "parse_mode")
    const ignoreCache = input.ignore_cache === true
    const config = readChannelsConfig()
    if (!config.telegram?.enabled || !config.telegram.token) {
      return formatToolError("Telegram is not configured or not enabled. Use /channels to set it up.")
    }

    if (isLocalPath(photo)) {
      const resolvedPath = resolveMonolitoPath(photo)
      if (!ignoreCache && isPhotoAlreadySent(context.rootDir, resolvedPath)) {
        return { ok: true, chat_id: chatId, message: "Photo already sent previously (deduplicated)", deduplicated: true }
      }
      const params: Record<string, unknown> = { chat_id: chatId, photo }
      if (caption) params.caption = caption
      if (parseMode) params.parse_mode = parseMode
      const data = await telegramApiCallWithFile(config.telegram.token, "sendPhoto", "photo", photo, params)
      if (data.ok) markPhotoAsSent(context.rootDir, resolvedPath)
      if (!data.ok) return formatToolError(`Telegram API error: ${data.description ?? "sendPhoto failed"}`)
      return { ok: true, chat_id: chatId, message: data.result }
    }

    const params: Record<string, unknown> = { chat_id: chatId, photo }
    if (caption) params.caption = caption
    if (parseMode) params.parse_mode = parseMode
    const data = await telegramApiCall(config.telegram.token, "sendPhoto", params)
    if (!data.ok) return formatToolError(`Telegram API error: ${data.description ?? "sendPhoto failed"}`)
    return { ok: true, chat_id: chatId, message: data.result }
  },
},

{
  name: "TelegramSendDocument",
  permissionTier: "edit",
  description: "Send a document to a Telegram chat. Accepts a Telegram file_id, an HTTP URL, or a local file path.",
  inputSchema: {
    type: "object",
    properties: {
      chat_id: { type: "number", description: "The Telegram chat ID to send the document to." },
      document: { type: "string", description: "Telegram file_id, HTTP URL, or local file path." },
      caption: { type: "string", description: "Optional caption for the document." },
    },
    required: ["chat_id", "document"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  sideEffect: true,
  validate: input => {
    if (typeof input.chat_id !== "number") return "chat_id must be a number"
    if (typeof input.document !== "string" || input.document.length === 0) return "document must be a non-empty string"
    return null
  },
  async run(input) {
    const chatId = input.chat_id as number
    const document = requireString(input, "document")
    const caption = optionalString(input, "caption")
    const config = readChannelsConfig()
    if (!config.telegram?.enabled || !config.telegram.token) {
      return formatToolError("Telegram is not configured or not enabled. Use /channels to set it up.")
    }
    const params: Record<string, unknown> = { chat_id: chatId, document }
    if (caption) params.caption = caption
    const data = isLocalPath(document)
      ? await telegramApiCallWithFile(config.telegram.token, "sendDocument", "document", document, params)
      : await telegramApiCall(config.telegram.token, "sendDocument", params)
    if (!data.ok) return formatToolError(`Telegram API error: ${data.description ?? "sendDocument failed"}`)
    return { ok: true, chat_id: chatId, message: data.result }
  },
},

{
  name: "TelegramGetFile",
  permissionTier: "read",
  description: "Resolve a Telegram file_id into Telegram file metadata and a downloadable file_path.",
  inputSchema: {
    type: "object",
    properties: {
      file_id: { type: "string", description: "The Telegram file_id to inspect." },
    },
    required: ["file_id"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  validate: input => typeof input.file_id === "string" && input.file_id.length > 0 ? null : "file_id must be a non-empty string",
  async run(input) {
    const fileId = requireString(input, "file_id")
    const config = readChannelsConfig()
    if (!config.telegram?.enabled || !config.telegram.token) {
      return formatToolError("Telegram is not configured or not enabled. Use /channels to set it up.")
    }
    const data = await telegramApiCall(config.telegram.token, "getFile", { file_id: fileId })
    if (!data.ok) return formatToolError(`Telegram API error: ${data.description ?? "getFile failed"}`)
    return { ok: true, file: data.result }
  },
},

{
  name: "DownloadFile",
  permissionTier: "read",
  description: "Download any file from a public HTTP/HTTPS URL into the secure Monolito scratchpad storage and return the local path. Essential for bypassing hotlinking blocks on images or getting documents.",
  inputSchema: {
    type: "object",
    properties: {
      url: { type: "string", description: "The HTTP/HTTPS URL of the file to download." },
      filename: { type: "string", description: "Optional local filename override (including extension). If not provided, a safe name will be generated from the URL path." },
    },
    required: ["url"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  validate: input => {
    if (typeof input.url !== "string" || input.url.length === 0) return "url must be a non-empty string"
    try { new URL(input.url) } catch { return "url must be a valid HTTP/HTTPS URL" }
    if (input.filename !== undefined && typeof input.filename !== "string") return "filename must be a string"
    return null
  },
  async run(input, context) {
    const url = requireString(input, "url")
    const filename = optionalString(input, "filename")
    
    const paths = ensureDirs(context.rootDir)
    const downloadsDir = join(paths.scratchpadDir, "downloads")
    
    const startedAt = Date.now()
    try {
      const response = await fetch(url, {
        headers: {
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
          "Accept": "*/*",
        },
        signal: AbortSignal.timeout(30_000),
      })
      
      if (!response.ok) {
        throw new Error(`HTTP Error ${response.status}: ${response.statusText}`)
      }
      
      const contentType = response.headers.get("content-type") ?? "application/octet-stream"
      const buffer = Buffer.from(await response.arrayBuffer())
      
      // Determinar nombre del archivo
      let finalName = filename
      if (!finalName) {
        const parsedUrl = new URL(url)
        const urlSegment = parsedUrl.pathname.split("/").at(-1)
        finalName = urlSegment && urlSegment.includes(".")
          ? sanitizeFilenameSegment(urlSegment)
          : `download-${Date.now()}`
      }
      
      // Asegurar extensión adecuada si falta en la inferencia básica
      if (!finalName.includes(".") && contentType !== "application/octet-stream") {
        const mimeExt = contentType.split(";")[0]?.split("/")[1]
        if (mimeExt) finalName = `${finalName}.${mimeExt}`
      }
      
      mkdirSync(downloadsDir, { recursive: true })
      const localPath = join(downloadsDir, finalName)
      writeFileSync(localPath, buffer)
      
      return {
        ok: true,
        url,
        local_path: localPath,
        bytes: buffer.length,
        content_type: contentType,
        durationMs: Date.now() - startedAt,
      }
    } catch (error: any) {
      return formatToolError(`Download failed: ${error.message || error}`)
    }
  },
},

{
  name: "TelegramDownloadFile",
  permissionTier: "edit",
  description: "Download a Telegram file_id into Monolito scratchpad storage and return the local path. IMPORTANT: Do NOT execute this tool for standard attachments that already provide a 'local_path' attribute, as they are downloaded automatically. Only execute this tool as a manual override when a Telegram attachment exceeds the auto-download size limit (status='size_limit_exceeded') and the user explicitly confirms they want to proceed.",
  inputSchema: {
    type: "object",
    properties: {
      file_id: { type: "string", description: "The Telegram file_id to download." },
      filename: { type: "string", description: "Optional local filename override." },
    },
    required: ["file_id"],
    additionalProperties: false,
  },
  concurrencySafe: false,
  validate: input => typeof input.file_id === "string" && input.file_id.length > 0 ? null : "file_id must be a non-empty string",
  async run(input, context) {
    const fileId = requireString(input, "file_id")
    const filename = optionalString(input, "filename")
    const config = readChannelsConfig()
    if (!config.telegram?.enabled || !config.telegram.token) {
      return formatToolError("Telegram is not configured or not enabled. Use /channels to set it up.")
    }
    return await resolveTelegramDownload(config.telegram.token, fileId, context.rootDir, filename)
  },
},

]
