// Auto-generated by scripts/split_registry.py — do not edit manually.
// Domain: telegram (8 tools)

import {
  mkdirSync,
  writeFileSync,
} from "node:fs"

import {
  join,
} from "node:path"

import {
  TELEGRAM_AUDIO_FORMATS,
  TELEGRAM_VOICE_FORMATS,
  formatToolError,
  isAudioAlreadySent,
  isLocalPath,
  isPhotoAlreadySent,
  markAudioAsSent,
  markPhotoAsSent,
  optionalNumber,
  optionalString,
  requireString,
  resolveMonolitoPath,
  resolveTelegramDownload,
  sanitizeFilenameSegment,
  telegramApiCall,
  telegramApiCallWithFile,
} from "../internal.ts"

import {
  ensureDirs,
} from "../../ipc/protocol.ts"

import {
  readChannelsConfig,
} from "../../channels/config.ts"

import {
  persistTelegramSentPhoto,
  listTelegramSentPhotos,
} from "../../session/store.ts"

import type { ToolDefinition, ToolContext } from "../internal.ts"

interface TelegramPhotoResult {
  ok: boolean
  result?: {
    message_id?: number
    photo?: Array<{ file_id: string; width?: number; height?: number; file_size?: number }>
    caption?: string
  }
  description?: string
}

// -----------------------------------------------------------------------------
// Browser-required host detection
//
// Some image CDNs (Reddit, Pinterest, certain Imgur paths) block generic
// bot user-agents with HTTP 403 even when the file is publicly accessible.
// They need a full browser-shaped request (Referer + Accept-Language +
// Sec-Fetch-*) and a Referer that matches a "real" referring page on the
// same site. We retry exactly once with a host-appropriate Referer before
// surfacing the 403 to the model.
//
// The pure helpers (isBrowserRequiredHost, refererForHost, isHtmlContentType,
// isJsonErrorBody, looksLikeTelegramFileId) and the network probe
// (probeImageUrl) live in ./telegramGuards.ts so they can be unit-tested
// without dragging in the full tool registry.
// -----------------------------------------------------------------------------

import {
  isBrowserRequiredHost,
  refererForHost,
  isHtmlContentType,
  isJsonErrorBody,
  looksLikeTelegramFileId,
  probeImageUrl,
} from "./telegramGuards.ts"

// Re-export the guards so existing call sites keep working.
export { isBrowserRequiredHost, refererForHost, isHtmlContentType, isJsonErrorBody, looksLikeTelegramFileId, probeImageUrl }

function extractTelegramPhotoFields(data: TelegramPhotoResult): { messageId: number | null; fileId: string | null } {
  if (!data?.result) return { messageId: null, fileId: null }
  const photos = Array.isArray(data.result.photo) ? data.result.photo : []
  const largest = photos[photos.length - 1]
  const messageId = typeof data.result.message_id === "number" ? data.result.message_id : null
  const fileId = largest?.file_id ?? null
  return { messageId, fileId }
}

function persistSentPhoto(rootDir: string, row: { chatId: number; messageId: number; fileId: string | null; localPath: string; caption: string | null }) {
  try {
    persistTelegramSentPhoto(rootDir, row)
  } catch (err) {
    // Persistence is best-effort: a DB hiccup must not make the tool
    // report the photo as unsent when Telegram already accepted it.
    // Surface a warning so the operator can investigate, but do not
    // fail the tool result.
    console.warn(`[TelegramSendPhoto] failed to persist sent photo: ${err instanceof Error ? err.message : String(err)}`)
  }
}

type TelegramSendMessageResult = {
  ok: boolean
  result?: unknown
  description?: string
}

async function postTelegramSendMessage(
  token: string,
  body: Record<string, unknown>,
): Promise<TelegramSendMessageResult> {
  const response = await fetch(`https://api.telegram.org/bot${token}/sendMessage`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
    signal: AbortSignal.timeout(15000),
  })
  return await response.json() as TelegramSendMessageResult
}

async function sendTelegramChatMessage(
  token: string,
  chatId: number,
  text: string,
  parseMode?: string,
): Promise<{ ok: true; message: unknown; parse_mode_used?: string } | { ok: false; error: string }> {
  const attempts: Array<{ parse_mode?: string; label: string }> = []
  if (parseMode) attempts.push({ parse_mode: parseMode, label: parseMode })
  attempts.push({ label: "plain" })

  let lastError = "Unknown Telegram API error"
  for (const attempt of attempts) {
    const body: Record<string, unknown> = { chat_id: chatId, text }
    if (attempt.parse_mode) body.parse_mode = attempt.parse_mode
    const data = await postTelegramSendMessage(token, body)
    if (data.ok) {
      return {
        ok: true,
        message: data.result,
        parse_mode_used: attempt.parse_mode ?? "plain",
      }
    }
    lastError = data.description ?? "Unknown Telegram API error"
    const parseEntityFailure = /can't parse entities|Can't find end of the entity/i.test(lastError)
    if (!parseEntityFailure && attempt.parse_mode) break
  }
  return { ok: false, error: `Telegram API error: ${lastError}` }
}

const legacyTelegramSendTools: ToolDefinition[] = [
{
  name: "TelegramSend",
  aliases: ["telegram_send"],
  permissionTier: "edit",
  description:
    "Send a message to a Telegram chat. Requires Telegram to be configured and enabled via /channels. " +
    "Default is plain text (no parse_mode). For long URL lists, prefer plain text or TelegramSendDocument — " +
    "avoid MarkdownV2 unless you can escape every reserved character.",
  inputSchema: {
    type: "object",
    properties: {
      chat_id: { type: "number", description: "The Telegram chat ID to send the message to." },
      text: { type: "string", description: "The text message to send." },
      parse_mode: { type: "string", enum: ["Markdown", "MarkdownV2", "HTML"], description: "Optional parse mode. On entity parse errors, retries as plain text automatically." },
    },
    required: ["chat_id", "text"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  sideEffect: true,
  validate: input => {
    if (typeof input.chat_id !== "number") return "chat_id must be a number"
    if (typeof input.text !== "string" || input.text.length === 0) return "text must be a non-empty string"
    return null
  },
  async run(input) {
    const chatId = input.chat_id as number
    const text = input.text as string
    const parseMode = optionalString(input, "parse_mode")
    const config = readChannelsConfig()
    if (!config.telegram?.enabled || !config.telegram.token) {
      return formatToolError("Telegram is not configured or not enabled. Use /channels to set it up.")
    }
    const result = await sendTelegramChatMessage(config.telegram.token, chatId, text, parseMode)
    if (!result.ok) {
      return formatToolError(result.error)
    }
    return {
      ok: true,
      chat_id: chatId,
      message: result.message,
      parse_mode_used: result.parse_mode_used,
    }
  },
},

{
  name: "TelegramSendAudio",
  aliases: ["telegram_send_audio"],
  permissionTier: "edit",
  description: "Send an audio file to a Telegram chat. Accepts a Telegram file_id, an HTTP URL, or a local file path (use the local_path returned by GenerateSpeech, VoiceClone, or scratchpad files). Local files should be mp3, m4a, or aac. The `audio` field MUST be a non-empty string — do NOT pass an empty string or omit the field; if the path is unknown, fetch the file first with Read/Glob.",
  inputSchema: {
    type: "object",
    properties: {
      chat_id: { type: "number", description: "The Telegram chat ID to send the audio to." },
      audio: { type: "string", description: "Telegram file_id, HTTP URL, or local file path." },
      caption: { type: "string", description: "Optional caption for the audio." },
      title: { type: "string", description: "Optional title shown by Telegram." },
      performer: { type: "string", description: "Optional performer shown by Telegram." },
    },
    required: ["chat_id", "audio"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  sideEffect: true,
  validate: input => {
    if (typeof input.chat_id !== "number") return "chat_id must be a number"
    if (typeof input.audio !== "string" || input.audio.length === 0) return "audio must be a non-empty string"
    if (isLocalPath(input.audio) && !TELEGRAM_AUDIO_FORMATS.has((input.audio.split(".").pop() ?? "").toLowerCase())) {
      return "local audio files should use mp3, m4a, or aac"
    }
    return null
  },
  async run(input, context) {
    const chatId = input.chat_id as number
    const audio = requireString(input, "audio")
    const caption = optionalString(input, "caption")
    const title = optionalString(input, "title")
    const performer = optionalString(input, "performer")
    const config = readChannelsConfig()
    if (!config.telegram?.enabled || !config.telegram.token) {
      return formatToolError("Telegram is not configured or not enabled. Use /channels to set it up.")
    }
    // Fast-path dedupe: skip the API call when the same local audio file
    // was already sent in this workspace. Prevents the model from
    // regenerating an identical audio clip after a guard re-feed and
    // delivering it twice (observed 2026-06-09 with message_ids 21213
    // and 21215 in the same turn).
    if (context && isLocalPath(audio) && isAudioAlreadySent(context.rootDir, audio)) {
      return { ok: true, chat_id: chatId, message: "Audio already sent previously (deduplicated)", deduplicated: true }
    }
    const params: Record<string, unknown> = { chat_id: chatId, audio }
    if (caption) params.caption = caption
    if (title) params.title = title
    if (performer) params.performer = performer
    const data = isLocalPath(audio)
      ? await telegramApiCallWithFile(config.telegram.token, "sendAudio", "audio", audio, params)
      : await telegramApiCall(config.telegram.token, "sendAudio", params)
    if (!data.ok) return formatToolError(`Telegram API error: ${data.description ?? "sendAudio failed"}`)
    if (context && isLocalPath(audio)) markAudioAsSent(context.rootDir, audio)
    return { ok: true, chat_id: chatId, message: data.result }
  },
},

{
  name: "TelegramSendVoice",
  aliases: ["telegram_send_voice"],
  permissionTier: "edit",
  description: "Send a voice note to a Telegram chat. Accepts a Telegram file_id, an HTTP URL, or a local file path (use the local_path returned by GenerateSpeech or scratchpad files). Local files should be ogg or opus. The `voice` field MUST be a non-empty string — do NOT pass an empty string or omit the field.",
  inputSchema: {
    type: "object",
    properties: {
      chat_id: { type: "number", description: "The Telegram chat ID to send the voice note to." },
      voice: { type: "string", description: "Telegram file_id, HTTP URL, or local file path." },
      caption: { type: "string", description: "Optional caption for the voice note." },
    },
    required: ["chat_id", "voice"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  sideEffect: true,
  validate: input => {
    if (typeof input.chat_id !== "number") return "chat_id must be a number"
    if (typeof input.voice !== "string" || input.voice.length === 0) return "voice must be a non-empty string"
    if (isLocalPath(input.voice) && !TELEGRAM_VOICE_FORMATS.has((input.voice.split(".").pop() ?? "").toLowerCase())) {
      return "local voice files should use ogg or opus"
    }
    return null
  },
  async run(input, context) {
    const chatId = input.chat_id as number
    const voice = requireString(input, "voice")
    const caption = optionalString(input, "caption")
    const config = readChannelsConfig()
    if (!config.telegram?.enabled || !config.telegram.token) {
      return formatToolError("Telegram is not configured or not enabled. Use /channels to set it up.")
    }
    // Fast-path dedupe: skip the API call when the same local voice file
    // was already sent in this workspace. Prevents the model from
    // regenerating an identical voice note after a guard re-feed and
    // delivering it twice (observed 2026-06-09 with message_ids 21213
    // and 21215 in the same turn).
    if (context && isLocalPath(voice) && isAudioAlreadySent(context.rootDir, voice)) {
      return { ok: true, chat_id: chatId, message: "Voice already sent previously (deduplicated)", deduplicated: true }
    }
    const params: Record<string, unknown> = { chat_id: chatId, voice }
    if (caption) params.caption = caption
    const data = isLocalPath(voice)
      ? await telegramApiCallWithFile(config.telegram.token, "sendVoice", "voice", voice, params)
      : await telegramApiCall(config.telegram.token, "sendVoice", params)
    if (!data.ok) return formatToolError(`Telegram API error: ${data.description ?? "sendVoice failed"}`)
    if (context && isLocalPath(voice)) markAudioAsSent(context.rootDir, voice)
    return { ok: true, chat_id: chatId, message: data.result }
  },
},

{
  name: "TelegramSendPhoto",
  permissionTier: "edit",
  description: "Send a photo to a Telegram chat. Accepts a Telegram file_id, an HTTP URL, or a local file path.",
  inputSchema: {
    type: "object",
    properties: {
      chat_id: { type: "number", description: "The Telegram chat ID to send the photo to." },
      photo: { type: "string", description: "Telegram file_id, HTTP URL, or local file path." },
      caption: { type: "string", description: "Optional caption for the photo." },
      parse_mode: { type: "string", enum: ["Markdown", "MarkdownV2", "HTML"], description: "Optional parse mode for the caption." },
      ignore_cache: { type: "boolean", description: "Set to true to ignore send cache and force sending even if sent before." },
    },
    required: ["chat_id", "photo"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  sideEffect: true,
  validate: input => {
    if (typeof input.chat_id !== "number") return "chat_id must be a number"
    if (typeof input.photo !== "string" || input.photo.length === 0) return "photo must be a non-empty string"
    if (input.ignore_cache !== undefined && typeof input.ignore_cache !== "boolean") return "ignore_cache must be a boolean"
    return null
  },
  async run(input, context) {
    const chatId = input.chat_id as number
    const photo = requireString(input, "photo")
    const caption = optionalString(input, "caption")
    const parseMode = optionalString(input, "parse_mode")
    const ignoreCache = input.ignore_cache === true
    const config = readChannelsConfig()
    if (!config.telegram?.enabled || !config.telegram.token) {
      return formatToolError("Telegram is not configured or not enabled. Use /channels to set it up.")
    }

    // Pre-check: if the user passed a URL (not a local path or Telegram
    // file_id), do a fast HEAD/GET-range probe to confirm the resource is
    // actually a direct image. Without this, the runtime passes the URL
    // straight to Telegram's API, which fetches it server-side and rejects
    // HTML/login pages with "Bad Request: wrong type of the web page
    // content" — observed 2026-06-09 when 4 of 10 fan-art URLs were 403
    // login walls from Reddit/Pinterest. The pre-check is fail-soft: if
    // the probe itself errors (DNS, timeout, blocked), we let the call
    // through and let Telegram be the authority.
    if (!isLocalPath(photo) && /^https?:\/\//i.test(photo) && !looksLikeTelegramFileId(photo)) {
      const probe = await probeImageUrl(photo)
      if (probe && !probe.ok) {
        return formatToolError(
          `TelegramSendPhoto URL pre-check failed for ${photo}: ${probe.reason}. ` +
          `Use \`DownloadFile\` first to retrieve the resource to a local_path, ` +
          `then pass that local_path to \`TelegramSendPhoto\`.`,
        )
      }
    }

    if (isLocalPath(photo)) {
      const resolvedPath = resolveMonolitoPath(photo)
      if (!ignoreCache && isPhotoAlreadySent(context.rootDir, resolvedPath)) {
        return { ok: true, chat_id: chatId, message: "Photo already sent previously (deduplicated)", deduplicated: true }
      }
      const params: Record<string, unknown> = { chat_id: chatId, photo }
      if (caption) params.caption = caption
      if (parseMode) params.parse_mode = parseMode
      const data = (await telegramApiCallWithFile(config.telegram.token, "sendPhoto", "photo", photo, params)) as TelegramPhotoResult
      if (!data?.ok) {
        return formatToolError(`Telegram API error: ${data?.description ?? "sendPhoto failed"}`)
      }
      const { messageId, fileId } = extractTelegramPhotoFields(data)
      // Hard failure: Telegram accepted the upload but did not return
      // a usable message_id. We must NOT report ok:true in that case —
      // the 25-may-2026 incident showed that an undocumented success
      // path can leave the user staring at a chat with nothing
      // attached while the assistant announces "ya te mandé". Surface
      // the partial result so the orchestrator can retry with
      // ignore_cache=true or report the failure.
      if (messageId === null) {
        return formatToolError(
          `Telegram returned ok=true but no message_id. The photo may not have been delivered. ` +
          `Response: ${JSON.stringify(data.result).slice(0, 200)}`,
        )
      }
      markPhotoAsSent(context.rootDir, resolvedPath)
      persistSentPhoto(context.rootDir, {
        chatId,
        messageId,
        fileId,
        localPath: resolvedPath,
        caption: caption ?? null,
      })
      return {
        ok: true,
        chat_id: chatId,
        message_id: messageId,
        file_id: fileId,
        local_path: resolvedPath,
        message: data.result,
      }
    }

    const params: Record<string, unknown> = { chat_id: chatId, photo }
    if (caption) params.caption = caption
    if (parseMode) params.parse_mode = parseMode
    const data = (await telegramApiCall(config.telegram.token, "sendPhoto", params)) as TelegramPhotoResult
    if (!data?.ok) {
      return formatToolError(`Telegram API error: ${data?.description ?? "sendPhoto failed"}`)
    }
    const { messageId, fileId } = extractTelegramPhotoFields(data)
    if (messageId === null) {
      return formatToolError(
        `Telegram returned ok=true but no message_id for the remote photo. ` +
        `Response: ${JSON.stringify(data.result).slice(0, 200)}`,
      )
    }
    // For remote/file_id/URL inputs we don't have a local_path; persist
    // a synthetic marker so the post-send lookup can still find it.
    persistSentPhoto(context.rootDir, {
      chatId,
      messageId,
      fileId,
      localPath: `<remote:${photo.slice(0, 200)}>`,
      caption: caption ?? null,
    })
    return {
      ok: true,
      chat_id: chatId,
      message_id: messageId,
      file_id: fileId,
      message: data.result,
    }
  },
},

{
  name: "TelegramSendDocument",
  permissionTier: "edit",
  description: "Send a document to a Telegram chat. Accepts a Telegram file_id, an HTTP URL, or a local file path.",
  inputSchema: {
    type: "object",
    properties: {
      chat_id: { type: "number", description: "The Telegram chat ID to send the document to." },
      document: { type: "string", description: "Telegram file_id, HTTP URL, or local file path." },
      caption: { type: "string", description: "Optional caption for the document." },
    },
    required: ["chat_id", "document"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  sideEffect: true,
  validate: input => {
    if (typeof input.chat_id !== "number") return "chat_id must be a number"
    if (typeof input.document !== "string" || input.document.length === 0) return "document must be a non-empty string"
    return null
  },
  async run(input) {
    const chatId = input.chat_id as number
    const document = requireString(input, "document")
    const caption = optionalString(input, "caption")
    const config = readChannelsConfig()
    if (!config.telegram?.enabled || !config.telegram.token) {
      return formatToolError("Telegram is not configured or not enabled. Use /channels to set it up.")
    }
    const params: Record<string, unknown> = { chat_id: chatId, document }
    if (caption) params.caption = caption
    const data = isLocalPath(document)
      ? await telegramApiCallWithFile(config.telegram.token, "sendDocument", "document", document, params)
      : await telegramApiCall(config.telegram.token, "sendDocument", params)
    if (!data.ok) return formatToolError(`Telegram API error: ${data.description ?? "sendDocument failed"}`)
    return { ok: true, chat_id: chatId, message: data.result }
  },
},

]

const legacyTelegramGetTools: ToolDefinition[] = [
{
  name: "TelegramGetRecentPhotos",
  permissionTier: "read",
  description: "Lista las últimas fotos enviadas a un chat de Telegram, devolviendo `file_id`, `message_id`, `local_path` y `caption` por cada una. Usala cuando el usuario pida verificar o revisar una foto enviada previamente (ej. 'verifica la última foto que te mandé'). Para analizar visualmente la foto, pasá el `file_id` o `local_path` a `VisionAnalyze`.",
  inputSchema: {
    type: "object",
    properties: {
      chat_id: { type: "number", description: "Telegram chat ID. Si se omite, devuelve las últimas fotos de todos los chats." },
      limit: { type: "number", description: "Cantidad máxima de fotos a devolver (default 5, máximo 20)." },
    },
    additionalProperties: false,
  },
  concurrencySafe: true,
  validate: input => {
    if (input.chat_id !== undefined && typeof input.chat_id !== "number") return "chat_id must be a number"
    if (input.limit !== undefined && (typeof input.limit !== "number" || input.limit < 1)) return "limit must be a positive number"
    return null
  },
  async run(input, context) {
    const chatId = typeof input.chat_id === "number" ? input.chat_id : null
    const requestedLimit = optionalNumber(input, "limit") ?? 5
    const limit = Math.min(Math.max(requestedLimit, 1), 20)
    try {
      const rows = listTelegramSentPhotos(context.rootDir, chatId, limit)
      return {
        ok: true,
        count: rows.length,
        photos: rows.map(r => ({
          message_id: r.message_id,
          file_id: r.file_id,
          local_path: r.local_path.startsWith("<remote:") ? null : r.local_path,
          caption: r.caption,
          sent_at: r.sent_at,
          chat_id: r.chat_id,
        })),
      }
    } catch (err: any) {
      return formatToolError(`Failed to read recent photos: ${err?.message ?? String(err)}`)
    }
  },
},

{
  name: "TelegramGetFile",
  permissionTier: "read",
  description: "Resolve a Telegram file_id into Telegram file metadata and a downloadable file_path.",
  inputSchema: {
    type: "object",
    properties: {
      file_id: { type: "string", description: "The Telegram file_id to inspect." },
    },
    required: ["file_id"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  validate: input => typeof input.file_id === "string" && input.file_id.length > 0 ? null : "file_id must be a non-empty string",
  async run(input) {
    const fileId = requireString(input, "file_id")
    const config = readChannelsConfig()
    if (!config.telegram?.enabled || !config.telegram.token) {
      return formatToolError("Telegram is not configured or not enabled. Use /channels to set it up.")
    }
    const data = await telegramApiCall(config.telegram.token, "getFile", { file_id: fileId })
    if (!data.ok) return formatToolError(`Telegram API error: ${data.description ?? "getFile failed"}`)
    return { ok: true, file: data.result }
  },
},

]

function runLegacyTelegramTool(tools: ToolDefinition[], legacyName: string, input: Record<string, unknown>, context: ToolContext) {
  const tool = tools.find(t => t.name === legacyName)
  if (!tool?.run) return formatToolError(`Internal Telegram handler missing: ${legacyName}`)
  return tool.run(input, context)
}

function resolveTelegramSendAction(invoked: string, input: Record<string, unknown>): string {
  const aliasMap: Record<string, string> = {
    TelegramSend: "send_text",
    telegram_send: "send_text",
    TelegramSendPhoto: "send_photo",
    TelegramSendAudio: "send_audio",
    telegram_send_audio: "send_audio",
    TelegramSendVoice: "send_voice",
    telegram_send_voice: "send_voice",
    TelegramSendDocument: "send_document",
  }
  if (aliasMap[invoked]) return aliasMap[invoked]
  const explicit = optionalString(input, "action")
  if (explicit?.startsWith("send_")) return explicit
  if (typeof input.text === "string") return "send_text"
  if (typeof input.photo === "string") return "send_photo"
  if (typeof input.audio === "string") return "send_audio"
  if (typeof input.voice === "string") return "send_voice"
  if (typeof input.document === "string") return "send_document"
  return "send_text"
}

const SEND_ACTION_LEGACY: Record<string, string> = {
  send_text: "TelegramSend",
  send_photo: "TelegramSendPhoto",
  send_audio: "TelegramSendAudio",
  send_voice: "TelegramSendVoice",
  send_document: "TelegramSendDocument",
}

function resolveTelegramGetAction(invoked: string, input: Record<string, unknown>): string {
  if (invoked === "TelegramGetRecentPhotos") return "recent_photos"
  if (invoked === "TelegramGetFile") return "get_file"
  const explicit = optionalString(input, "action")
  if (explicit === "recent_photos" || explicit === "get_file") return explicit
  if (typeof input.file_id === "string" && input.chat_id === undefined && input.limit === undefined) return "get_file"
  return "recent_photos"
}

const GET_ACTION_LEGACY: Record<string, string> = {
  recent_photos: "TelegramGetRecentPhotos",
  get_file: "TelegramGetFile",
}

export const telegramTools: ToolDefinition[] = [
{
  name: "Telegram",
  aliases: [
    "TelegramSend", "telegram_send",
    "TelegramSendPhoto",
    "TelegramSendAudio", "telegram_send_audio",
    "TelegramSendVoice", "telegram_send_voice",
    "TelegramSendDocument",
  ],
  permissionTier: "edit",
  sideEffect: true,
  description:
    "Send content to a Telegram chat. action=send_text|send_photo|send_voice|send_audio|send_document. " +
    "Legacy alias names (TelegramSendPhoto, etc.) still work. Requires /channels Telegram config.",
  inputSchema: {
    type: "object",
    properties: {
      action: { type: "string", enum: ["send_text", "send_photo", "send_voice", "send_audio", "send_document"] },
      chat_id: { type: "number" },
      text: { type: "string" },
      photo: { type: "string" },
      voice: { type: "string" },
      audio: { type: "string" },
      document: { type: "string" },
      caption: { type: "string" },
      parse_mode: { type: "string", enum: ["Markdown", "MarkdownV2", "HTML"] },
      title: { type: "string" },
      performer: { type: "string" },
      ignore_cache: { type: "boolean" },
    },
    additionalProperties: false,
  },
  concurrencySafe: true,
  validate: input => {
    const legacyName = SEND_ACTION_LEGACY[resolveTelegramSendAction("TelegramSend", input as Record<string, unknown>)] ?? "TelegramSend"
    const legacy = legacyTelegramSendTools.find(t => t.name === legacyName)
    return legacy?.validate ? legacy.validate(input) : null
  },
  async run(input, context) {
    const invoked = context.invokedAs ?? "Telegram"
    const action = resolveTelegramSendAction(invoked, input as Record<string, unknown>)
    const legacyName = SEND_ACTION_LEGACY[action]
    if (!legacyName) return formatToolError(`Unknown Telegram send action: ${action}`)
    return runLegacyTelegramTool(legacyTelegramSendTools, legacyName, input as Record<string, unknown>, context)
  },
},
{
  name: "TelegramGet",
  aliases: ["TelegramGetRecentPhotos", "TelegramGetFile"],
  permissionTier: "read",
  description: "Read Telegram state. action=recent_photos|get_file.",
  inputSchema: {
    type: "object",
    properties: {
      action: { type: "string", enum: ["recent_photos", "get_file"] },
      chat_id: { type: "number" },
      limit: { type: "number" },
      file_id: { type: "string" },
    },
    additionalProperties: false,
  },
  concurrencySafe: true,
  validate: input => {
    const legacyName = GET_ACTION_LEGACY[resolveTelegramGetAction("TelegramGetRecentPhotos", input as Record<string, unknown>)] ?? "TelegramGetRecentPhotos"
    const legacy = legacyTelegramGetTools.find(t => t.name === legacyName)
    return legacy?.validate ? legacy.validate(input) : null
  },
  async run(input, context) {
    const invoked = context.invokedAs ?? "TelegramGet"
    const action = resolveTelegramGetAction(invoked, input as Record<string, unknown>)
    const legacyName = GET_ACTION_LEGACY[action]
    if (!legacyName) return formatToolError(`Unknown Telegram get action: ${action}`)
    return runLegacyTelegramTool(legacyTelegramGetTools, legacyName, input as Record<string, unknown>, context)
  },
},
{
  name: "DownloadFile",
  permissionTier: "read",
  description: "Download any file from a public HTTP/HTTPS URL into the secure Monolito scratchpad storage and return the local path. Essential for bypassing hotlinking blocks on images or getting documents.",
  inputSchema: {
    type: "object",
    properties: {
      url: { type: "string", description: "The HTTP/HTTPS URL of the file to download." },
      filename: { type: "string", description: "Optional local filename override (including extension). If not provided, a safe name will be generated from the URL path." },
    },
    required: ["url"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  validate: input => {
    if (typeof input.url !== "string" || input.url.length === 0) return "url must be a non-empty string"
    try { new URL(input.url) } catch { return "url must be a valid HTTP/HTTPS URL" }
    if (input.filename !== undefined && typeof input.filename !== "string") return "filename must be a string"
    return null
  },
  async run(input, context) {
    const url = requireString(input, "url")
    const filename = optionalString(input, "filename")

    const paths = ensureDirs(context.rootDir)
    const downloadsDir = join(paths.scratchpadDir, "downloads")

    const startedAt = Date.now()
    try {
      // Browser-required hosts block generic bot user-agents with 403. Reddit
      // and Pinterest in particular need a full browser-shaped request
      // (Referer + Accept-Language + Sec-Fetch-*). Without these the host
      // returns 403 even though the file is publicly accessible — observed
      // 2026-06-09 when 4 of 10 fan-art downloads failed this way.
      const parsedUrl = new URL(url)
      const browserHeaders = (referer: string) => ({
        "User-Agent":
          "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
        "Accept": "*/*",
        "Accept-Language": "en-US,en;q=0.9",
        "Referer": referer,
        "Sec-Fetch-Dest": "document",
        "Sec-Fetch-Mode": "navigate",
        "Sec-Fetch-Site": "cross-site",
        "Sec-Fetch-User": "?1",
        "Upgrade-Insecure-Requests": "1",
      })
      // First attempt: minimal browser-shaped headers with the URL's own
      // origin as Referer. Works for most CDNs (i.redd.it, imgur direct,
      // i.pinimg.com).
      let response = await fetch(url, {
        headers: browserHeaders(parsedUrl.origin + "/"),
        signal: AbortSignal.timeout(30_000),
        redirect: "follow",
      })
      // Second attempt (only on 403 from a known bot-blocking host): use
      // a domain-appropriate Referer. Many image CDNs (preview.redd.it,
      // b.thumbs.redditmedia.com) require Referer=https://www.reddit.com/
      // to even serve the bytes.
      if (response.status === 403 && isBrowserRequiredHost(parsedUrl.hostname)) {
        response = await fetch(url, {
          headers: browserHeaders(refererForHost(parsedUrl.hostname)),
          signal: AbortSignal.timeout(30_000),
          redirect: "follow",
        })
      }

      if (!response.ok) {
        const statusNote = response.status === 403
          ? ` (host likely blocks bot user-agents; even the browser-shaped retry was rejected)`
          : ""
        throw new Error(`HTTP Error ${response.status}: ${response.statusText}${statusNote}`)
      }

      const contentType = response.headers.get("content-type") ?? "application/octet-stream"
      const buffer = Buffer.from(await response.arrayBuffer())

      // Some 403 pages still return 200 with an HTML login wall. If the
      // resource is not a sensible content-type, fail with a clear message
      // so the model doesn't pass a login page to TelegramSendPhoto and
      // get back 'wrong type of the web page content'.
      if (isHtmlContentType(contentType) || isJsonErrorBody(buffer, contentType)) {
        return formatToolError(
          `Download failed: ${url} returned a ${contentType} response, not a direct file. ` +
          `The host is probably serving a login page or API error JSON. ` +
          `Bytes received: ${buffer.length}. ` +
          `Try a different source URL (e.g. an \`i.redd.it\` direct link, an \`imgur.com\` direct, or a smaller image).`,
        )
      }

      // Determinar nombre del archivo
      let finalName = filename
      if (!finalName) {
        const urlSegment = parsedUrl.pathname.split("/").at(-1)
        finalName = urlSegment && urlSegment.includes(".")
          ? sanitizeFilenameSegment(urlSegment)
          : `download-${Date.now()}`
      }

      // Asegurar extensión adecuada si falta en la inferencia básica
      if (!finalName.includes(".") && contentType !== "application/octet-stream") {
        const mimeExt = contentType.split(";")[0]?.split("/")[1]
        if (mimeExt) finalName = `${finalName}.${mimeExt}`
      }

      mkdirSync(downloadsDir, { recursive: true })
      const localPath = join(downloadsDir, finalName)
      writeFileSync(localPath, buffer)

      return {
        ok: true,
        url,
        local_path: localPath,
        bytes: buffer.length,
        content_type: contentType,
        durationMs: Date.now() - startedAt,
      }
    } catch (error: any) {
      return formatToolError(`Download failed: ${error.message || error}`)
    }
  },
},

{
  name: "TelegramDownloadFile",
  permissionTier: "edit",
  description: "Download a Telegram file_id into Monolito scratchpad storage and return the local path. IMPORTANT: Do NOT execute this tool for standard attachments that already provide a 'local_path' attribute, as they are downloaded automatically. Only execute this tool as a manual override when a Telegram attachment exceeds the auto-download size limit (status='size_limit_exceeded') and the user explicitly confirms they want to proceed.",
  inputSchema: {
    type: "object",
    properties: {
      file_id: { type: "string", description: "The Telegram file_id to download." },
      filename: { type: "string", description: "Optional local filename override." },
    },
    required: ["file_id"],
    additionalProperties: false,
  },
  concurrencySafe: false,
  validate: input => typeof input.file_id === "string" && input.file_id.length > 0 ? null : "file_id must be a non-empty string",
  async run(input, context) {
    const fileId = requireString(input, "file_id")
    const filename = optionalString(input, "filename")
    const config = readChannelsConfig()
    if (!config.telegram?.enabled || !config.telegram.token) {
      return formatToolError("Telegram is not configured or not enabled. Use /channels to set it up.")
    }
    return await resolveTelegramDownload(config.telegram.token, fileId, context.rootDir, filename)
  },
},

]
