// Auto-generated by scripts/split_registry.py — do not edit manually.
// Domain: todo (2 tools)

import {
  randomUUID,
} from "node:crypto"

import {
  join,
} from "node:path"

import {
  formatToolError,
  optionalString,
} from "../internal.ts"

import {
  getDb,
  listSessionTasks,
  writeSessionTask,
} from "../../session/store.ts"
import type { SessionTask } from "../../session/store.ts"

import type { ToolDefinition } from "../registry.ts"

export const todoTools: ToolDefinition[] = [
{
  name: "TodoWrite",
  permissionTier: "edit",
  description: "Replace the session task list with the supplied full state. Use this tool proactively for complex multi-step work (3+ steps) so the user can see progress. Input MUST be an object `{ todos: [{ content, activeForm, status: 'pending' | 'in_progress' | 'completed' }] }`. The `todos` key and the `status` field on every item are REQUIRED — omitting them produces a confusing 'requires at least one todo' error. Each todo: `content` (imperative, e.g. 'Run tests'), `activeForm` (present continuous, e.g. 'Running tests'), `status` (one of pending|in_progress|completed). Exactly ONE todo may be in_progress at a time; mark previous ones as completed or pending before promoting a new one. The list is replaced atomically on each call: send the FULL desired state (any todo not in the new list is removed).",
  inputSchema: {
    type: "object",
    properties: {
      todos: {
        type: "array",
        description: "The full updated todo list for the session. Existing items not present in this array are removed; new items are created with the supplied content/activeForm/status.",
        items: {
          type: "object",
          properties: {
            content: {
              type: "string",
              description: "Imperative form describing what needs to be done (e.g. 'Run tests', 'Fix authentication bug').",
            },
            activeForm: {
              type: "string",
              description: "Present-continuous form shown during execution (e.g. 'Running tests', 'Fixing authentication bug').",
            },
            status: {
              type: "string",
              enum: ["pending", "in_progress", "completed"],
              description: "Status of this todo item. Exactly ONE may be 'in_progress' at a time.",
            },
          },
          required: ["content", "activeForm", "status"],
          additionalProperties: false,
        },
      },
    },
    required: ["todos"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    const profileId = context.profileId || "default"
    const sessionId = (context as any).sessionId
    if (!sessionId) {
      return formatToolError("No active session ID found in context.")
    }
    if (!input || typeof input !== "object" || !("todos" in input)) {
      const gotKeys = input && typeof input === "object" ? Object.keys(input).join(", ") : typeof input
      return formatToolError(
        `TodoWrite: input must be an object with a 'todos' array. Got keys: [${gotKeys}]. Expected: {todos: [{content, activeForm, status: 'pending'|'in_progress'|'completed'}]}.`,
      )
    }
    const todos = Array.isArray(input.todos) ? input.todos : []
    if (todos.length === 0) {
      return formatToolError("TodoWrite: todos array is empty. To mark all done, send [{content: 'All previous tasks completed', activeForm: 'Wrapping up', status: 'completed'}] explicitly. To clear the list, call TodoList first to confirm the state.")
    }

    // Validate each todo
    const validStatuses = new Set(["pending", "in_progress", "completed"])
    for (let i = 0; i < todos.length; i++) {
      const t = todos[i] as Record<string, unknown>
      const content = typeof t.content === "string" ? t.content.trim() : ""
      const activeForm = typeof t.activeForm === "string" ? t.activeForm.trim() : ""
      const status = typeof t.status === "string" ? t.status : ""
      if (content.length === 0) {
        return formatToolError(`todos[${i}].content cannot be empty.`)
      }
      if (activeForm.length === 0) {
        return formatToolError(`todos[${i}].activeForm cannot be empty.`)
      }
      if (!validStatuses.has(status)) {
        return formatToolError(`todos[${i}].status must be one of pending|in_progress|completed (got '${status}').`)
      }
    }

    // Structural rule: exactly ONE todo may be in_progress at a time.
    const inProgressCount = todos.filter(t => (t as any).status === "in_progress").length
    if (inProgressCount > 1) {
      return formatToolError(
        `Multiple todos are marked as in_progress (${inProgressCount}). ` +
        `Exactly ONE todo may be in_progress at a time. Mark all but one as 'pending' or 'completed'.`,
      )
    }

    // Atomic replacement: mark all existing tasks in the session as
    // superseded, then write the new ones. This is the entire state, not
    // a diff — the runtime generates fresh ids.
    const now = new Date().toISOString()
    const existing = listSessionTasks(context.rootDir, sessionId, profileId)
    const db = getDb(context.rootDir)
    for (const t of existing) {
      db.prepare(
        `UPDATE palace_nodes SET superseded_at = ? WHERE wing = 'active_tasks' AND room = ? AND node_key = ? AND superseded_at IS NULL`,
      ).run(now, sessionId, t.id)
    }

    const persisted: SessionTask[] = []
    for (const t of todos) {
      const tt = t as { content: string; activeForm: string; status: "pending" | "in_progress" | "completed" }
      const taskId = `task-${randomUUID().slice(0, 8)}`
      const task: SessionTask = {
        id: taskId,
        sessionId,
        content: tt.content,
        activeForm: tt.activeForm,
        status: tt.status,
        createdAt: now,
        updatedAt: now,
      }
      writeSessionTask(context.rootDir, sessionId, taskId, task, profileId)
      persisted.push(task)
    }

    // Verification nudge: if the entire new list is completed, has 3+
    // items, and none mentions a verification step, surface a reminder
    // so the agent adds and executes a verification step before emitting
    // a final summary. Catches the pattern of multi-step work being
    // marked done without any actual verification.
    let verificationNudge: string | undefined
    const allDone = persisted.length > 0 && persisted.every(t => t.status === "completed")
    const hasVerificationStep = persisted.some(t =>
      /\b(verif|test|check|validate|assert|confirm|audit|review|inspect|examine|run\s+tests?|build\s+and|smoke)\b/i.test(t.content),
    )
    if (allDone && persisted.length >= 3 && !hasVerificationStep) {
      verificationNudge =
        "You just closed out 3+ tasks and none of them was a verification step. " +
        "Before writing your final summary, add and execute at least one verification step " +
        "(e.g. 'Run tests', 'Validate output', 'Confirm with tool evidence') and mark it completed. " +
        "You cannot self-assign a passing verdict without a verification step in the todo list."
    }

    const result: Record<string, unknown> = {
      todos: persisted,
      totalInSession: persisted.length,
      profile: profileId,
    }
    if (verificationNudge) result.verificationNudge = verificationNudge
    return result
  },
},

{
  name: "TodoList",
  permissionTier: "read",
  description: "List tasks for the current agent profile and session.",
  inputSchema: {
    type: "object",
    properties: {
      filter: { type: "string", enum: ["all", "pending", "in_progress", "completed"] },
    },
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    const filter = optionalString(input, "filter") ?? "all"
    const profileId = context.profileId || "default"
    const sessionId = (context as any).sessionId
    if (!sessionId) {
      return formatToolError("No active session ID found in context.")
    }

    const tasks = listSessionTasks(context.rootDir, sessionId, profileId)
    const filtered = filter === "all" ? tasks : tasks.filter(t => t.status === filter)

    return {
      tasks: filtered,
      totalInSession: tasks.length,
      filter,
      profile: profileId
    }
  },
},

]
