// Auto-generated by scripts/split_registry.py — do not edit manually.
// Domain: web (3 tools)

import {
  join,
  resolve,
} from "node:path"

import {
  compactWhitespace,
  fetchWithCurl,
  formatToolError,
  htmlToReadableText,
  isValidJson,
  objectArrayField,
  optionalNumber,
  requireString,
  selectRelevantText,
  truncateText,
} from "../internal.ts"

import {
  readWebSearchConfig,
} from "../../websearch/config.ts"

import {
  SEARXNG_URL,
  deploySearxng,
} from "../../websearch/managed.ts"

import {
  writeSessionSource,
} from "../../session/store.ts"

import type { ToolDefinition } from "../registry.ts"

export const webTools: ToolDefinition[] = [
{
  name: "WebFetch",
  permissionTier: "read",
  description: "Fetch a URL and extract content relevant to a prompt.",
  inputSchema: {
    type: "object",
    properties: {
      url: { type: "string" },
      prompt: { type: "string" },
    },
    required: ["url", "prompt"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  validate: input => {
    if (typeof input.url !== "string" || !input.url.length) return "url must be a non-empty string"
    try { new URL(input.url) } catch { return "url must be a valid URL" }
    if (typeof input.prompt !== "string") return "prompt must be a string"
    return null
  },
  async run(input, context) {
    const url = requireString(input, "url")
    if (!context.sessionId?.startsWith("agent-") && /\.(jpe?g|png|webp|gif|avif|svg)(\?.*)?$/i.test(url)) {
      return formatToolError("Action denied. Use delegate_background_task instead.")
    }
    const prompt = requireString(input, "prompt")
    const startedAt = Date.now()
    let code = 0
    let codeText = ""
    let contentType = ""
    let bytes = 0
    let content = ""
    try {
      try {
        const response = await fetch(url, {
          headers: {
            "User-Agent": "MonolitoV2/1.0",
            "Accept": "application/json,text/html,application/xhtml+xml,text/plain,*/*",
          },
          signal: AbortSignal.timeout(15000),
        })
        code = response.status
        codeText = response.statusText
        contentType = response.headers.get("content-type") ?? ""
        const buffer = await response.arrayBuffer()
        bytes = buffer.byteLength
        const decoder = new TextDecoder("utf-8", { fatal: false })
        content = decoder.decode(buffer)
      } catch {
        const fallback = await fetchWithCurl(url)
        code = fallback.code
        codeText = fallback.codeText
        bytes = fallback.bytes
        content = fallback.content
      }
    } catch (error) {
      const msg = error instanceof Error ? error.message : String(error)
      return {
        url,
        prompt,
        error: msg,
        durationMs: Date.now() - startedAt,
      }
    }
    const normalizedContentType = contentType.toLowerCase()
    const trimmedContent = content.trim()
    const looksLikeJson = (trimmedContent.startsWith("{") || trimmedContent.startsWith("["))
    const isJson = /(^|[/+])json\b/.test(normalizedContentType) || (looksLikeJson && isValidJson(trimmedContent))
    if (!isJson) {
      content = /<\/?[a-z][\s\S]*>/i.test(content)
        ? htmlToReadableText(content)
        : content.replace(/\s+/g, " ").trim()
    }
    const maxChars = isJson ? 50_000 : 5_000
    const truncated = isJson
      ? content.length > maxChars ? content.slice(0, maxChars) + "..." : content
      : selectRelevantText(content, prompt, maxChars)
    const relevant = isJson
      ? truncated
      : truncated.toLowerCase().includes(prompt.toLowerCase())
      ? `[Content relevant to "${prompt}"]\n${truncated}`
      : truncated

    if (context.sessionId) {
      try {
        writeSessionSource(
          context.rootDir,
          context.sessionId,
          `WebFetch:${Date.now()}`,
          `Contenido extraído de <${url}> (Prompt: "${prompt}"):\n\n${relevant}`,
          context.profileId,
        )
      } catch (e) {
        // Ignorar errores de guardado en caché
      }
    }

    return {
      url,
      bytes,
      code,
      codeText,
      contentType,
      result: relevant,
      durationMs: Date.now() - startedAt,
    }
  },
},

{
  name: "ImageSearch",
  permissionTier: "read",
  description: "Search for images on the internet via SearxNG. Auto-deploys SearxNG Docker container if not running (localhost only). Returns clean image candidates with `image_url` (direct download URL). For simple image requests, use these direct image_url values; do not use WebFetch or scrape source pages. Use VisionAnalyze only if the user explicitly asks to verify/analyze/describe the image content.",
  inputSchema: {
    type: "object",
    properties: {
      query: { type: "string", description: "Search query for images. Be direct and specific." },
      limit: { type: "number", description: "Max number of image URLs to return (default 5)." },
    },
    required: ["query"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    const query = requireString(input, "query")
    const limit = optionalNumber(input, "limit") ?? 5
    const config = readWebSearchConfig()

    let isAdult = false
    if (context.sessionId && context.runtime && typeof (context.runtime as any).hasAdultMode === "function") {
      isAdult = (context.runtime as any).hasAdultMode(context.sessionId)
    }

    async function fetchWithBackoff(
      url: string,
      init?: RequestInit,
      maxRetries = 2
    ): Promise<Response> {
      let lastError: any = null
      for (let attempt = 0; attempt <= maxRetries; attempt++) {
        try {
          if (attempt > 0) {
            const delay = Math.pow(2, attempt) * 1000 + Math.random() * 1000
            await new Promise(resolve => setTimeout(resolve, delay))
          }
          const res = await fetch(url, init)
          if (res.status === 429 || res.status === 503) {
            lastError = new Error(`HTTP ${res.status}`)
            continue
          }
          return res
        } catch (err) {
          lastError = err
        }
      }
      throw lastError || new Error("Failed after retries")
    }

    async function runSearxngFallback() {
      const deploy = await deploySearxng()
      if (!deploy.ok) {
        throw new Error(`Error auto-desplegando SearxNG: ${deploy.message}`)
      }

      let categories = "images"
      let safesearch = "1"
      if (isAdult) {
        safesearch = "0"
        categories = "images,adult"
      }

      const encoded = encodeURIComponent(query)
      const searchUrl = `${SEARXNG_URL}/search?q=${encoded}&categories=${categories}&format=json&safesearch=${safesearch}`
      const res = await fetch(searchUrl, { signal: AbortSignal.timeout(15_000) })
      if (!res.ok) {
        throw new Error(`SearxNG returned HTTP ${res.status}`)
      }
      const data = await res.json()
      return objectArrayField(data, "results")
        .filter(r => typeof r.img_src === "string" && r.img_src.length > 0)
        .slice(0, limit)
        .map(r => {
          const imageUrl = r.img_src as string
          return {
            image_url: imageUrl,
            recommended_download_url: imageUrl,
            recommended_download_field: "image_url" as const,
            fetch_strategy: "download_image_url_directly" as const,
            title: typeof r.title === "string" ? r.title : undefined,
            source: typeof r.source === "string" ? r.source : undefined,
            thumbnail: typeof r.thumbnail_src === "string" ? r.thumbnail_src : undefined,
          }
        })
    }

    let results: Array<{
      image_url: string
      recommended_download_url: string
      recommended_download_field: "image_url"
      fetch_strategy: "download_image_url_directly"
      title?: string
      source?: string
      thumbnail?: string
    }> = []

    try {
      if (config.provider === "brave" && config.apiKey) {
        try {
          const safesearchParam = isAdult ? "off" : "moderate"
          const url = `https://api.search.brave.com/res/v1/images/search?q=${encodeURIComponent(query)}&safesearch=${safesearchParam}&count=${limit}`
          const response = await fetchWithBackoff(url, {
            headers: { "X-Subscription-Token": config.apiKey, "Accept": "application/json" },
            signal: AbortSignal.timeout(15_000)
          })
          if (!response.ok) {
            throw new Error(`Brave Search returned HTTP ${response.status}`)
          }
          const data = await response.json()
          results = objectArrayField(data, "results").map(r => {
            const properties = typeof r.properties === "object" && r.properties !== null ? r.properties as any : {}
            const thumbnail = typeof r.thumbnail === "object" && r.thumbnail !== null ? r.thumbnail as any : {}
            const imageUrl = properties.url || r.url || ""
            return {
              image_url: imageUrl,
              recommended_download_url: imageUrl,
              recommended_download_field: "image_url" as const,
              fetch_strategy: "download_image_url_directly" as const,
              title: typeof r.title === "string" ? r.title : undefined,
              source: typeof r.source === "string" ? r.source : undefined,
              thumbnail: typeof thumbnail.src === "string" ? thumbnail.src : undefined,
            }
          })
        } catch (err) {
          results = await runSearxngFallback()
        }
      } else if (config.provider === "serper" && config.apiKey) {
        try {
          const response = await fetchWithBackoff("https://google.serper.dev/images", {
            method: "POST",
            headers: { "X-API-KEY": config.apiKey, "Content-Type": "application/json" },
            body: JSON.stringify({
              q: query,
              num: limit,
              safe: isAdult ? "off" : "active"
            }),
            signal: AbortSignal.timeout(15_000)
          })
          if (!response.ok) {
            throw new Error(`Serper API returned HTTP ${response.status}`)
          }
          const data = await response.json()
          results = objectArrayField(data, "images").map(r => {
            const imageUrl = typeof r.imageUrl === "string" ? r.imageUrl : ""
            return {
              image_url: imageUrl,
              recommended_download_url: imageUrl,
              recommended_download_field: "image_url" as const,
              fetch_strategy: "download_image_url_directly" as const,
              title: typeof r.title === "string" ? r.title : undefined,
              source: typeof r.source === "string" ? r.source : (typeof r.domain === "string" ? r.domain : undefined),
              thumbnail: typeof r.thumbnailUrl === "string" ? r.thumbnailUrl : undefined,
            }
          })
        } catch (err) {
          results = await runSearxngFallback()
        }
      } else if (config.provider === "tavily" && config.apiKey) {
        try {
          const response = await fetchWithBackoff("https://api.tavily.com/search", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              api_key: config.apiKey,
              query: query,
              include_images: true,
              include_image_descriptions: true
            }),
            signal: AbortSignal.timeout(15_000)
          })
          if (!response.ok) {
            throw new Error(`Tavily API returned HTTP ${response.status}`)
          }
          const data = await response.json()
          results = objectArrayField(data, "images").slice(0, limit).map(r => {
            let imageUrl = ""
            let title = query
            if (typeof r === "string") {
              imageUrl = r
            } else if (typeof r === "object" && r !== null) {
              imageUrl = typeof (r as any).url === "string" ? (r as any).url : ""
              title = typeof (r as any).description === "string" ? (r as any).description : query
            }
            return {
              image_url: imageUrl,
              recommended_download_url: imageUrl,
              recommended_download_field: "image_url" as const,
              fetch_strategy: "download_image_url_directly" as const,
              title,
              source: "tavily",
              thumbnail: undefined,
            }
          })
        } catch (err) {
          results = await runSearxngFallback()
        }
      } else {
        // Fallback to SearXNG
        results = await runSearxngFallback()
      }

      return { ok: true, query, count: results.length, results }
    } catch (searchErr) {
      const msg = searchErr instanceof Error ? searchErr.message : String(searchErr)
      return { ok: false, error: `Search failed: ${msg}` }
    }
  },
},

{
  name: "WebSearch",
  permissionTier: "read",
  description: "Search the web for current text results via the local SearxNG instance and return clean summaries with title, URL, and snippet. CRÍTICO: PROHIBIDO usar esta herramienta para buscar, ver o analizar IMÁGENES o FOTOS. Solo devuelve texto y fallará. Para cualquier tarea visual o de imágenes, DEBES usar la herramienta de delegación a background.",
  inputSchema: {
    type: "object",
    properties: {
      query: { type: "string", description: "Free-text search query." },
    },
    required: ["query"],
    additionalProperties: false,
  },
  concurrencySafe: true,
  async run(input, context) {
    const query = requireString(input, "query")
    const config = readWebSearchConfig()
    
    let results: Array<{ title: string; url: string; snippet: string }> = []
    
    try {
      if (config.provider === "brave" && config.apiKey) {
        const url = `https://api.search.brave.com/res/v1/web/search?q=${encodeURIComponent(query)}`
        const response = await fetch(url, {
          headers: { "X-Subscription-Token": config.apiKey, "Accept": "application/json" },
          signal: AbortSignal.timeout(15_000)
        })
        if (!response.ok) {
          return { ok: false, error: `Brave Search returned HTTP ${response.status}` }
        }
        const data = await response.json()
        results = objectArrayField(data.web, "results").map(result => ({
          title: compactWhitespace(typeof result.title === "string" ? result.title : "Untitled result"),
          url: typeof result.url === "string" ? result.url : "",
          snippet: compactWhitespace(typeof result.description === "string" ? result.description : ""),
        }))
      } else if (config.provider === "serper" && config.apiKey) {
        const response = await fetch("https://google.serper.dev/search", {
          method: "POST",
          headers: { "X-API-KEY": config.apiKey, "Content-Type": "application/json" },
          body: JSON.stringify({ q: query }),
          signal: AbortSignal.timeout(15_000)
        })
        if (!response.ok) {
          return { ok: false, error: `Serper API returned HTTP ${response.status}` }
        }
        const data = await response.json()
        results = objectArrayField(data, "organic").map(result => ({
          title: compactWhitespace(typeof result.title === "string" ? result.title : "Untitled result"),
          url: typeof result.link === "string" ? result.link : "",
          snippet: compactWhitespace(typeof result.snippet === "string" ? result.snippet : ""),
        }))
      } else if (config.provider === "tavily" && config.apiKey) {
        const response = await fetch("https://api.tavily.com/search", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ api_key: config.apiKey, query: query, include_images: false }),
          signal: AbortSignal.timeout(15_000)
        })
        if (!response.ok) {
          return { ok: false, error: `Tavily API returned HTTP ${response.status}` }
        }
        const data = await response.json()
        results = objectArrayField(data, "results").map(result => ({
          title: compactWhitespace(typeof result.title === "string" ? result.title : "Untitled result"),
          url: typeof result.url === "string" ? result.url : "",
          snippet: compactWhitespace(typeof result.content === "string" ? result.content : ""),
        }))
      } else {
        // Fallback to SearXNG
        const deploy = await deploySearxng()
        if (!deploy.ok) return formatToolError(`Error auto-desplegando SearxNG: ${deploy.message}`)
        const searchUrl = `${SEARXNG_URL}/search?q=${encodeURIComponent(query)}&format=json`
        const response = await fetch(searchUrl, { signal: AbortSignal.timeout(15_000) })
        if (!response.ok) {
          return { ok: false, error: `SearxNG returned HTTP ${response.status}` }
        }
        const data = await response.json()
        results = objectArrayField(data, "results")
          .filter(result => typeof result.url === "string" && result.url.length > 0)
          .map(result => ({
            title: compactWhitespace(typeof result.title === "string" ? result.title : "Untitled result"),
            url: typeof result.url === "string" ? result.url : "",
            snippet: compactWhitespace(typeof result.content === "string" ? result.content : ""),
          }))
      }

      results = results.slice(0, 8)

      const formatted = results.length === 0
        ? "No results found."
        : results
          .map((result, index) => {
            const snippet = result.snippet ? `\n${truncateText(result.snippet, 280)}` : ""
            return `${index + 1}. ${result.title}\n${result.url}${snippet}`
          })
          .join("\n\n")

      // Auto-Scrape de la primera fuente (top result) para enriquecer la respuesta
      let autoFetchContent = ""
      const topResult = results[0]
      if (topResult && topResult.url && !/\.(jpe?g|png|webp|gif|avif|svg|pdf)(\?.*)?$/i.test(topResult.url)) {
        try {
          const fetchRes = await fetch(topResult.url, {
            headers: {
              "User-Agent": "MonolitoV2/1.0",
              "Accept": "text/html,application/xhtml+xml,text/plain,*/*",
            },
            signal: AbortSignal.timeout(3000), // Timeout corto de 3 segundos
          })
          if (fetchRes.ok) {
            const contentType = fetchRes.headers.get("content-type") ?? ""
            const buffer = await fetchRes.arrayBuffer()
            const decoder = new TextDecoder("utf-8", { fatal: false })
            let rawText = decoder.decode(buffer)
            if (rawText) {
              rawText = /<\/?[a-z][\s\S]*>/i.test(rawText)
                ? htmlToReadableText(rawText)
                : rawText.replace(/\s+/g, " ").trim()
              if (rawText) {
                autoFetchContent = rawText.slice(0, 4000) // Primeros 4000 caracteres
              }
            }
          }
        } catch (e) {
          // Silenciosamente ignorar fallas de autofetch
        }
      }

      let finalFormatted = formatted
      if (autoFetchContent) {
        finalFormatted += `\n\n=== CONTENIDO EXTRAÍDO AUTOMÁTICAMENTE DE LA PRIMERA FUENTE (${topResult.url}) ===\n${autoFetchContent}`
      }

      if (context.sessionId) {
        try {
          writeSessionSource(
            context.rootDir,
            context.sessionId,
            `WebSearch:${Date.now()}`,
            `Resultados de búsqueda para "${query}":\n\n${finalFormatted}`,
            context.profileId,
          )
        } catch (e) {
          // Ignorar errores de guardado en caché
        }
      }

      return { ok: true, query, count: results.length, results, formatted: finalFormatted }
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error)
      return { ok: false, error: `Search failed: ${message}` }
    }
  },
},

]
